import test from 'node:test';import assert from 'node:assert/strict';
import {fresh} from '../app/systems/state.ts';
import {completeChapter,progress,recordVictory} from '../app/systems/progression.ts';
import {prepareChapterSwitch} from '../app/systems/chapter-manager.ts';
import {encode,decode} from '../app/systems/save.ts';
import chapter from '../app/chapters/chapter-2/chapter-config.ts';
import {flags,won,bridgeOpen,naveOpen,choirReady} from '../app/chapters/chapter-2/state.ts';
import {walkable} from '../app/chapters/chapter-2/terrain.ts';
import {placements} from '../app/chapters/chapter-2/object-config.ts';
import {damage,enemyAttack} from '../app/chapters/chapter-2/enemy-config.ts';
function state(){let s=fresh();completeChapter(s.campaign,['chapter-2']);s.lv=3;s.hp=148;s.mp=46;return prepareChapterSwitch(s,'chapter-2',chapter.start)}
function context(){const s=state();chapter.initialize(s);const c={state:s,progress:progress(s.campaign),modal:'',objects:[],talk:(_n,lines,after)=>{c.lines=lines;c.after=after},save:()=>{},notify:t=>c.notice=t,renderUI:()=>{},build:()=>{},burst:()=>{},height:()=>0,maxHP:()=>148,maxMP:()=>46,startBattle:o=>c.battle=o.id,transition:async n=>{s.area=n},finish:()=>c.finished=true};return c}
function reachable(s,start,target){const step=.75,q=[[Math.round(start.x/step),Math.round(start.z/step)]],seen=new Set([q[0].join(',')]);for(let i=0;i<q.length;i++){const [x,z]=q[i];if(Math.hypot(x*step-target.x,z*step-target.z)<1.1)return true;for(const [dx,dz]of [[1,0],[-1,0],[0,1],[0,-1]]){const a=x+dx,b=z+dz,k=[a,b].join(',');if(!seen.has(k)&&walkable(s,a*step,b*step)){seen.add(k);q.push([a,b])}}}return false}
test('Chapter 2 cannot be selected before Chapter 1 clear; prior progress survives round trip',()=>{assert.throws(()=>prepareChapterSwitch(fresh(),'chapter-2',chapter.start),/解放/);const s=state();flags(s).beacons=2;progress(s.campaign).chests.push('harbor');const back=prepareChapterSwitch(s,'chapter-1',{area:0,x:0,z:8});const again=prepareChapterSwitch(decode(JSON.stringify(encode(back))),'chapter-2',chapter.start);assert.equal(flags(again).beacons,2);assert.deepEqual(progress(again.campaign).chests,['harbor']);assert.ok(again.campaign.completedChapters.includes('chapter-1'))});
test('all Chapter 2 entrypoints are lazy modules and spawns are on valid floors',async()=>{const s=state();flags(s).beacons=3;flags(s)['nave-west']=flags(s)['nave-east']=true;recordVictory(s.campaign,'bellwarden',true);for(const m of chapter.maps){assert.equal(typeof(await m.load()).build,'function');s.area=m.id;assert.ok(walkable(s,m.spawn.x,m.spawn.z),m.name);for(const p of placements[m.id])assert.ok(reachable(s,m.spawn,p),m.name+': '+p.id)}});
test('sea and unlit gates are impassable, illuminated routes become reachable',()=>{const s=state();s.area=1;assert.equal(walkable(s,18,0),false);assert.equal(reachable(s,{x:0,z:18},{x:0,z:-19}),false);flags(s).beacons=3;assert.ok(reachable(s,{x:0,z:18},{x:0,z:-19}));s.area=2;assert.equal(reachable(s,{x:0,z:18},{x:0,z:-15}),false);flags(s)['nave-west']=true;assert.equal(reachable(s,{x:0,z:18},{x:0,z:-15}),false);flags(s)['nave-east']=true;assert.ok(reachable(s,{x:0,z:18},{x:0,z:-19}))});
test('investigation requires three clues and supplies are granted only once',()=>{const c=context(),f=flags(c.state);const npc=id=>placements[0].find(p=>p.id===id);chapter.interact(c,npc('keeper'));chapter.interact(c,npc('bell'));chapter.interact(c,npc('boat'));chapter.interact(c,npc('keeper'));assert.equal(f.permit,undefined);chapter.interact(c,npc('star'));chapter.interact(c,npc('keeper'));chapter.interact(c,npc('keeper'));assert.equal(f.permit,true);assert.equal(c.state.potions,7);assert.equal(c.state.ethers,5)});
test('wrong beacon order cannot open bridge; correct order persists and rewards cannot duplicate',()=>{const c=context();c.state.area=1;c.objects=placements[1];c.modal='beacon:star-beacon';chapter.action(c,'ignite-beacon');assert.equal(bridgeOpen(c.state),false);for(const id of ['bell','boat','star']){c.modal='beacon:'+id+'-beacon';chapter.action(c,'ignite-beacon')}assert.equal(bridgeOpen(c.state),true);chapter.interact(c,{kind:'chest',id:'tools'});const gold=c.state.gold;chapter.interact(c,{kind:'chest',id:'tools'});assert.equal(c.state.gold,gold);const loaded=decode(JSON.stringify(encode(c.state)));assert.equal(bridgeOpen(loaded),true)});
test('midboss opens choir without clearing chapter; final boss clears and unlocks Chapter 3',()=>{const c=context();chapter.onBossVictory(c,'bellwarden');assert.equal(c.progress.completed,false);chapter.interact(c,{kind:'boss',id:'nereis'});assert.equal(c.battle,undefined);for(const id of ['vigil-west','vigil-east','vigil-heart'])flags(c.state)[id]=true;chapter.interact(c,{kind:'boss',id:'nereis'});c.after();assert.equal(c.battle,'nereis');chapter.onBossVictory(c,'nereis');assert.equal(c.progress.completed,true);assert.ok(c.state.campaign.unlockedChapters.includes('chapter-3'));c.after();assert.equal(c.finished,true)});
test('enemy traits and the relight mechanic reward informed command choices',()=>{const c=context();assert.ok(damage(c,'shell',1,'fire',50)>damage(c,'shell',1,'attack',50));assert.equal(damage(c,'jelly',3,'attack',50),25);assert.equal(damage(c,'jelly',3,'fire',50),50);assert.ok(enemyAttack(c,'moth',1,'fire',23)<23);assert.ok(damage(c,'nereis',3,'fire',50)>damage(c,'nereis',3,'attack',50));assert.equal(damage(c,'nereis',3,'guard',0),0)});
