import test from 'node:test';import assert from 'node:assert/strict';
import {fresh} from '../app/systems/state.ts';
import {createProgress} from '../app/systems/progression.ts';
import {encode,decode} from '../app/systems/save.ts';
import {prepareChapterSwitch} from '../app/systems/chapter-manager.ts';
import {migrateTrials,takeUnlockNotice,equip,reward,maxHealth,attackBonus,incoming,regenerate,chapter2Cleared} from '../app/trials/state.ts';
import {createRun,resolveTurn,allowed,hidden,totalHP} from '../app/trials/rules.ts';
const ready=()=>{const s=fresh();s.lv=8;s.hp=268;s.mp=86;s.campaign.chapters['chapter-2']={...createProgress(),completed:true};s.campaign.completedChapters.push('chapter-2');migrateTrials(s);return s};
const old=(cleared)=>{const s=ready();s.campaign.chapters['chapter-2'].completed=cleared;s.campaign.completedChapters=cleared?['chapter-2']:[];s.gold=321;s.potions=7;s.hp=201;s.campaign.chapters['chapter-1'].flags.custom='kept';const d=encode(s);delete d.player.trials;return d};
test('old incomplete save remains locked even with a forged new unlock field',()=>{const d=old(false);d.player.trials={unlocked:true};const s=decode(JSON.stringify(d));assert.equal(s.trials.unlocked,false);assert.throws(()=>prepareChapterSwitch(s,'trials',{area:0,x:0,z:7}));});
test('old Chapter 2 complete save migrates without resetting any existing field',()=>{const d=old(true),s=decode(JSON.stringify(d));assert.equal(s.trials.unlocked,true);assert.equal(s.gold,321);assert.equal(s.hp,201);assert.equal(s.potions,7);assert.equal(s.campaign.chapters['chapter-1'].flags.custom,'kept');assert.equal(s.campaign.chapters['chapter-2'].completed,true);assert.deepEqual(s.trials.unlockedTrials,[1]);});
test('official false completion prevents early boss flag unlock; legacy corroboration only without formal field',()=>{const s=ready();s.campaign.completedChapters=[];const p=s.campaign.chapters['chapter-2'];p.completed=false;p.bosses=['nereis'];p.flags.starGlass=true;p.quests['missing-lights']='complete';assert.equal(chapter2Cleared(s),false);delete p.completed;assert.equal(chapter2Cleared(s),true)});
test('unlock notice occurs once and remains acknowledged after encode/decode',()=>{let s=decode(JSON.stringify(old(true)));assert.equal(takeUnlockNotice(s),true);s=decode(JSON.stringify(encode(s)));assert.equal(takeUnlockNotice(s),false);assert.equal(s.trials.unlocked,true)});
test('rewards unlock sequentially, grant once, and retain best records',()=>{let s=ready();assert.equal(reward(s,2,1,100),false);for(let i=1;i<=5;i++){assert.equal(reward(s,i,20,120),true);assert.equal(reward(s,i,25,130),false);assert.equal(s.trials.best[i].turns,20)}assert.equal(s.trials.owned.length,5);s=decode(JSON.stringify(encode(s)));assert.deepEqual(s.trials.unlockedTrials,[1,2,3,4,5]);});
test('two accessory slots, duplicates blocked, 8 percent effects and HP cap persist',()=>{const s=ready();for(let i=1;i<=5;i++)reward(s,i,10,100);assert.equal(equip(s,0,'warden'),true);assert.equal(equip(s,1,'warden'),false);assert.equal(incoming(s,100,false,()=>1),93);equip(s,1,'afterglow');assert.equal(attackBonus(s,100),108);equip(s,0,'mist');assert.equal(maxHealth(s),294);s.hp=294;assert.equal(decode(JSON.stringify(encode(s))).hp,294);equip(s,0,null);assert.equal(s.hp,268);equip(s,0,'phantom');assert.equal(incoming(s,100,false,()=>.079),0);assert.equal(incoming(s,100,false,()=>.08),100);});
test('eternal heals 3 percent at live turn start, never above cap or from zero; no-heal suppresses it',()=>{const s=ready();s.trials.owned=['eternal'];equip(s,0,'eternal');s.hp=200;assert.equal(regenerate(s),8);assert.equal(s.hp,208);assert.equal(regenerate(s,true),0);s.hp=267;assert.equal(regenerate(s),1);assert.equal(regenerate(s),0);s.hp=0;assert.equal(regenerate(s),0);});
test('lamp defense reduces lamp damage and zero lamp is a special loss',()=>{const s=ready(),a=createRun(1),b=createRun(1);resolveTurn(a,s,'guard',0,()=>1);resolveTurn(b,ready(),'protect',0,()=>1);assert.ok(b.lamp>a.lamp);a.lamp=1;resolveTurn(a,s,'guard',0,()=>1);assert.equal(a.result,'lose');});
test('mist reveal lasts three subsequent command selections; unavailable commands are rejected',()=>{const s=ready(),r=createRun(3);assert.equal(hidden(r),true);resolveTurn(r,s,'raise',0,()=>1);for(let i=0;i<3;i++){assert.equal(hidden(r),false);resolveTurn(r,s,'guard',0,()=>1)}assert.equal(hidden(r),true);assert.equal(allowed(r,'shard'),false)});
test('no-heal blocks all recovery and preserves HP across three waves',()=>{const s=ready(),r=createRun(4);for(const cmd of ['heal','potion','ether'])assert.equal(allowed(r,cmd),false);s.hp=140;resolveTurn(r,s,'attack',999,()=>1);assert.equal(r.wave,2);assert.equal(s.hp,140);resolveTurn(r,s,'attack',999,()=>1);resolveTurn(r,s,'attack',999,()=>1);assert.equal(r.result,'win');assert.equal(s.hp,140);});
function play(id){const s=ready(),r=createRun(id);s.potions=4;s.ethers=3;let safety=0;while(r.result==='active'&&safety++<100){let cmd='fire';if(id===1){const lamp=r.foes.findIndex(f=>f.hp>0&&f.target!=='hero');if(lamp>=0)r.target=lamp}
 if(id===2)cmd=s.hp<80?'potion':'guard';
 if(id===4&&(r.turn+1)%3===0)cmd='guard';
 if(id===3&&((r.turn+1)%3===0))cmd='guard';
 if(id===5){if((r.turn+1)%3===0)cmd='protect';else if(s.hp<65)cmd=s.potions?'potion':'heal';else if(r.lamp<=45&&r.shards)cmd='shard';}
 if(cmd==='heal'&&s.mp<5)cmd='ether';if(cmd==='fire'&&s.mp<6)cmd=id===4?'attack':'ether';if(cmd==='potion'&&!s.potions)cmd='heal';
 if(cmd==='fire')s.mp-=6;if(cmd==='heal'){s.mp-=5;s.hp=Math.min(maxHealth(s),s.hp+58)}if(cmd==='potion'){s.potions--;s.hp=Math.min(maxHealth(s),s.hp+65)}if(cmd==='ether'){if(!s.ethers){cmd='attack'}else{s.ethers--;s.mp=Math.min(86,s.mp+20)}}
 const d=cmd==='fire'?81:cmd==='attack'?49:0;resolveTurn(r,s,cmd,d,()=>1);
 }return {r,s}}
for(let id=1;id<=5;id++)test('trial '+id+' is winnable at Chapter 2 clear level without random evasion',()=>{const {r,s}=play(id);assert.equal(r.result,'win',JSON.stringify({id,turn:r.turn,hp:s.hp,lamp:r.lamp}));if(id===2)assert.equal(r.turn,15);});

test('defeated enemies disappear from trial HP text and target commands',async()=>{const {trialStatus}=await import('../app/trials/ui.ts');const r=createRun(2),s=ready();resolveTurn(r,s,'fire',999,()=>1);const html=trialStatus(r,(_id,label)=>label,false);assert.ok(!html.includes('残響の兵'));assert.ok(html.includes('残響の弓手'));for(let i=0;i<3;i++)resolveTurn(r,s,'guard',0,()=>1);assert.ok(trialStatus(r,(_id,label)=>label,false).includes('増援の影'));});
test('fourth trial replaces each defeated foe without retaining its HP or name',async()=>{const {trialStatus}=await import('../app/trials/ui.ts');const r=createRun(4),s=ready();s.hp=140;for(const [oldName,newName] of [['傷なき影','乾いた守衛'],['乾いた守衛','無癒の番獣']]){resolveTurn(r,s,'fire',999,()=>1);const html=trialStatus(r,(_id,label)=>label,false);assert.ok(!html.includes(oldName));assert.ok(html.includes(newName));assert.equal(s.hp,140)}resolveTurn(r,s,'fire',999,()=>1);assert.equal(r.result,'win')});

test('fourth trial punishes sword spam but telegraphed guarding is survivable',()=>{const r=createRun(4),s=ready();while(r.result==='active'&&r.turn<50)resolveTurn(r,s,'attack',49,()=>1);assert.equal(r.result,'lose');const a=createRun(4),b=createRun(4);a.turn=b.turn=2;const sa=ready(),sb=ready();resolveTurn(a,sa,'attack',0,()=>1);resolveTurn(b,sb,'guard',0,()=>1);assert.ok(sb.hp>sa.hp);assert.equal(play(4).r.result,'win')});
