import test from 'node:test';import assert from 'node:assert/strict';import * as T from 'three';
import {fresh} from '../app/systems/state.ts';import {progress,createProgress,recordVictory} from '../app/systems/progression.ts';import {encode,decode} from '../app/systems/save.ts';import {prepareChapterSwitch} from '../app/systems/chapter-manager.ts';
import chapter from '../app/chapters/chapter-3/chapter-config.ts';import {flags,canEnter} from '../app/chapters/chapter-3/state.ts';import {placements} from '../app/chapters/chapter-3/object-config.ts';import {createFight,deal,retaliation,forecast} from '../app/chapters/chapter-3/combat.ts';
import {migrateTrials,reward,equip,maxHealth,attackBonus,incoming,regenerate} from '../app/trials/state.ts';
function old(){const s=fresh();s.lv=8;s.hp=201;s.mp=65;s.gold=321;s.potions=7;s.ethers=4;const p=s.campaign.chapters['chapter-2']=createProgress();p.completed=true;p.bosses=['nereis'];p.flags.starGlass=true;p.quests['missing-lights']='complete';s.campaign.completedChapters=['chapter-1','chapter-2'];s.campaign.unlockedChapters=['chapter-1','chapter-2'];migrateTrials(s);for(let i=1;i<=5;i++)reward(s,i,20,90);equip(s,0,'afterglow');equip(s,1,'eternal');return s}
function state(){const s=decode(JSON.stringify(encode(old())));return prepareChapterSwitch(s,'chapter-3',chapter.start)}
function context(){const s=state();chapter.initialize(s);const c={state:s,progress:progress(s.campaign),world:new T.Group(),scene:new T.Scene(),ambient:new T.HemisphereLight(),sun:new T.DirectionalLight(),objects:[],blocks:[],mobile:true,animationTime:{value:0},modal:'',mode:'explore',talk:(_n,l,cb)=>{c.lines=l;c.after=cb},save:()=>{},notify:t=>c.notice=t,renderUI:()=>{},build:()=>{},burst:()=>{},maxHP:()=>maxHealth(s),maxMP:()=>86,finish:()=>c.finished=true,transition:async n=>{s.area=n},startBattle:o=>c.enemy=o.id,rand:n=>Math.abs(Math.sin(n*13)%1),mat:(color,roughness=.9)=>new T.MeshStandardMaterial({color,roughness}),light:()=>{},height:(x,z)=>chapter.height(s,x,z),addObj:(kind,name,x,z,id)=>{const o={kind,name,x,z,id,r:2.3};c.objects.push(o);return o}};c.box=(x,y,z,w,h,d,m)=>{const mesh=new T.Mesh(new T.BoxGeometry(w,h,d),m);mesh.position.set(x,y,z);c.world.add(mesh);return mesh};c.cyl=(x,y,z,r,h,m,n=8)=>{const mesh=new T.Mesh(new T.CylinderGeometry(r,r,h,n),m);mesh.position.set(x,y,z);c.world.add(mesh);return mesh};c.sprite=(kind,x,z)=>{const sp=new T.Sprite();sp.position.set(x,c.height(x,z),z);c.world.add(sp);return sp};c.chest=(x,z,id)=>c.addObj('chest','宝箱',x,z,id);return c}
function reachable(c,start,target){const step=.75,q=[[Math.round(start.x/step),Math.round(start.z/step)]],seen=new Set([q[0].join(',')]);for(let i=0;i<q.length;i++){const [a,b]=q[i];if(Math.hypot(a*step-target.x,b*step-target.z)<1.2)return true;for(const [dx,dz]of [[1,0],[-1,0],[0,1],[0,-1]]){const x=a+dx,z=b+dz,k=x+','+z;if(!seen.has(k)&&chapter.walkable(c.state,x*step,z*step)&&!c.blocks.some(r=>Math.abs(x*step-r.x)<r.w/2+.23&&Math.abs(z*step-r.z)<r.d/2+.23)){seen.add(k);q.push([x,z])}}}return false}
test('Chapter 3 unlock migrates official old clears without losing trial/player fields',()=>{const s=old(),d=encode(s),loaded=decode(JSON.stringify(d));assert.ok(loaded.campaign.unlockedChapters.includes('chapter-3'));assert.deepEqual(loaded.trials,s.trials);for(const k of ['hp','mp','lv','xp','gold','potions','ethers','sword','armor'])assert.equal(loaded[k],s[k]);assert.deepEqual(loaded.campaign.chapters,s.campaign.chapters);assert.ok(!loaded.campaign.chapters['chapter-3']);});
test('incomplete Chapter 2 cannot enter Chapter 3 even through a forged unlock',()=>{const s=old();s.campaign.completedChapters=[];s.campaign.chapters['chapter-2'].completed=false;s.campaign.unlockedChapters.push('chapter-3');assert.throws(()=>prepareChapterSwitch(s,'chapter-3',chapter.start));const loaded=decode(JSON.stringify(encode(s)));assert.ok(!loaded.campaign.unlockedChapters.includes('chapter-3'))});
test('all five maps load lazily and every interaction is reachable with real scenery collisions',async()=>{for(const map of chapter.maps){const c=context();const f=flags(c.state);f.history=f.smith=f.watcher=f.evidence=f.record=f['hearth-west']=f['hearth-east']=true;recordVictory(c.state.campaign,'warden',true);c.state.area=map.id;const module=await map.load();module.build(c);assert.ok(chapter.walkable(c.state,map.spawn.x,map.spawn.z),map.name);for(const o of c.objects)assert.ok(reachable(c,map.spawn,o),map.name+': '+o.id);const snow=c.world.children.find(o=>o instanceof T.Points);assert.equal(snow.geometry.attributes.position.count,110);assert.ok(c.world.children.length<400,'finite scene budget');c.world.traverse(o=>{o.geometry?.dispose();if(o.material?.dispose)o.material.dispose()})}});
test('gate, evidence and two sanctuary lamps enforce story order',()=>{const c=context(),s=c.state,f=flags(s);assert.equal(canEnter(s,2),false);s.area=1;chapter.interact(c,placements[1].find(o=>o.id==='warden'));assert.equal(c.enemy,undefined);for(const id of ['elder','smith','watcher'])chapter.interact(c,placements[1].find(o=>o.id===id));chapter.interact(c,placements[1].find(o=>o.id==='warden'));assert.equal(c.enemy,'warden');recordVictory(s.campaign,'warden',true);assert.equal(canEnter(s,2),true);assert.equal(canEnter(s,3),false);s.area=2;const evidence=placements[2].find(o=>o.id==='memory');chapter.interact(c,evidence);assert.equal(f.evidence,undefined);recordVictory(s.campaign,'soldier',false);recordVictory(s.campaign,'shade',false);chapter.interact(c,evidence);assert.equal(canEnter(s,3),true);s.area=3;chapter.interact(c,placements[3].find(o=>o.id==='record'));recordVictory(s.campaign,'hunter',false);for(const id of ['hearth-west','hearth-east'])chapter.interact(c,placements[3].find(o=>o.id===id));assert.equal(canEnter(s,4),true)});
test('supplies and treasure grants are idempotent across saves',()=>{const c=context();c.state.area=1;const elder=placements[1].find(o=>o.id==='elder');chapter.interact(c,elder);const n=c.state.potions;chapter.interact(c,elder);assert.equal(c.state.potions,n);chapter.interact(c,{kind:'chest',id:'village'});const snapshot=encode(c.state);chapter.interact(c,{kind:'chest',id:'village'});assert.deepEqual(encode(c.state),snapshot);assert.deepEqual(decode(JSON.stringify(snapshot)).campaign, c.state.campaign)});
test('shield telegraph rewards fire break or waiting and mist never causes guaranteed misses',()=>{const r=createFight();assert.equal(deal(r,'warden',1,'attack',100),30);assert.equal(deal(r,'warden',2,'attack',100),80);assert.equal(deal(r,'warden',4,'fire',100),145);assert.equal(deal(r,'warden',5,'attack',100),145);assert.equal(deal(r,'shade',3,'attack',100),75);assert.equal(deal(r,'shade',3,'fire',100),100);assert.match(forecast('warden',1),/盾/)});
test('freezing can be thawed by fire and avalanche warns two actions ahead',()=>{const a=createFight(),b=createFight();deal(a,'aurel',1,'attack',49);retaliation(a,'aurel',1,'attack',1);assert.equal(a.freeze,1);deal(a,'aurel',2,'fire',81);const safe=retaliation(a,'aurel',2,'fire',1);deal(b,'aurel',1,'attack',49);retaliation(b,'aurel',1,'attack',1);deal(b,'aurel',2,'attack',49);assert.equal(retaliation(b,'aurel',2,'attack',1),safe+45);assert.match(forecast('aurel',6,2),/3行動/);assert.match(forecast('aurel',7,2),/2行動/);assert.match(forecast('aurel',8,2),/今、防御/)});
function battle(id,access=false){const s=state();s.trials.slots=access?['afterglow','eternal']:[null,null];s.hp=maxHealth(s);s.mp=86;s.potions=4;s.ethers=5;const r=createFight();let hp=chapter.enemies[id].hp,turn=0,phase=1;while(hp>0&&s.hp>0&&turn++<80){let cmd='fire';if(id==='aurel'&&(turn%8===4||phase===2&&turn%8===0))cmd='guard';else if(s.hp<75)cmd=s.potions?'potion':'heal';else if(s.mp<6)cmd=s.ethers?'ether':'attack';if(cmd==='fire')s.mp-=6;if(cmd==='potion'){s.potions--;s.hp=Math.min(maxHealth(s),s.hp+65)}if(cmd==='heal'){if(s.mp<5)cmd='attack';else{s.mp-=5;s.hp=Math.min(maxHealth(s),s.hp+58)}}if(cmd==='ether'){s.ethers--;s.mp=Math.min(86,s.mp+20)}hp-=deal(r,id,turn,cmd,cmd==='fire'?attackBonus(s,81):cmd==='attack'?attackBonus(s,49):0);if(hp<=0)break;if(hp<=chapter.enemies[id].hp/2)phase=2;s.hp=Math.max(0,s.hp-incoming(s,retaliation(r,id,turn,cmd,phase),cmd==='guard',()=>1));regenerate(s)}return {hp,s,turn,phase}}
for(const id of ['frost','soldier','shade','hunter','warden','aurel'])test(id+' is beatable without accessories at Chapter 2 clear level',()=>{const r=battle(id);assert.ok(r.hp<=0,JSON.stringify({id,hp:r.hp,player:r.s.hp,turn:r.turn}));if(id==='aurel')assert.equal(r.phase,2)});
test('accessories stay effective in Chapter 3 and survive round trips',()=>{const s=state();assert.equal(attackBonus(s,100),108);equip(s,0,'warden');assert.equal(incoming(s,100,false,()=>1),93);equip(s,0,'mist');assert.equal(maxHealth(s),294);equip(s,1,'phantom');assert.equal(incoming(s,100,false,()=>.01),0);equip(s,1,'eternal');s.hp=100;assert.equal(regenerate(s),8);flags(s).evidence=true;for(const id of ['chapter-1','chapter-2','trials']){const target=prepareChapterSwitch(s,id,{area:0,x:0,z:7});const back=prepareChapterSwitch(decode(JSON.stringify(encode(target))),'chapter-3',chapter.start);assert.deepEqual(back.trials,s.trials);assert.equal(flags(back).evidence,true)}});
test('boss survives as dialogue, ending completes and chapter clear persists',async()=>{const c=context();recordVictory(c.state.campaign,'warden',true);recordVictory(c.state.campaign,'aurel',true);assert.equal(chapter.enemies.aurel.keepAfterVictory,true);chapter.onBossVictory(c,'aurel');for(let i=0;i<12&&!c.finished;i++){const cb=c.after;c.after=undefined;cb?.();await Promise.resolve()}assert.equal(c.finished,true);assert.ok(c.progress.completed);const loaded=decode(JSON.stringify(encode(c.state)));assert.ok(loaded.campaign.completedChapters.includes('chapter-3'));assert.equal(flags(loaded).endingComplete,true);assert.equal(loaded.trials.cleared.length,5)});

test('phase change cannot trigger an avalanche without two preparation selections',()=>{for(const turn of [6,7,8]){const r=createFight();retaliation(r,'aurel',turn,'fire',2);if(turn===7){assert.doesNotMatch(forecast('aurel',8,2,r.phaseAt),/雪崩/);assert.equal(retaliation(r,'aurel',8,'guard',2),27)}if(turn===8)assert.equal(retaliation(r,'aurel',8,'guard',2),27)}assert.match(forecast('aurel',7,2,5),/2行動/);assert.equal(retaliation({...createFight(),phase:2,phaseAt:5},'aurel',8,'guard',2),100)});

test('furnace blocks the whole plinth and rescues old saves without losing progress',()=>{const s=state();const p=progress(s.campaign);p.defeatedEnemies.push('warden','aurel');Object.assign(p.flags,{evidence:true,record:true,'hearth-west':true,'hearth-east':true});s.area=4;s.x=0;s.z=-11;const before=structuredClone(s);chapter.normalize(s);assert.equal(chapter.walkable(s,s.x,s.z),true);assert.equal(s.z,-3.8);assert.deepEqual(s.trials,before.trials);assert.deepEqual(s.campaign,before.campaign);for(let a=0;a<Math.PI*2;a+=.1)assert.equal(chapter.walkable(s,Math.cos(a)*5.7,-11+Math.sin(a)*5.7),false);for(const id of ['aurel','echo']){const o=placements[4].find(o=>o.id===id);assert.ok(chapter.walkable(s,o.x,o.z));assert.ok(Math.hypot(o.x,o.z+11)>5.9)}});
test('post-boss conversation is reachable outside the plinth with extended range',async()=>{const c=context();c.state.area=4;Object.assign(flags(c.state),{evidence:true,record:true,'hearth-west':true,'hearth-east':true});recordVictory(c.state.campaign,'warden',true);recordVictory(c.state.campaign,'aurel',true);(await chapter.maps[4].load()).build(c);const o=c.objects.find(o=>o.id==='echo');assert.ok(o);assert.equal(o.r,3.4);assert.ok(reachable(c,chapter.maps[4].spawn,o));assert.ok(chapter.walkable(c.state,0,-1));assert.ok(Math.hypot(o.x,o.z+1)<o.r);chapter.interact(c,o);assert.ok(c.lines.length);assert.equal(typeof c.after,'function')});
