// Runs the actual game controller and DOM input. Rendering is stubbed: not a GPU/browser benchmark.
import test from 'node:test';import assert from 'node:assert/strict';import {registerHooks,stripTypeScriptTypes} from 'node:module';import {existsSync,readFileSync} from 'node:fs';import {fileURLToPath} from 'node:url';import {JSDOM} from 'jsdom';
registerHooks({resolve(spec,ctx,next){if(spec.startsWith('.')&&!/\.(ts|js|mjs|css)$/.test(spec)&&ctx.parentURL?.includes('/app/')){const u=new URL(spec+'.ts',ctx.parentURL);if(existsSync(u))return next(u.href,ctx)}return next(spec,ctx)},load(url,ctx,next){if(url.endsWith('/software.ts'))return {format:'module',source:stripTypeScriptTypes(readFileSync(new URL(url),'utf8'),{mode:'transform'}),shortCircuit:true};if(url.endsWith('.css'))return {format:'module',source:'',shortCircuit:true};return next(url,ctx)}});
const {fresh}=await import('../app/systems/state.ts');const {createProgress}=await import('../app/systems/progression.ts');const {encode,decode}=await import('../app/systems/save.ts');const {startGame}=await import('../app/game.ts');const {SoftwareRenderer}=await import('../app/software.ts');
function completed3(){const s=fresh();s.lv=11;s.hp=340;s.mp=110;s.potions=8;s.ethers=7;s.sword=s.armor=true;s.gold=420;for(const id of ['chapter-1','chapter-2','chapter-3']){s.campaign.chapters[id]=createProgress();s.campaign.chapters[id].completed=true}s.campaign.completedChapters=['chapter-1','chapter-2','chapter-3'];s.campaign.unlockedChapters=[...s.campaign.completedChapters];s.campaign.currentChapter='chapter-3';s.area=0;s.x=0;s.z=17;return s}
async function harness(width=1280,search='',saved=completed3()){
 const dom=new JSDOM('<main><canvas id="world"></canvas><div id="ui"></div><div id="fade"></div><div id="floaters"></div><div id="loading"></div></main>',{url:'https://test.invalid/'+search,pretendToBeVisual:true});const w=dom.window;let now=0,seq=0;const jobs=new Map(),original=new Map();
 const set=(k,v)=>{original.set(k,Object.getOwnPropertyDescriptor(globalThis,k));Object.defineProperty(globalThis,k,{configurable:true,writable:true,value:v})};
 for(const k of ['window','document','localStorage','location','HTMLElement','HTMLCanvasElement'])set(k,k==='window'?w:w[k]);set('AudioContext',class {state='running';currentTime=0;destination={};resume(){}close(){}createOscillator(){return {frequency:{value:0},connect(){},start(){},stop(){}}}createGain(){return {gain:{setValueAtTime(){},exponentialRampToValueAtTime(){}},connect(){}}}});set('innerWidth',width);set('innerHeight',width<600?844:800);set('devicePixelRatio',1);set('matchMedia',()=>({matches:width<600}));set('performance',{now:()=>now});
 const timeout=(fn,ms=0)=>{const id=++seq;jobs.set(id,{fn,at:now+ms});return id},clear=id=>jobs.delete(id);set('setTimeout',timeout);set('clearTimeout',clear);set('requestAnimationFrame',fn=>timeout(()=>fn(now),16));set('cancelAnimationFrame',clear);w.setTimeout=timeout;w.clearTimeout=clear;
 const ctx2=new Proxy({createImageData:(x,y)=>({data:new Uint8ClampedArray(x*y*4)}),createLinearGradient:()=>({addColorStop(){}}),createRadialGradient:()=>({addColorStop(){}})},{get:(o,k)=>k in o?o[k]:(()=>{})});w.HTMLCanvasElement.prototype.getContext=function(type){return type==='2d'?ctx2:null};
 w.HTMLElement.prototype.setPointerCapture=function(id){this._capture=id};w.HTMLElement.prototype.hasPointerCapture=function(id){return this._capture===id};w.HTMLElement.prototype.releasePointerCapture=function(){this._capture=null};
 let renders=0;const originalRender=SoftwareRenderer.prototype.render;SoftwareRenderer.prototype.render=function(scene,camera){renders++;scene.updateMatrixWorld();camera.updateMatrixWorld()};if(saved)w.localStorage.setItem('lumenfall-save',JSON.stringify(encode(saved)));
 const dispose=await startGame();
 const flush=async()=>{for(let i=0;i<50;i++)await new Promise(r=>setImmediate(r))};
 const advance=async(ms)=>{const end=now+ms;for(let i=0;i<20000;i++){let id=-1,next=Infinity;for(const [k,v]of jobs)if(v.at<next){id=k;next=v.at}if(next>end)break;now=next;const job=jobs.get(id);jobs.delete(id);job.fn()}now=end;await flush()};
 const button=id=>w.document.querySelector(`[data-action="${id}"]`),click=async id=>{const b=button(id);assert.ok(b,`missing button ${id}: ${w.document.body.textContent.slice(-500)}`);assert.equal(b.disabled,false,`disabled ${id}`);b.click();await flush()};
 const dialogues=async()=>{for(let i=0;i<80&&button('next');i++)await click('next')};
 const read=async()=>{await click('menu');await click('save');await click('close');return decode(w.localStorage.getItem(search.includes('debug=1')?'lumenfall-debug-save':'lumenfall-save'))};
 const go=async id=>{await click('map');await click('walk-'+id);await advance(14000);assert.ok(button('interact'),'cannot reach '+id);await click('interact');await dialogues();await advance(1600)};
 const fight=async()=>{let turn=0,phase=false;for(;turn<110&&button('attack');turn++){const text=w.document.body.textContent;phase ||= /第二段階/.test(text);let cmd='fire';const hpText=w.document.querySelector('.party')?.textContent??'';const match=hpText.match(/HP\s*(\d+)\/(\d+)/);const hp=match?Number(match[1]):999;const hint=w.document.querySelector('.enemy-hint')?.textContent??'';
 if(/今、防御|環海沈降！/.test(hint))cmd='guard';else if(hp<130&&button('potion')&&!button('potion').disabled)cmd='potion';else if(hp<100&&button('heal')&&!button('heal').disabled)cmd='heal';else if(/まで2行動/.test(hint)&&button('route:cycle')&&!button('route:cycle').disabled)cmd='route:cycle';else if(button('route:defense')&&!button('route:defense').disabled)cmd='route:defense';else if(button('fire')?.disabled)cmd=button('ether')&&!button('ether').disabled?'ether':'attack';await click(cmd);await advance(4000)}assert.ok(turn<110,'battle did not end');await dialogues();return turn};
 return {w,button,click,go,fight,advance,dialogues,read,renders:()=>renders,close(){dispose();SoftwareRenderer.prototype.render=originalRender;dom.window.close();for(const [k,d]of original)if(d)Object.defineProperty(globalThis,k,d);else delete globalThis[k]}};
}
test('actual controller UI: C3 old save to complete C4 via walking/dialogue/commands; saves and revisits',async()=>{const h=await harness();try{assert.equal(h.w.document.querySelector('#lumenfall-debug'),null);await h.click('load');await h.dialogues();await h.click('menu');await h.click('chapters');await h.click('chapter:chapter-4');assert.ok(h.button('ring-start'));await h.click('ring-start');await h.dialogues();await h.go('port');await h.go('rau');
 for(const [island,enemies,lamp]of [['west',['biter','jelly'],'west'],['east',['shell','ray'],'east']]){await h.go(island);for(const id of enemies){await h.go(id);await h.fight()}await h.go(lamp);await h.go('port');await h.go('rest')}
 await h.go('ruins');for(const id of ['biter-2','shell-2','seawarden']){await h.go(id);await h.fight()}await h.go('corridor');await h.go('rest');for(const id of ['jelly-2','ray-2']){await h.go(id);await h.fight()}await h.go('cut');await h.go('altar');await h.go('van');await h.go('rest');await h.go('heart');await h.go('ignas');assert.equal(h.w.document.querySelectorAll('[data-action^="route:"]').length,3);await h.fight();await h.dialogues();assert.match(h.w.document.body.textContent,/CHAPTER 4 COMPLETE/);await h.click('after');const s=await h.read();assert.ok(s.campaign.completedChapters.includes('chapter-4'));assert.equal(s.campaign.chapters['chapter-4'].quests['ring-current'],'complete');await h.click('menu');await h.click('load');await h.dialogues();const reread=await h.read();assert.equal(reread.campaign.currentChapter,'chapter-4');for(const id of ['chapter-1','chapter-2','chapter-3']){await h.click('menu');await h.click('chapters');await h.click('chapter:'+id);await h.dialogues()}await h.click('menu');await h.click('trials');await h.dialogues();if(!h.button('trial-start:1')){await h.click('menu');await h.click('trials')}assert.ok(h.button('trial-start:1'),h.w.document.body.textContent);assert.ok(h.renders()>100)}finally{h.close()}});
test('actual controller mobile input: keyboard, pointer auto-walk, joystick release, debug query off',async()=>{const h=await harness(390,'?debug=0');try{await h.click('load');await h.dialogues();await h.click('menu');await h.click('chapters');await h.click('chapter:chapter-4');await h.click('ring-start');await h.dialogues();const before=await h.read();h.w.dispatchEvent(new h.w.KeyboardEvent('keydown',{key:'ArrowUp'}));await h.advance(400);h.w.dispatchEvent(new h.w.KeyboardEvent('keyup',{key:'ArrowUp'}));const after=await h.read();assert.notEqual(before.z,after.z);const joy=h.w.document.querySelector('#joystick');joy.getBoundingClientRect=()=>({left:0,top:0,width:110,height:110});const pointer=(target,type,x,y,buttons)=>{const e=new h.w.MouseEvent(type,{clientX:x,clientY:y,button:0,buttons,bubbles:true});Object.defineProperty(e,'pointerId',{value:1});target.dispatchEvent(e)};pointer(joy,'pointerdown',75,45,1);await h.advance(400);pointer(h.w,'pointerup',75,45,0);const released=await h.read();await h.advance(1500);const stopped=await h.read();assert.equal(stopped.x,released.x);assert.equal(stopped.z,released.z);assert.equal(h.w.document.querySelector('#lumenfall-debug'),null);await h.go('port');assert.match(h.w.document.body.textContent,/無響の港/)}finally{h.close()}});
test('actual controller restores old chapter after map build throws without saving new state',async()=>{const h=await harness();const {default:c4}=await import('../app/chapters/chapter-4/chapter-config.ts');const load=c4.maps[0].load;try{await h.click('load');await h.dialogues();await h.click('menu');await h.click('chapters');const before=h.w.localStorage.getItem('lumenfall-save');c4.maps[0].load=async()=>({build(){throw Error('injected build failure')}});await h.click('chapter:chapter-4');assert.equal(h.w.localStorage.getItem('lumenfall-save'),before);assert.match(h.w.document.body.textContent,/injected build failure/);await h.click('close');assert.match(h.w.document.body.textContent,/白霧の雪原/);c4.maps[0].load=load;await h.click('menu');await h.click('chapters');await h.click('chapter:chapter-4');assert.ok(h.button('ring-start'))}finally{c4.maps[0].load=load;h.close()}});
test('actual controller preserves C3 ending callbacks across city transition and saves C4 unlock',async()=>{const {travel}=await import('../app/debug/debug-actions.ts');const {default:c3}=await import('../app/chapters/chapter-3/chapter-config.ts');const s=await travel(completed3(),'chapter-3',undefined,'Before Aurel');const hp=c3.enemies.aurel.hp;c3.enemies.aurel.hp=1;const h=await harness(1280,'',s);try{await h.click('load');await h.dialogues();await h.go('aurel');await h.click('attack');await h.advance(4000);await h.dialogues();assert.match(h.w.document.body.textContent,/CHAPTER 3 COMPLETE/);const saved=decode(h.w.localStorage.getItem('lumenfall-save'));assert.equal(saved.campaign.chapters['chapter-3'].flags.endingComplete,true);assert.ok(saved.campaign.unlockedChapters.includes('chapter-4'))}finally{c3.enemies.aurel.hp=hp;h.close()}});
test('actual controller new game is unchanged; C4 remains locked',async()=>{const h=await harness(390,'',null);try{await h.click('new');await h.dialogues();const s=await h.read();assert.equal(s.campaign.currentChapter,'chapter-1');assert.equal(s.lv,1);await h.click('menu');await h.click('chapters');assert.equal(h.button('chapter:chapter-4').disabled,true)}finally{h.close()}});
test('actual mobile battle UI consumes switch turn, enforces cooldown, defeat returns safely and retries',async()=>{const {travel}=await import('../app/debug/debug-actions.ts');const s=await travel(completed3(),'chapter-4',undefined,'Before Ignas');s.hp=1;const h=await harness(390,'?debug=0',s);try{await h.click('load');await h.dialogues();await h.go('ignas');assert.equal(h.w.document.querySelectorAll('[data-action^="route:"]').length,3);await h.click('route:cycle');assert.equal(h.button('route:cycle').disabled,true);await h.advance(4000);await h.dialogues();assert.match(h.w.document.body.textContent,/無響の港/);const after=await h.read();assert.equal(after.hp,340);assert.equal(after.campaign.chapters['chapter-4'].bosses.includes('ignas'),false);await h.go('ruins');await h.go('corridor');await h.go('altar');await h.go('heart');await h.go('ignas');assert.ok(h.button('attack'));assert.equal(h.button('route:cycle').disabled,false)}finally{h.close()}});
test('actual shop and gear UI preserve two accessories and save selected equipment',async()=>{const {travel}=await import('../app/debug/debug-actions.ts');const s=await travel(completed3(),'chapter-4',1);s.trials.owned=['warden','afterglow'];s.trials.slots=['warden','afterglow'];const h=await harness(390,'',s);try{await h.click('load');await h.dialogues();await h.go('shop');await h.click('ring-buy:ring-sword');await h.click('ring-buy:ring-cloak');await h.click('close');const saved=await h.read();assert.equal(saved.gear.weapon,'ring-sword');assert.equal(saved.gear.armor,'ring-cloak');assert.deepEqual(saved.trials.slots,['warden','afterglow']);await h.click('menu');await h.click('gear-menu');assert.ok(h.button('gear:ring-sword'));await h.click('close');await h.click('menu');await h.click('equipment');assert.match(h.w.document.body.textContent,/灯守の指輪/)}finally{h.close()}});
test('actual controller same-chapter map build failure keeps position, progress, save and permits retry',async()=>{const {travel}=await import('../app/debug/debug-actions.ts');const {default:c4}=await import('../app/chapters/chapter-4/chapter-config.ts');const s=await travel(completed3(),'chapter-4');const h=await harness(390,'',s),load=c4.maps[1].load;try{await h.click('load');await h.dialogues();const before=h.w.localStorage.getItem('lumenfall-save');c4.maps[1].load=async()=>({build(){throw Error('map build')}});await h.go('port');assert.match(h.w.document.body.textContent,/環海入口/);assert.equal(h.w.localStorage.getItem('lumenfall-save'),before);c4.maps[1].load=load;await h.go('port');assert.match(h.w.document.body.textContent,/無響の港/)}finally{c4.maps[1].load=load;h.close()}});
