import * as T from 'three';
import type {ChapterContext} from '../../types.ts';
import {floors} from '../terrain.ts';
import {flags} from '../state.ts';
import {place} from '../object-config.ts';
export function palette(c:ChapterContext){return c.world.userData.palette??=( {stone:c.mat('#708b90',.83),edge:c.mat('#304c58'),dark:c.mat('#142e3a'),sand:c.mat('#a4af9b'),wood:c.mat('#42535a'),gold:c.mat('#baad7e'),green:c.mat('#365d58'),glow:new T.MeshStandardMaterial({color:'#c4f5e5',emissive:'#7fe7ce',emissiveIntensity:1.6,roughness:.35}),warm:new T.MeshStandardMaterial({color:'#f7dfac',emissive:'#edbf70',emissiveIntensity:1.5,roughness:.4})})}
export function foundation(c:ChapterContext){const m=palette(c),deep=c.state.area===5,restored=!!flags(c.state).restored;
 c.scene.background=new T.Color(deep?'#061b25':restored?'#304c59':'#142e43');c.scene.fog=new T.FogExp2(deep?'#12313d':'#2a4b60',deep?.023:.012);c.ambient.color.set('#b9dfeb');c.ambient.groundColor.set('#163440');c.ambient.intensity=deep?1.5:1.85;c.sun.color.set(restored?'#f6e1aa':'#b3d9e9');c.sun.intensity=deep?1.7:2.65;c.sun.position.set(-16,25,-14);c.scene.userData.fillLift=1.08;
 // One opaque animated sea; no reflection pass, no transparency stack or CPU vertex updates.
 const sea=new T.MeshStandardMaterial({color:'#0e3543',metalness:.42,roughness:.42,emissive:'#07252f',emissiveIntensity:.23});sea.onBeforeCompile=shader=>{shader.uniforms.uClock=c.animationTime;shader.vertexShader='uniform float uClock;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <beginnormal_vertex>','#include <beginnormal_vertex>\nfloat w=.028*cos(position.x*.7+position.y*.4+uClock*.4);objectNormal=normalize(vec3(-w,-w*.6,1.));').replace('#include <begin_vertex>','#include <begin_vertex>\ntransformed.z+=.04*sin(position.x*.7+position.y*.4+uClock*.4);')};const water=new T.Mesh(new T.PlaneGeometry(100,100,16,16),sea);water.rotation.x=-Math.PI/2;water.position.y=-.65;water.receiveShadow=true;c.world.add(water);
 for(const r of floors[c.state.area])for(let i=0;i<Math.ceil(r.d/2);i++){const depth=r.d/Math.ceil(r.d/2),z=r.z-r.d/2+(i+.5)*depth,y=c.height(r.x,z);c.box(r.x,y-.55,z,r.w,1.05,depth+.04,m.edge);c.box(r.x,y,z,r.w,.08,depth+.03,c.state.area===2?m.sand:m.stone);if(i%2===0)c.box(r.x,y+.046,z,r.w,.012,.035,m.gold,false)}
 // Distant ring islands establish scale without traversable oversized maps.
 if(!deep)for(let i=0;i<9;i++){const a=i*Math.PI*2/9;const x=Math.cos(a)*37,z=Math.sin(a)*37;c.cyl(x,-.9,z,3.6,1.5,m.dark,7);c.cyl(x,.6,z,.55,3+(i%3),m.edge,6)}
 for(let z=-14;z<=14;z+=7)c.box(0,c.height(0,z)+.065,z,.1,.04,3.8,m.glow,false);
 return m;
}
export function ring(c:ChapterContext,x:number,y:number,z:number,r:number,material:T.Material,vertical=false){const mesh=new T.Mesh(new T.TorusGeometry(r,.085,6,48),material);mesh.position.set(x,y,z);if(!vertical)mesh.rotation.x=-Math.PI/2;mesh.castShadow=true;c.world.add(mesh);return mesh}
export function pillar(c:ChapterContext,x:number,z:number,h=5){const m=palette(c),y=c.height(x,z);c.cyl(x,y+.15,z,.75,.3,m.gold);c.cyl(x,y+h/2,z,.36,h,m.stone,6);c.cyl(x,y+h,z,.6,.2,m.gold);c.box(x,y+h-.7,z,.12,.8,.77,m.glow,false);c.blocks.push({x,z,w:1.2,d:1.2})}
export function lamp(c:ChapterContext,x:number,z:number,warm=false){const m=palette(c),y=c.height(x,z);c.cyl(x,y+.75,z,.09,1.5,m.dark);c.box(x,y+1.5,z,.35,.5,.35,warm?m.warm:m.glow,false);c.box(x,y+1.8,z,.6,.08,.6,m.gold);c.light(x,y+1.6,z,warm?'#f6cc8d':'#90e7e1',5)}
export function house(c:ChapterContext,x:number,z:number){const m=palette(c),y=c.height(x,z);c.box(x,y+1.65,z,4,3.3,3.8,m.edge);c.box(x,y+3.4,z,4.6,.25,4.2,m.dark);c.box(x,y+.8,z+1.95,.9,1.6,.12,m.wood);for(const dx of [-1.25,1.25])c.box(x+dx,y+1.7,z+1.93,.65,.9,.06,m.warm,false);c.box(x,y+2.9,z+2,4,.13,.1,m.gold);c.blocks.push({x,z,w:4.2,d:4});lamp(c,x+2.8,z+2,true)}
export function beacon(c:ChapterContext,x:number,z:number,lit:boolean){const m=palette(c),y=c.height(x,z);c.cyl(x,y+.2,z,1.5,.4,m.edge);ring(c,x,y+.5,z,1.15,m.gold);const glow=new T.MeshStandardMaterial({color:lit?'#e1ffe5':'#376773',emissive:'#74e2cd',emissiveIntensity:lit?2.5:.2,roughness:.2});c.cyl(x,y+1.5,z,.35,2.7,glow,6);c.light(x,y+2,z,'#a0f5df',lit?9:2);if(lit){ring(c,x,y+.6,z,2.2,m.glow);for(let i=0;i<5;i++)c.box(x-2-i*1.2,-.55,z-i*.6,.7,.05,.1,m.glow,false)}}
export function trees(c:ChapterContext){const m=palette(c);for(let i=0;i<8;i++){const x=i%2?-7:7,z=14-i*3.5;c.cyl(x,1,z,.13,2,m.wood);for(let j=0;j<3;j++){const a=c.box(x+Math.cos(j*2)*.7,2.2,z+Math.sin(j*2)*.7,1.8,.18,.7,m.green);a.rotation.z=.2;a.rotation.y=j*2}c.blocks.push({x,z,w:.4,d:.4})}}
export function finish(c:ChapterContext){place(c)}
