import type {ChapterContext} from '../types.ts';
import {flags,won} from './state.ts';
export type Placement={id:string;kind:string;name:string;x:number;z:number;sprite?:string;scale?:number;destination?:number};
export const placements:Record<number,Placement[]>={
 0:[{id:'keeper',kind:'npc',name:'港守のイサ',x:-3,z:11,sprite:'keeper'},{id:'bell',kind:'npc',name:'鐘番のトワ',x:-12,z:4,sprite:'towa'},{id:'boat',kind:'npc',name:'船大工のロウ',x:12,z:3,sprite:'shipwright'},{id:'star',kind:'npc',name:'星図師のエル',x:6,z:-4,sprite:'stargazer'},{id:'supply',kind:'shop',name:'港の旅支度',x:13,z:12,sprite:'shipwright'},{id:'inn',kind:'inn',name:'宿屋「帰り灯」',x:-12,z:13,sprite:'towa'},{id:'coast',kind:'exit',name:'残灯の桟橋へ',x:0,z:-17,destination:1},{id:'home',kind:'previous',name:'リュネへ戻る',x:-5,z:17}],
 1:[{id:'harbor',kind:'exit',name:'セレインへ戻る',x:0,z:19,destination:0},{id:'shell',kind:'enemy',name:'潮殻ヤドリ',x:-10,z:7,sprite:'shell',scale:2.4},{id:'bell-beacon',kind:'beacon',name:'鐘の航路灯',x:-13,z:1},{id:'jelly',kind:'enemy',name:'霧縫いクラゲ',x:10,z:0,sprite:'jelly',scale:2.7},{id:'boat-beacon',kind:'beacon',name:'舟の航路灯',x:12,z:-6},{id:'moth',kind:'enemy',name:'灯喰い蛾',x:4,z:-9,sprite:'moth',scale:2.6},{id:'star-beacon',kind:'beacon',name:'星の航路灯',x:-2,z:-9},{id:'chapel',kind:'exit',name:'潮葬の礼拝堂へ',x:0,z:-19,destination:2}],
 2:[{id:'coast',kind:'exit',name:'桟橋へ戻る',x:0,z:19,destination:1},{id:'inscription',kind:'lore',name:'潮に濡れた碑文',x:2,z:12},{id:'jelly-nave',kind:'enemy',name:'深潮のクラゲ',x:-11,z:1,sprite:'jelly',scale:2.7},{id:'nave-west',kind:'lamp',name:'西の祈り灯',x:-11,z:-6},{id:'moth-nave',kind:'enemy',name:'残響の灯喰い蛾',x:11,z:1,sprite:'moth',scale:2.6},{id:'nave-east',kind:'lamp',name:'東の祈り灯',x:11,z:-6},{id:'survivor',kind:'npc',name:'霧の中の少年',x:-9,z:6,sprite:'boy'},{id:'bellwarden',kind:'boss',name:'沈鐘の衛士 ボルン',x:0,z:-15,sprite:'bellwarden',scale:4.4},{id:'choir',kind:'exit',name:'無灯の聖歌廊へ',x:0,z:-19,destination:3}],
 3:[{id:'chapel',kind:'exit',name:'礼拝堂へ戻る',x:0,z:19,destination:2},{id:'rest-light',kind:'spring',name:'旅人の灯溜まり',x:0,z:10},{id:'vigil-west',kind:'lamp',name:'西の帰り灯',x:-12,z:0},{id:'vigil-east',kind:'lamp',name:'東の帰り灯',x:12,z:0},{id:'vigil-heart',kind:'lamp',name:'中央の帰り灯',x:0,z:-7},{id:'nereis',kind:'boss',name:'無灯の聖歌 ネレイス',x:0,z:-15,sprite:'nereis',scale:5.4}],
};
export const treasures:Record<string,{area:number;x:number;z:number;gold:number;potions:number;ethers:number}>={
 harbor:{area:0,x:16,z:17,gold:30,potions:2,ethers:1},tools:{area:1,x:-13,z:-3,gold:20,potions:1,ethers:2},nave:{area:2,x:11,z:-10,gold:35,potions:2,ethers:2},choir:{area:3,x:-12,z:-5,gold:50,potions:2,ethers:2},
};
export const guardians:Record<string,string>={'bell-beacon':'shell','boat-beacon':'jelly','star-beacon':'moth','nave-west':'jelly-nave','nave-east':'moth-nave'};
export function place(ctx:ChapterContext){for(const p of placements[ctx.state.area]){if((p.kind==='enemy'||p.kind==='boss')&&won(ctx.state,p.id))continue;if(p.id==='survivor'&&flags(ctx.state).rescued)continue;const o=ctx.addObj(p.kind,p.name,p.x,p.z,p.id);if(p.sprite)o.mesh=ctx.sprite(p.sprite,p.x,p.z,p.scale)}for(const [id,t]of Object.entries(treasures)){if(t.area===ctx.state.area)ctx.chest(t.x,t.z,id)}}
