import type {ChapterContext} from '../types.ts';
import {won} from './state.ts';
export type Placement={id:string;kind:string;name:string;x:number;z:number;sprite?:string;scale?:number;destination?:number};
export const placements:Record<number,Placement[]>={
 0:[{id:'harbor',kind:'previous',name:'霧港へ戻る',x:-4,z:17},{id:'traveler',kind:'npc',name:'運び屋のセナ',x:3,z:12,sprite:'traveler'},{id:'frost',kind:'enemy',name:'霜喰い',x:-4,z:3,sprite:'frost',scale:2.5},{id:'waylight',kind:'lamp',name:'雪原の道標を灯す',x:2,z:-5},{id:'village',kind:'exit',name:'凍灯の集落へ',x:0,z:-18,destination:1}],
 1:[{id:'snowfield',kind:'exit',name:'白霧の雪原へ',x:0,z:18,destination:0},{id:'elder',kind:'npc',name:'語り部のオル',x:-6,z:6,sprite:'elder'},{id:'watcher',kind:'npc',name:'山番のネム',x:5,z:-5,sprite:'watcher'},{id:'smith',kind:'npc',name:'灯細工のユル',x:7,z:4,sprite:'smith'},{id:'shop',kind:'shop',name:'雪旅の支度',x:11,z:10,sprite:'smith'},{id:'rest',kind:'spring',name:'集落の暖炉で休む',x:-7,z:10},{id:'warden',kind:'boss',name:'凍れる番人',x:0,z:-10,sprite:'warden',scale:4.6},{id:'city',kind:'exit',name:'凍れる旧都へ',x:0,z:-18,destination:2}],
 2:[{id:'village',kind:'exit',name:'集落へ戻る',x:0,z:18,destination:1},{id:'soldier',kind:'enemy',name:'凍灯兵',x:-13,z:2,sprite:'soldier',scale:2.8},{id:'shade',kind:'enemy',name:'白霧の亡影',x:13,z:-2,sprite:'shade',scale:3},{id:'memory',kind:'lore',name:'消灯装置の痕跡',x:-13,z:-9},{id:'cathedral',kind:'exit',name:'観測塔の地下・凍灯聖堂へ',x:0,z:-18,destination:3}],
 3:[{id:'city',kind:'exit',name:'旧都へ戻る',x:0,z:18,destination:2},{id:'shelter',kind:'spring',name:'聖堂の保温灯で休む',x:3,z:12},{id:'record',kind:'lore',name:'封印の記録',x:0,z:5},{id:'hunter',kind:'enemy',name:'灯狩り',x:-13,z:1,sprite:'hunter',scale:3.3},{id:'hearth-west',kind:'lamp',name:'西の保温灯',x:-13,z:-7},{id:'hearth-east',kind:'lamp',name:'東の保温灯',x:13,z:-7},{id:'furnace',kind:'exit',name:'大灯の炉心へ',x:0,z:-18,destination:4}],
 4:[{id:'cathedral',kind:'exit',name:'聖堂へ戻る',x:0,z:18,destination:3},{id:'rest',kind:'spring',name:'分かち火で休む',x:3,z:11},{id:'aurel',kind:'boss',name:'氷葬の灯守 アウレル',x:0,z:-3.8,sprite:'aurel',scale:5.5},{id:'echo',kind:'ending',name:'氷葬の灯守に話す',x:0,z:-3.8,sprite:'aurel',scale:4.3}]
};
export const treasures:Record<string,{area:number;x:number;z:number;gold:number;potions:number;ethers:number}>={snow:{area:0,x:10,z:-7,gold:40,potions:2,ethers:2},village:{area:1,x:13,z:-8,gold:50,potions:2,ethers:2},archive:{area:2,x:13,z:-10,gold:65,potions:2,ethers:3},sanctuary:{area:3,x:13,z:3,gold:70,potions:3,ethers:3}};
export function place(c:ChapterContext){for(const p of placements[c.state.area]){if((p.kind==='enemy'||p.kind==='boss')&&won(c.state,p.id))continue;if(p.kind==='ending'&&!won(c.state,'aurel'))continue;const o=c.addObj(p.kind,p.name,p.x,p.z,p.id);if(p.id==='aurel'||p.id==='echo')o.r=3.4;if(p.sprite)o.mesh=c.sprite(p.sprite,p.x,p.z,p.scale)}for(const [id,t]of Object.entries(treasures))if(t.area===c.state.area)c.chest(t.x,t.z,id)}
