import type {ChapterContext,WorldObject} from '../types.ts';
import {maps} from './map-config.ts';
import {goal} from './events.ts';
import {flags,canEnter} from './state.ts';
import {placements} from './object-config.ts';
export function hud(c:ChapterContext){const m=maps[c.state.area],g=goal(c);return `<div class=top><div class=region><small>${m.eyebrow}</small><h2>${m.name}</h2><p>${m.description}</p></div><div class=tools><button class=iconbtn data-action=sound aria-label=音の切り替え>♪</button><button class=iconbtn data-action=map aria-label=周辺の案内>⌖</button><button class=iconbtn data-action=menu aria-label=冒険メニュー>☰</button></div></div><div class=quest><small>CHAPTER 4 · 無音の環海</small><div class=journey>港 › 二つの環灯 › 灯路 › 中央祭壇</div><span class=quest-copy>${c.progress.completed?'灯がつながっても、海は昔と同じではない。':'地図の南西。途切れた第四の灯を追う。'}</span>${g?`<button class=guide data-action=guide>⌖ ${g.name}</button>`:''}<button class="guide chapter-notebook" data-action=ring-notes>環海の航路帳</button></div>`}
export function modalUI(c:ChapterContext){const b=c.btn,s=c.state,f=flags(s);let h='';if(c.modal==='chapter4-title')h=`<div class=eyebrow>THE FOURTH LIGHT</div><h1>Chapter 4</h1><h2>無音の環海</h2><p>雪の旧都の地図に、黒く染まった南西の灯。<br>音の遠い海へ、リオとミナは向かう。</p>${b('ring-start','環海へ渡る')}`;
 if(c.modal==='ring-notes')h=`<h2>環海の航路帳</h2><p>港守ラウ → 西・東の島（順不同） → 環状遺跡 → 沈灯回廊 → 祭壇。<br>環灯の周りの二体を鎮めて、灯を復旧しよう。<br>宿・分かち火は無料で全回復。</p><p>西の灯：${f.west?'点灯':'未復旧'} ／ 東の灯：${f.east?'点灯':'未復旧'}<br>航路標：${['mark-west','mark-east','mark-ring'].filter(k=>f[k]).length}/3<br>石板：${f.tablet?'回収済み':'未回収'}</p><p>海守：白い灯が無響圧の合図。防御で備える。<br>イグナス：三灯のどれかを切り替えで停止。同じ灯の連続停止は不可。環海沈降の前に循環灯を止めるか、防御でしのぐ。<br>切り替えも1ターン。第二段階は再使用まで2行動。</p>${b('close','閉じる')}`;
 if(c.modal==='shop')h=`<h2>環海の船具店</h2><p>所持金 ${s.gold} G</p>${b('buy-potion','薬草 15 G ／ HP +65',s.gold<15)}${b('buy-ether','星の雫 20 G ／ MP +20',s.gold<20)}${b('ring-buy:ring-sword','環潮の剣 140 G ／ 攻撃 +11',s.gold<140||s.gear?.owned.includes('ring-sword'))}${b('ring-buy:ring-cloak','環海の外套 120 G ／ 被ダメージ −6',s.gold<120||s.gear?.owned.includes('ring-cloak'))}${b('close','店を出る')}`;
 return h?`<div class=overlay><div class="panel winter-panel">${h}</div></div>`:''}
export function endingUI(c:ChapterContext){return `<div class=overlay><div class="panel ending"><div class=eyebrow>THE LIGHTS ARE CONNECTED</div><h1>無音の環海</h1><div class=sep></div><p>船鐘が、静かな海を渡る。<br>帰ってきた灯。変わってしまった潮。<br>灯路の先に、まだ知らない答えがある。</p><div class=badge>CHAPTER 4 COMPLETE</div><p>到達レベル ${c.state.lv} · 宝箱 ${c.progress.chests.length}/6</p>${c.btn('after','航路の戻った港へ')}</div></div>`}
export function visible(c:ChapterContext,o:WorldObject){const p=placements[c.state.area].find(p=>p.id===o.id);return o.kind!=='exit'||p?.destination!==undefined&&canEnter(c.state,p.destination)}
