import * as T from 'three';
import {AdaptiveQuality,pixelRatio,batchStatic,waterProfile} from './performance';
import {bindJoystick} from './input';
import {SoftwareRenderer} from './software';
import {fresh} from './systems/state';
import {progress,unlockArea,recordVictory,completeChapter} from './systems/progression';
import {readSave,writeSave,hasSave} from './systems/save';
import {prepareChapterSwitch} from './systems/chapter-manager';
import {loadChapter,chapterCatalog} from './chapters/registry';
import type {Chapter,ChapterContext,WorldObject as Obj} from './chapters/types';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';
import {UnrealBloomPass} from 'three/addons/postprocessing/UnrealBloomPass.js';
import {ShaderPass} from 'three/addons/postprocessing/ShaderPass.js';
import {Reflector} from 'three/addons/objects/Reflector.js';

export async function startGame(){
 let initial=fresh();try{initial=readSave(localStorage)}catch{}
 let chapter=await loadChapter(initial.campaign.currentChapter).catch(()=>loadChapter('chapter-1'));
 if(chapter.id!==initial.campaign.currentChapter)initial=fresh();
 chapter.initialize(initial);chapter.normalize(initial);
 let loadedMap=await chapter.maps.find(m=>m.id===initial.area)!.load();
 const map=()=>chapter.maps.find(m=>m.id===s.area)!;
 const cp=()=>progress(s.campaign);
 let canvas=document.getElementById('world') as HTMLCanvasElement;const ui=document.getElementById('ui')!,fade=document.getElementById('fade')!;
 let renderer:any,software=false;try{renderer=new T.WebGLRenderer({canvas,antialias:false,powerPreference:'high-performance'});}catch{software=true;const replacement=canvas.cloneNode() as HTMLCanvasElement;canvas.replaceWith(replacement);canvas=replacement;renderer=new SoftwareRenderer(canvas)}
 const mobileDevice=(matchMedia('(pointer:coarse)').matches||innerWidth<=600);const adaptive=new AdaptiveQuality();let quality='auto';try{quality=localStorage.getItem('lumenfall-quality')||'auto'}catch{};const timeUniform={value:0},waterTimeUniform={value:0};let waterFrame=0;let reflections:Reflector[]=[];
 renderer.setPixelRatio(software?1:pixelRatio(innerWidth,innerHeight,devicePixelRatio,mobileDevice));renderer.shadowMap.enabled=true;renderer.shadowMap.autoUpdate=false;renderer.shadowMap.type=mobileDevice?T.PCFShadowMap:T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.18;
 const scene=new T.Scene(),camera=new T.PerspectiveCamera(36,1,.1,180);scene.background=new T.Color('#758c98');scene.fog=new T.FogExp2('#8d9b9b',.021);
 const composer:any=software?{addPass:()=>{},setSize:()=>{},dispose:()=>{},render:()=>renderer.render(scene,camera)}:new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));const bloom=new UnrealBloomPass(new T.Vector2(800,600),.65,.5,.82);composer.addPass(bloom);
 const tilt=new ShaderPass({uniforms:{tDiffuse:{value:null},resolution:{value:new T.Vector2(800,600)},strength:{value:1.7}},vertexShader:'varying vec2 vUv; void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:`uniform sampler2D tDiffuse;uniform vec2 resolution;uniform float strength;varying vec2 vUv;void main(){float f=smoothstep(.13,.47,abs(vUv.y-.49));vec2 d=vec2(1.)/resolution*f*strength*2.;vec4 c=texture2D(tDiffuse,vUv)*.24;c+=texture2D(tDiffuse,vUv+d)*.12;c+=texture2D(tDiffuse,vUv-d)*.12;c+=texture2D(tDiffuse,vUv+vec2(d.x,-d.y))*.12;c+=texture2D(tDiffuse,vUv+vec2(-d.x,d.y))*.12;c+=texture2D(tDiffuse,vUv+vec2(0.,d.y*2.))*.07;c+=texture2D(tDiffuse,vUv-vec2(0.,d.y*2.))*.07;c+=texture2D(tDiffuse,vUv+vec2(d.x*2.,0.))*.07;c+=texture2D(tDiffuse,vUv-vec2(d.x*2.,0.))*.07;float vig=1.-.32*pow(length((vUv-.5)*1.4),1.5);gl_FragColor=vec4(c.rgb*vig,1.);}`});composer.addPass(tilt);
 const ambient=new T.HemisphereLight('#c3e1ef','#384538',2);scene.add(ambient);const sun=new T.DirectionalLight('#ffcf85',4);sun.position.set(-14,25,9);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-30,right:30,top:30,bottom:-30,near:1,far:90});sun.shadow.bias=-.0007;sun.shadow.normalBias=.035;scene.add(sun);const flash=new T.PointLight('#85dbff',0,35,1);flash.position.set(0,5,0);scene.add(flash);
 let world=new T.Group();scene.add(world);let hero:T.Sprite,companion:T.Sprite,enemySprite:T.Sprite|undefined;let objects:Obj[]=[],blocks:{x:number,z:number,w:number,d:number}[]=[],waters:T.Mesh[]=[],flames:T.Sprite[]=[],grass:T.Mesh[]=[],particles:T.Points;let mode='title',modal='',dialogues:string[]=[],speaker='',afterDialogue:(()=>void)|undefined;let releaseJoystick:(()=>void)|undefined;let s=initial,keys=new Set<string>(),joy={x:0,y:0},target:T.Vector3|null=null,route:T.Vector3[]=[],near:Obj|undefined,clock=0,last=performance.now(),raf=0,dead=false,toast='',toastUntil=0,shake=0,hitstop=0,battle:any=null,busy=false,battleLog='',fx:T.Points[]=[];let audio:AudioContext|undefined,muted=false,nextNote=0;let camLook=new T.Vector3(),camPos=new T.Vector3(),anim=0;const followPosition=new T.Vector3(),lookPosition=new T.Vector3();let lastFrameAt=0,lastShadow=-1,lastLight=-1,lastAmbient=-1,frameSum=0,frameCount=0,statsAt=0,fps=0,uiMarkup='',uiDirty=false;const geometryResources=new Set<T.BufferGeometry>(),materialResources=new Set<T.Material>(),textureResources=new Set<T.Texture>();const localLights:{position:T.Vector3,color:T.Color,power:number}[]=[];const lightPool=Array.from({length:mobileDevice?4:6},()=>{const l=new T.PointLight('#ffd087',0,8,2);scene.add(l);return l});const timers=new Set<ReturnType<typeof setTimeout>>();const later=(f:()=>void,t:number)=>{const id=setTimeout(()=>{timers.delete(id);if(!dead)f()},t);timers.add(id)};
 const maxHP=()=>100+(s.lv-1)*24,maxMP=()=>30+(s.lv-1)*8;
 const rand=(n:number)=>{const x=Math.sin(n*127.1+311.7)*43758.5453;return x-Math.floor(x)};
 const mat=(color:string,roughness=.9)=>new T.MeshStandardMaterial({color,roughness});
 const mats={stone:mat('#8b9186'),dark:mat('#505d58'),wall:mat('#ddcba6'),wood:mat('#665044'),roof:mat('#487573'),gold:mat('#b38a45'),ground:mat('#647b46'),path:mat('#b4a17a')};
 function box(x:number,y:number,z:number,w:number,h:number,d:number,m:T.Material,cast=true){const a=new T.Mesh(new T.BoxGeometry(w,h,d,software?Math.ceil(w/3):1,1,software?Math.ceil(d/3):1),m);a.position.set(x,y,z);a.castShadow=cast;a.receiveShadow=true;world.add(a);return a}
 function cyl(x:number,y:number,z:number,r:number,h:number,m:T.Material,n=8){const a=new T.Mesh(new T.CylinderGeometry(r,r*1.08,h,n),m);a.position.set(x,y,z);a.castShadow=true;a.receiveShadow=true;world.add(a);return a}
 function texture(kind:string){const c=document.createElement('canvas');c.width=48;c.height=64;const g=c.getContext('2d')!;const rect=(x:number,y:number,w:number,h:number,col:string)=>{g.fillStyle=col;g.fillRect(x,y,w,h)};
 if(chapter.paintSprite(kind,rect)){} else{const npc=kind!=='hero',blue=kind==='mage',coat=blue?'#d6d4dc':npc?'#89977a':'#355f83';rect(17,8,15,6,npc?'#aaa197':'#4a3535');rect(14,13,20,13,npc?'#cec1a1':'#533b36');rect(18,15,14,14,'#e9b58c');rect(29,18,3,3,'#26313b');rect(14,13,7,11,npc?'#a7a8a7':'#684335');rect(16,29,17,20,coat);rect(12,30,5,16,coat);rect(32,31,5,13,coat);rect(13,44,5,5,'#e9b58c');rect(33,42,4,6,'#e9b58c');rect(17,46,7,11,'#283947');rect(27,46,6,11,'#283947');rect(15,56,9,4,'#302d31');rect(27,55,9,4,'#302d31');rect(17,28,18,5,blue?'#6bb9b4':'#dfa552');rect(10,32,6,20,blue?'#9eafb9':'#bd6d49');rect(19,43,14,3,'#97754a');if(!npc){rect(36,25,3,30,'#c1d5d3');rect(33,45,9,3,'#c3a26d')}if(blue){rect(9,2,26,6,'#c5c5d9');rect(17,0,13,5,'#b2b5ce');rect(37,24,2,34,'#82775d');rect(34,21,8,7,'#96f7ed')}}
 const tx=new T.CanvasTexture(c);tx.magFilter=T.NearestFilter;tx.minFilter=T.NearestFilter;tx.colorSpace=T.SRGBColorSpace;return tx}
 const spriteCache=new Map<string,T.Texture>();function sprite(kind:string,x:number,z:number,scale=2.2){if(!spriteCache.has(kind))spriteCache.set(kind,texture(kind));const sp=new T.Sprite(new T.SpriteMaterial({map:spriteCache.get(kind),color:'#fff4df',alphaTest:.1,depthWrite:true}));sp.scale.set(scale*.75,scale,1);sp.center.set(.5,0);sp.position.set(x,height(x,z)+.06,z);world.add(sp);const sh=new T.Mesh(new T.CircleGeometry(scale*.24,24),new T.MeshBasicMaterial({color:'#071a20',transparent:true,opacity:.3,depthWrite:false}));sh.userData.dynamic=true;sh.rotation.x=-Math.PI/2;sh.position.set(x,height(x,z)+.025,z);world.add(sh);sp.userData.shadow=sh;return sp}
 function height(x:number,z:number){return chapter.height(s,x,z)}
 function light(x:number,y:number,z:number,color='#ffd087',power=8){localLights.push({position:new T.Vector3(x,y,z),color:new T.Color(color),power})}
 function torch(x:number,z:number){const y=height(x,z);cyl(x,y+.8,z,.09,1.6,mats.wood);const c=document.createElement('canvas');c.width=c.height=32;const g=c.getContext('2d')!,gr=g.createRadialGradient(16,16,0,16,16,16);gr.addColorStop(0,'#fff5c6');gr.addColorStop(.23,'#ffc65b');gr.addColorStop(.5,'#ee761aaa');gr.addColorStop(1,'#ff660000');g.fillStyle=gr;g.fillRect(0,0,32,32);const f=new T.Sprite(new T.SpriteMaterial({map:new T.CanvasTexture(c),blending:T.AdditiveBlending,depthWrite:false}));f.position.set(x,y+1.8,z);f.scale.set(.7,1.2,1);world.add(f);flames.push(f);light(x,y+2,z)}
 function tree(x:number,z:number,scale=1){const y=height(x,z);cyl(x,y+1.6*scale,z,.23*scale,3.2*scale,mats.wood);for(let i=0;i<3;i++){const m=mat(map().night?['#234b46','#2c6255','#427b61'][i]:['#466c49','#648347','#839455'][i]);const a=new T.Mesh(new T.ConeGeometry((2-i*.4)*scale,2.5*scale,7),m);a.position.set(x,y+(3+i*1.1)*scale,z);a.rotation.y=rand(x+z)*5;a.castShadow=true;a.receiveShadow=true;world.add(a)}blocks.push({x,z,w:.6*scale,d:.6*scale})}
 function exitMarker(x:number,z:number,label:string){const y=height(x,z);for(const side of [-1,1]){cyl(x+side*2,y+1.7,z,.07,3.4,mats.wood);const banner=box(x+side*2.3,y+2.65,z,.55,1.1,.05,new T.MeshStandardMaterial({color:'#c9a257',emissive:'#775125',emissiveIntensity:.3}));banner.rotation.z=side*.07;torch(x+side*2,z+1)}const c=document.createElement('canvas');c.width=512;c.height=100;const ctx=c.getContext('2d')!;ctx.fillStyle='#0d2631e8';ctx.fillRect(0,0,512,100);ctx.strokeStyle='#e6c47c';ctx.lineWidth=4;ctx.strokeRect(3,3,506,94);ctx.fillStyle='#ffe6a8';ctx.font='32px serif';ctx.textAlign='center';ctx.fillText(label,256,62);const tx=new T.CanvasTexture(c);const sign=new T.Sprite(new T.SpriteMaterial({map:tx,depthWrite:false}));sign.position.set(x,y+3.8,z);sign.scale.set(6.2,1.21,1);world.add(sign);const ring=new T.Mesh(new T.TorusGeometry(1,.045,8,48),new T.MeshStandardMaterial({color:'#ffe1a1',emissive:'#ffc45c',emissiveIntensity:1.8}));ring.rotation.x=-Math.PI/2;ring.position.set(x,y+.12,z);world.add(ring)}
 function nextGoal(){return chapter.goal(ctx)}
 function house(x:number,z:number,w:number,d:number,roof='#467471'){box(x,1.5,z,w,3,d,mats.wall);box(x,.22,z,w+.25,.45,d+.25,mats.stone);for(const dx of [-w/2+.1,w/2-.1])box(x+dx,1.6,z+d/2+.03,.17,2.8,.15,mats.wood);box(x,2.7,z+d/2+.05,w,.16,.13,mats.wood);const rm=mat(roof);for(const side of [-1,1]){const r=box(x+side*w*.25,3.6,z,w*.65,.23,d+.8,rm);r.rotation.z=side*-.58;for(let j=0;j<5;j++){const b=box(x+side*(j+.5)*w/10,4.32-j*.18,z,.07,.08,d+.85,mats.dark);b.rotation.z=side*-.58}}box(x+.6,4,z-.5,.55,1.8,.65,mats.stone);box(x,1,z+d/2+.07,.85,2,.1,mats.wood);for(const dx of [-w*.3,w*.3]){box(x+dx,1.65,z+d/2+.09,.7,.9,.07,new T.MeshStandardMaterial({color:'#ffce81',emissive:'#ffac45',emissiveIntensity:2.2}));box(x+dx,1.65,z+d/2+.15,.06,1,.07,mats.wood);box(x+dx,1.65,z+d/2+.15,.8,.06,.07,mats.wood);light(x+dx,1.8,z+d/2+.5,'#ffd291',4)}blocks.push({x,z,w:w+.3,d:d+.3})}
 function addObj(kind:string,name:string,x:number,z:number,id=kind){const o:Obj={kind,name,x,z,r:2.3,id};objects.push(o);return o}
 function chest(x:number,z:number,id:string){const y=height(x,z),opened=cp().chests.includes(id);const b=box(x,y+.35,z,.8,.6,.65,opened?mats.dark:mats.wood);box(x,y+.63,z,.87,.13,.69,mats.gold);box(x,y+.4,z+.34,.15,.25,.04,mats.gold);const o=addObj('chest',opened?'空の宝箱':'宝箱を開ける',x,z,id);o.mesh=b}
 function water(x:number,z:number,w:number,d:number,level=-.22){
 const profile=waterProfile(w,d);
 if(!software&&profile.reflect){const ref=new Reflector(new T.PlaneGeometry(w,d),{textureWidth:w>3?384:128,textureHeight:w>3?384:128,multisample:0,color:0x648a91,clipBias:.003});ref.rotation.x=-Math.PI/2;ref.position.set(x,level,z);const original=ref.onBeforeRender;let updated=-100;ref.onBeforeRender=function(...args){if(args[2]!==camera||clock-updated<(mode==='battle'?.1:1/15))return;updated=clock;const visible=reflections.map(r=>r.visible);reflections.forEach(r=>{if(r!==ref)r.visible=false});try{original.apply(ref,args)}finally{reflections.forEach((r,i)=>r.visible=visible[i])}};world.add(ref);reflections.push(ref)}
 const wm=new T.MeshStandardMaterial({color:'#4e969c',transparent:true,opacity:software?.7:profile.reflect?.38:.7,metalness:.7,roughness:.24});
 wm.onBeforeCompile=shader=>{shader.uniforms.uTime=waterTimeUniform;shader.vertexShader='uniform float uTime;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <beginnormal_vertex>','#include <beginnormal_vertex>\nfloat slope=.025*cos(position.x*3.+uTime*1.6+position.y);objectNormal=normalize(vec3(-3.*slope,-slope,1.));').replace('#include <begin_vertex>','#include <begin_vertex>\ntransformed.z+=sin(position.x*3.+uTime*1.6+position.y)*.025;')};
 const mesh=new T.Mesh(new T.PlaneGeometry(w,d,software?1:profile.segmentsX,software?1:profile.segmentsY),wm);mesh.rotation.x=-Math.PI/2;mesh.position.set(x,level+.06,z);mesh.userData.dynamic=true;world.add(mesh);waters.push(mesh)}
 function collectResources(){world.traverse(o=>{if(o instanceof T.Mesh||o instanceof T.Points||o instanceof T.Sprite){if('geometry' in o)geometryResources.add(o.geometry);const ms=Array.isArray(o.material)?o.material:[o.material];for(const m of ms){if(!Object.values(mats).includes(m))materialResources.add(m);const tx=(m as T.SpriteMaterial).map;if(tx&&![...spriteCache.values()].includes(tx))textureResources.add(tx)}}})}
 function disposeWorld(){reflections.forEach(r=>r.dispose());geometryResources.forEach(g=>g.dispose());materialResources.forEach(m=>m.dispose());textureResources.forEach(t=>t.dispose());geometryResources.clear();materialResources.clear();textureResources.clear();scene.remove(world);world=new T.Group();scene.add(world);objects=[];blocks=[];waters=[];flames=[];grass=[];fx=[];reflections=[];localLights.length=0}
 function build(){collectResources();disposeWorld();lastShadow=lastLight=-100;const night=map().night;loadedMap.build(ctx);
 // Tufts and wildflowers sit within the same lighting as the miniature architecture.
 const bladeMat=new T.MeshStandardMaterial({color:night?'#4c8770':'#a1b26b',side:T.DoubleSide});const bladeGeo=new T.PlaneGeometry(.1,.42);bladeMat.userData.kind='grass';bladeMat.onBeforeCompile=shader=>{shader.uniforms.uTime=timeUniform;shader.vertexShader='uniform float uTime;\nattribute float windWeight;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\ntransformed.x+=sin(uTime*2.+position.x)*windWeight*.12;')};bladeGeo.setAttribute('windWeight',new T.Float32BufferAttribute([1,1,0,0],1));for(let i=0;i<(software?180:mobileDevice?420:650);i++){const x=rand(i+1000)*44-22,z=rand(i+2000)*44-22;if(!chapter.vegetation(s,x,z))continue;const a=new T.Mesh(bladeGeo,bladeMat);a.position.set(x,height(x,z)+.17,z);a.rotation.y=i;world.add(a);if(software&&i%4===0){grass.push(a);a.userData.dynamic=true}if(i%8===0)box(x,height(x,z)+.35,z,.09,.09,.09,new T.MeshStandardMaterial({color:night?'#7fdfdd':'#ffe4ac',emissive:night?'#53a8a8':'#5a471c',emissiveIntensity:night?1:.1}),false)}
 const ambientCount=mobileDevice?80:120;const pos=new Float32Array(ambientCount*3);for(let i=0;i<ambientCount;i++){pos[i*3]=rand(i+58)*42-21;pos[i*3+1]=rand(i+922)*7+.4;pos[i*3+2]=rand(i+88)*42-21}const pg=new T.BufferGeometry();pg.setAttribute('position',new T.BufferAttribute(pos,3));particles=new T.Points(pg,new T.PointsMaterial({color:night?'#adfff0':'#ffe0a0',size:.065,transparent:true,opacity:.75,blending:T.AdditiveBlending,depthWrite:false}));(particles.material as T.PointsMaterial).onBeforeCompile=shader=>{shader.uniforms.uTime=timeUniform;shader.vertexShader='uniform float uTime;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\ntransformed.y=mod(position.y+uTime*.13,8.);transformed.x+=sin(uTime*.3+position.y)*.3;')};world.add(particles);
 hero=sprite('hero',s.x,s.z,2.2);companion=sprite('mage',s.x+1,s.z+1,2.1);companion.visible=chapter.hasCompanion(s);camLook.set(s.x,1,s.z);camPos.set(s.x+15,21,s.z+24);camera.position.copy(camPos);camera.lookAt(camLook);collectResources();{const batches=batchStatic(world);scene.userData.batches=batches}collectResources();renderer.shadowMap.needsUpdate=true;uiDirty=true;renderUI()}
 function save(manual=false){try{cp().position={area:s.area,x:s.x,z:s.z};writeSave(localStorage,s);if(manual)notify('冒険を記録しました')}catch{notify('保存できません。ブラウザの保存設定をご確認ください')}}
 async function load(){if(mode==='loading')return;try{const next=readSave(localStorage);await activate(next,false);save();notify('記録した冒険を再開しました')}catch(e){notify(e instanceof Error?e.message:'読み込める記録がありません')}}
 function notify(t:string){toast=t;toastUntil=clock+3;renderUI()}
 function talk(name:string,lines:string[],cb?:()=>void){speaker=name;dialogues=[...lines];afterDialogue=cb;modal='dialogue';target=null;renderUI()}
 function next(){if(modal!=='dialogue')return;dialogues.shift();if(!dialogues.length){modal='';const cb=afterDialogue;afterDialogue=undefined;cb?.()}renderUI()}
 async function newGame(){if(mode==='loading')return;await activate(fresh(),true);chapter.begin(ctx)}
 async function transition(area:number){if(mode==='loading')return;const from=s.area;await changeMap(area,chapter.entry(area,from));chapter.enter(ctx,from);save();notify(map().name)}
 function interact(o=near){if(!o||modal||mode!=='explore')return;target=null;route=[];tone(523,.08);chapter.interact(ctx,o)}
 function tone(freq:number,duration=.2,type:OscillatorType='sine',vol=.045){if(muted||!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(vol,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+duration)}
 function activateAudio(){if(!audio){audio=new AudioContext()}if(audio.state==='suspended')audio.resume()}
 function burst(x:number,y:number,z:number,color:string,count=100){count=Math.ceil(count*(software?.35:mobileDevice?.7:1));const p=new Float32Array(count*3),v=[];for(let i=0;i<count;i++){p[i*3]=x;p[i*3+1]=y;p[i*3+2]=z;v.push(new T.Vector3((Math.random()-.5)*10,Math.random()*7,(Math.random()-.5)*10))}const g=new T.BufferGeometry();g.setAttribute('position',new T.BufferAttribute(p,3));const f=new T.Points(g,new T.PointsMaterial({color,size:.12,blending:T.AdditiveBlending,transparent:true,depthWrite:false}));g.setAttribute('velocity',new T.Float32BufferAttribute(v.flatMap(a=>[a.x,a.y,a.z]),3));const age={value:0};(f.material as T.PointsMaterial).onBeforeCompile=shader=>{shader.uniforms.uAge=age;shader.vertexShader='uniform float uAge;\nattribute vec3 velocity;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\ntransformed+=velocity*uAge;transformed.y-=2.5*uAge*uAge;')};f.frustumCulled=false;f.userData={age,life:1.3};world.add(f);fx.push(f)}
 function damageText(t:string,healing=false){const e=document.createElement('div');e.className='damage';e.textContent=t;if(healing){e.style.left='30%';e.style.color='#acffdc'}document.getElementById('floaters')!.append(e);later(()=>e.remove(),1100)}
 function impact(magic=false){shake=magic?.42:.2;hitstop=.09;flash.color.set(magic?'#8bf5ff':'#ffd1a0');flash.intensity=magic?65:25;fade.style.background=magic?'#b8fff6':'#ffe4b8';fade.style.opacity=magic?'.22':'.1';later(()=>fade.style.opacity='0',110);tone(magic?880:130,.3,magic?'sine':'triangle',.08)}
 function startBattle(o:Obj){const definition=chapter.enemies[o.id];if(!definition){notify('この敵の定義が見つかりません');return}const boss=!!definition.boss;mode='battle';busy=true;near=undefined;battle={definition,id:o.id,boss,name:o.name,hp:definition.hp,max:definition.hp,turn:0,charge:false,phase:1,origin:{x:s.x,z:s.z},obj:o};hero.position.set(s.x-2,height(s.x,s.z),s.z+1);companion.position.set(s.x-3,height(s.x,s.z),s.z+3);enemySprite=o.mesh as T.Sprite;enemySprite.position.set(s.x+3,height(s.x,s.z),s.z-2);battleLog=definition.intro||'魔物が行く手をふさいだ！';if(boss){bloom.strength=1.1;burst(enemySprite.position.x,3,enemySprite.position.z,'#79ffee',160);impact(true)}renderUI();later(()=>{busy=false;battleLog='リオたちは どうする？';renderUI()},1500)}
 function command(cmd:string){if(mode!=='battle'||busy)return;if(cmd==='fire'&&s.mp<6||cmd==='heal'&&s.mp<5||cmd==='potion'&&s.potions<=0||cmd==='ether'&&s.ethers<=0)return;busy=true;const e=enemySprite!;let dmg=0,guard=false;battle.turn++;if(cmd==='attack'){dmg=17+s.lv*4+(s.sword?9:0);battleLog='リオの攻撃！';anim=1;later(()=>{impact();burst(e.position.x,1.8,e.position.z,'#ffe2a0',50)},350)}if(cmd==='fire'){s.mp-=6;dmg=33+s.lv*6+(battle.definition.fireBonus??0);battleLog='ミナは 星火 を唱えた！';flash.color.set('#63cfff');flash.intensity=30;anim=2;burst(hero.position.x,2,hero.position.z,'#87eaff',75);later(()=>{impact(true);burst(e.position.x,2.5,e.position.z,'#80eaff',160)},650)}if(cmd==='heal'){s.mp-=5;const heal=Math.min(maxHP()-s.hp,58);s.hp+=heal;battleLog='ミナの 灯の癒し。HPが回復した！';burst(hero.position.x,1,hero.position.z,'#b1ffd4',65);damageText('+'+heal,true);tone(660,.7)}if(cmd==='potion'){s.potions--;const heal=Math.min(maxHP()-s.hp,65);s.hp+=heal;battleLog='薬草を使った。HPが回復した！';damageText('+'+heal,true)}if(cmd==='ether'){s.ethers--;s.mp=Math.min(maxMP(),s.mp+20);battleLog='星の雫を使った。MPが20回復した！';tone(740,.4)}if(cmd==='guard'){guard=true;battleLog='リオたちは 身を守っている。'}renderUI();later(()=>{if(dmg){battle.hp=Math.max(0,battle.hp-dmg);damageText(String(dmg));renderUI()}},cmd==='fire'?700:400);
 later(()=>{anim=0;if(battle.hp<=0){victory();return}if(battle.boss&&battle.hp<=battle.max*.5&&battle.phase===1){battle.phase=2;scene.fog=new T.FogExp2(chapter.effects.phaseFog,chapter.effects.phaseDensity);sun.color.set(chapter.effects.phaseSun);bloom.strength=1.35;battleLog=battle.definition.phaseText||'魔物の力が高まった！';impact(true);burst(e.position.x,3,e.position.z,'#d48cff',180);renderUI();later(()=>enemyTurn(guard),1300)}else enemyTurn(guard)},1500)}
 function enemyTurn(guard:boolean){if(!battle)return;if(battle.boss&&!battle.charge&&battle.turn%3===1){battle.charge=true;battleLog=battle.definition.chargeText||'次の一撃に備えよう！';flash.color.set('#e5a3ff');flash.intensity=25;burst(enemySprite!.position.x,2,enemySprite!.position.z,'#c892ff',70);tone(160,.8,'triangle');busy=false;renderUI();return}const charged=battle.charge;let dmg=charged?(battle.definition.chargeAttack??battle.definition.attack):battle.phase===2?(battle.definition.phaseAttack??battle.definition.attack):battle.definition.attack;dmg=Math.max(1,dmg-(s.armor?5:0));if(guard)dmg=Math.ceil(dmg*.25);battle.charge=false;s.hp=Math.max(0,s.hp-dmg);battleLog=(charged?(battle.definition.chargeName||battle.name+'の強攻撃！'):battle.name+'の攻撃！')+' '+dmg+' ダメージ'+(guard?'（防御）':'');damageText('-'+dmg,true);impact(charged);burst(hero.position.x,1.5,hero.position.z,charged?'#c491ff':'#ffdba1',charged?130:40);renderUI();later(()=>{if(s.hp<=0){mode='explore';battle=null;modal='';s.hp=maxHP();s.mp=maxMP();s.gold=Math.max(0,s.gold-10);void changeMap(chapter.respawn.area,chapter.respawn).then(()=>{chapter.onDefeat(ctx);save()}).catch(()=>{})}else{busy=false;battleLog='リオたちは どうする？';renderUI()}},1000)}
 function victory(){const boss=battle.boss,id=battle.id;const xp=battle.definition.xp,gold=battle.definition.gold;s.xp+=xp;s.gold+=gold;recordVictory(s.campaign,id,boss);let leveled=false;while(s.xp>=s.lv*30){s.xp-=s.lv*30;s.lv++;leveled=true}s.hp=leveled?maxHP():s.hp;s.mp=leveled?maxMP():s.mp;battleLog='勝利！ '+xp+' EXP / '+gold+' G'+(leveled?'　レベルアップ！ HP・MP全回復':'');enemySprite!.visible=false;burst(enemySprite!.position.x,2,enemySprite!.position.z,'#ffe2a2',150);tone(523,.2);later(()=>tone(659,.25),200);later(()=>tone(784,.7),400);renderUI();later(()=>{mode='explore';battle=null;bloom.strength=.65;build();if(boss){chapter.onBossVictory(ctx,id)}else{save();notify(leveled?'レベル '+s.lv+' になった！':'道が開けた。先へ進もう')}},1900)}
 function party(){return `<div class="party"><small>Lv. ${s.lv}</small><b>リオ <span style="font-size:11px;color:#bbc9cb">& ミナ</span></b><div class="stat"><span>HP</span><div class="bar"><i style="width:${s.hp/maxHP()*100}%"></i></div><span>${s.hp}/${maxHP()}</span></div><div class="stat"><span>MP</span><div class="bar mp"><i style="width:${s.mp/maxMP()*100}%"></i></div><span>${s.mp}/${maxMP()}</span></div></div>`}
 function btn(id:string,t:string,disabled=false){return `<button data-action="${id}" ${disabled?'disabled':''}>${t}</button>`}
 function renderUI(){uiDirty=false;const goal=nextGoal();let h='<div class="vignette"></div>';if(mode==='title'){let has=false;try{has=hasSave(localStorage)}catch{}h+=`<div class="title"><div class="eyebrow">A TALE OF THE LAST LIGHT</div><h1>灯の継承者</h1><div class="subtitle">L U M E N F A L L</div><p>消えゆく灯。小さな約束。<br>夜明けをつなぐ、ふたりの旅。</p>${btn('new','はじめから　 →')}${has?btn('load','つづきから'):''}</div><div class="corner">A SHORT FANTASY · 約15分の冒険</div>`}
 else if(mode==='loading'){h+='<div class=overlay><div class=panel>灯をつないでいます…</div></div>'}
 else if(mode==='ending'){h+=chapter.endingUI(ctx)}
 else if(mode==='battle'){h+=`<div class="battle"><div class="battlehead"><div class="eyebrow">${battle.definition.eyebrow||'ENCOUNTER'}</div><h2>${battle.name}</h2><div class="enemybar"><i style="width:${battle.hp/battle.max*100}%"></i></div><p style="font:11px Arial;color:#ddd4c2">${battle.hp} / ${battle.max}${battle.charge?'　 ⚠ 次の攻撃に備えよう':''}</p></div><div class="bottom">${party()}</div><div class="battlelog">${battleLog}</div><div class="commands">${btn('attack','剣で攻撃<small>SWORD</small>',busy)}${btn('fire','星火<small>MP 6 · 光の攻撃</small>',busy||s.mp<6)}${btn('heal','灯の癒し<small>MP 5 · HP回復</small>',busy||s.mp<5)}${btn('guard','身を守る<small>被ダメージを軽減</small>',busy)}${btn('potion',`薬草 ×${s.potions}<small>HP +65</small>`,busy||!s.potions)}${btn('ether',`星の雫 ×${s.ethers}<small>MP +20</small>`,busy||!s.ethers)}</div></div>`}
 else {h+=`${chapter.hud(ctx)}<div class="bottom">${party()}<div class="help">WASD / 矢印キー · 移動　 E / Space · 調べる<br>地面をクリック · 移動　 Esc · メニュー</div></div>${near&&!modal?`<button class="interact" data-action="interact"><em>E</em>${near.name}</button>`:''}<div class="joystick" id="joystick" aria-label="移動スティック"><i></i></div>`}
 if(modal==='dialogue')h+=`<div class="dialogue"><b>${speaker}</b><p>${dialogues[0]}</p>${btn('next',dialogues.length>1?'つづける　 ▸':'閉じる　 ▸')}<div style="clear:both"></div></div>`;
 if(modal==='menu')h+=`<div class="overlay"><div class="panel"><div class="eyebrow">TRAVEL JOURNAL</div><h2>冒険の記録</h2><p>${chapter.title}${cp().completed?' · CLEAR':''}<br>リオとミナ　Lv. ${s.lv}　 /　${s.gold} G<br>経験値 ${s.xp} / ${s.lv*30}<br>武器：${s.sword?'暁鉄の剣（攻撃 +9）':'旅立ちの剣'}<br>防具：${s.armor?'織星の外套（被ダメージ −5）':'旅人の服'}</p>${btn('usepotion',`薬草を使う ×${s.potions}　 HP +65`,!s.potions||s.hp===maxHP())}${btn('useether',`星の雫を使う ×${s.ethers}　 MP +20`,!s.ethers||s.mp===maxMP())}${btn('save','冒険を記録する')}${btn('load','記録から再開する')}${btn('quality','画質：'+(quality==='auto'?'自動調整':quality==='high'?'高画質':'軽量'))}<p id="renderStats" style="font:12px Arial;line-height:1.6"></p>${btn('chapters','チャプターの記録')}${btn('controls','操作方法')}${btn('close','旅に戻る')}</div></div>`;
 if(modal==='map')h+=`<div class="overlay"><div class="panel"><div class="eyebrow">NEARBY</div><h2>周辺の案内</h2><p>目的地を選ぶと、歩いて向かいます。</p>${objects.filter(o=>(o.kind!=='chest'||!cp().chests.includes(o.id))&&chapter.objectVisibleInGuide(ctx,o)).map(o=>btn('walk-'+o.id,o.name)).join('')}${btn('close','戻る')}</div></div>`;
 if(modal==='chapters')h+=`<div class=overlay><div class=panel><h2>チャプターの記録</h2><p>進行と所持品を引き継いで再開します。</p>${chapterCatalog.map(c=>btn('chapter:'+c.id,c.title+(s.campaign.completedChapters.includes(c.id)?' · CLEAR':''),!s.campaign.unlockedChapters.includes(c.id))).join('')}${btn('close','戻る')}</div></div>`;
 h+=chapter.modalUI(ctx);
 if(modal==='controls')h+=`<div class="overlay"><div class="panel"><h2>旅の手引き</h2><p>移動：WASD / 矢印キー。地面のクリック・タップでも移動できます。スマホでは左下のスティックを使えます。<br><br>会話・宝箱・出入口：近づいて E / Space、または表示されたボタン。<br><br>戦闘はコマンド選択式。敵が力をためたら「身を守る」。HPが減ったら薬草や癒しの魔法を。<br><br>エリア移動・勝利・買い物時に自動保存。メニューから手動でも保存できます。記録はこのブラウザに保存されます。</p>${btn('close','戻る')}</div></div>`;
 if(toast&&clock<toastUntil)h+=`<div class="toast">${toast}</div>`;if(h===uiMarkup)return;uiMarkup=h;const oldJoy=ui.querySelector('#joystick');
 // Keep the captured node connected while nearby prompts and toasts change.
 if(oldJoy&&releaseJoystick&&mode==='explore'&&!modal){const template=document.createElement('template');template.innerHTML=h;template.content.querySelector('#joystick')?.remove();for(const child of [...ui.childNodes])if(child!==oldJoy)child.remove();ui.append(template.content)}
 else{releaseJoystick?.();releaseJoystick=undefined;ui.innerHTML=h;const joystick=ui.querySelector('#joystick') as HTMLElement|null;if(joystick&&mode==='explore'&&!modal)releaseJoystick=bindJoystick(joystick,(x,y)=>{joy={x,y};target=null;route=[]});else joy={x:0,y:0}}}

 function action(e:MouseEvent){if(mode==='loading')return;const b=(e.target as HTMLElement).closest('[data-action]') as HTMLButtonElement;if(!b||b.disabled)return;activateAudio();const a=b.dataset.action!;if(mode==='battle'){command(a);return}tone(440,.04);if(chapter.action(ctx,a))return;if(a==='chapters'){modal='chapters';renderUI();return}if(a.startsWith('chapter:')){void switchChapter(a.slice(8)).catch(e=>notify(e.message));return}if(a==='quality'){quality=quality==='auto'?'high':quality==='high'?'low':'auto';try{localStorage.setItem('lumenfall-quality',quality)}catch{};adaptive.scale=1;resize()}if(a==='guide'){const goal=nextGoal();if(goal){if(Math.hypot(goal.x-s.x,goal.z-s.z)<goal.r)interact(goal);else{navigate(goal.x,goal.z);notify('目的地まで歩いて案内します')}}}if(a==='new')void newGame().catch(e=>notify(e.message));if(a==='load')load();if(a==='next')next();if(a==='interact')interact();if(a==='menu'){modal=modal?'':'menu';target=null}if(a==='close')modal='';if(a==='controls')modal='controls';if(a==='map')modal='map';if(a.startsWith('walk-')){const o=objects.find(o=>o.id===a.slice(5));modal='';if(o)navigate(o.x,o.z)}if(a==='sound')muted=!muted;if(a==='save')save(true);if(a==='after'){mode='explore';modal='';save()}if(a==='usepotion'&&s.potions){s.potions--;s.hp=Math.min(maxHP(),s.hp+65);save()}if(a==='useether'&&s.ethers){s.ethers--;s.mp=Math.min(maxMP(),s.mp+20);save()}if(a.startsWith('buy-')){const item=a.slice(4),cost=item==='potion'?15:item==='ether'?20:item==='sword'?40:35;if(s.gold>=cost){s.gold-=cost;if(item==='potion')s.potions++;if(item==='ether')s.ethers++;if(item==='sword')s.sword=true;if(item==='armor')s.armor=true;save();notify(item==='sword'||item==='armor'?'購入して装備した':'購入した')}}if(a==='rest'){s.gold=Math.max(0,s.gold-10);s.hp=maxHP();s.mp=maxMP();modal='';save();chapter.onRest(ctx)}renderUI()}
 ui.addEventListener('click',action);
 const down=(e:KeyboardEvent)=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' ','Tab'].includes(e.key)&&e.key!=='Tab')e.preventDefault();keys.add(e.key.toLowerCase());if(e.repeat)return;activateAudio();if(e.key==='Escape'&&mode==='explore'){if(modal==='dialogue')next();else{modal=modal?'':'menu';renderUI()}}if(['e','E',' ','Enter'].includes(e.key)){if(modal==='dialogue')next();else if(mode==='explore'&&!modal)interact()}};const up=(e:KeyboardEvent)=>keys.delete(e.key.toLowerCase());const blur=()=>{keys.clear();joy={x:0,y:0};target=null;route=[]};window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);

 const ctx:ChapterContext={get state(){return s},get progress(){return cp()},get world(){return world},scene,ambient,sun,get objects(){return objects},get blocks(){return blocks},mats,get modal(){return modal},set modal(v){modal=v},get mode(){return mode},set mode(v){mode=v},get clock(){return clock},get muted(){return muted},get companion(){return companion},get near(){return near},box,cyl,mat,water,tree,torch,light,sprite,chest,addObj,exitMarker,house,height,rand,build,save,notify,talk,renderUI,burst,transition,startBattle,maxHP,maxMP,btn,finish,switchChapter};
 async function activate(next:typeof s,isNew:boolean){const oldMode=mode;mode='loading';renderUI();try{const pack=await loadChapter(next.campaign.currentChapter);pack.initialize(next);pack.normalize(next);const selected=pack.maps.find(m=>m.id===next.area);if(!selected)throw Error('マップが見つかりません');const nextMap=await selected.load();if(dead)return;blur();timers.forEach(clearTimeout);timers.clear();battle=null;enemySprite=undefined;near=undefined;afterDialogue=undefined;dialogues=[];anim=0;busy=false;shake=hitstop=0;flash.intensity=0;fade.style.opacity='0';document.getElementById('floaters')!.replaceChildren();bloom.strength=.65;if(chapter.id!==pack.id){collectResources();disposeWorld();spriteCache.forEach(t=>t.dispose());spriteCache.clear()}chapter=pack;s=next;loadedMap=nextMap;mode='explore';modal='';unlockArea(s.campaign,s.area);build()}catch(e){mode=oldMode;renderUI();throw e}}
 async function switchChapter(id:string){if(mode==='loading'||mode==='battle')return;const pack=await loadChapter(id);const next=prepareChapterSwitch(s,id,pack.start);const first=!next.campaign.chapters[id].position;await activate(next,false);save();if(first)chapter.begin(ctx)}
 async function changeMap(area:number,position?:{x:number;z:number}){const selected=chapter.maps.find(m=>m.id===area);if(!selected)throw Error('マップが見つかりません');const oldMode=mode;mode='loading';blur();renderUI();try{const next=await selected.load();if(dead)return;timers.forEach(clearTimeout);timers.clear();s.area=area;s.x=position?.x??selected.spawn.x;s.z=position?.z??selected.spawn.z;loadedMap=next;near=undefined;mode='explore';unlockArea(s.campaign,area);build()}catch(e){mode=oldMode;renderUI();notify('マップを読み込めませんでした。もう一度お試しください');throw e}}
 function finish(){completeChapter(s.campaign,chapter.unlockNext);save();void changeMap(chapter.returnTo.area,chapter.returnTo).then(()=>{chapter.onEnding(ctx);mode='ending';save();renderUI()}).catch(()=>{})}
 const ray=new T.Raycaster(),plane=new T.Plane(new T.Vector3(0,1,0),0);const point=(e:PointerEvent)=>{if(mode!=='explore'||modal)return;const v=new T.Vector2(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1);ray.setFromCamera(v,camera);const p=new T.Vector3();if(ray.ray.intersectPlane(plane,p)){navigate(T.MathUtils.clamp(p.x,-21,21),T.MathUtils.clamp(p.z,-21,21))}};canvas.addEventListener('pointerdown',point);
 function resize(){const scale=quality==='low'?.7:quality==='high'?1.2:adaptive.scale;renderer.setPixelRatio(software?1:pixelRatio(innerWidth,innerHeight,devicePixelRatio,mobileDevice,scale));renderer.setSize(innerWidth,innerHeight);if(!software){composer.setPixelRatio(renderer.getPixelRatio());composer.setSize(innerWidth,innerHeight);bloom.setSize(innerWidth*renderer.getPixelRatio()*.5,innerHeight*renderer.getPixelRatio()*.5)}camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();tilt.uniforms.resolution.value.set(canvas.width,canvas.height)}window.addEventListener('resize',resize);resize();build();document.getElementById('loading')?.remove();
 function navigate(x:number,z:number){const step=.75;const start=[Math.round(s.x/step),Math.round(s.z/step)];const queue=[start],seen=new Set([start.join(',')]),prev=new Map<string,string>();let goal='';for(let n=0;n<queue.length&&n<5000;n++){const [a,b]=queue[n];if(Math.hypot(a*step-x,b*step-z)<1.2){goal=[a,b].join(',');break}for(const [da,db] of [[0,1],[0,-1],[1,0],[-1,0]]){const aa=a+da,bb=b+db,k=[aa,bb].join(',');if(!seen.has(k)&&canMove(aa*step,bb*step)){seen.add(k);prev.set(k,[a,b].join(','));queue.push([aa,bb])}}}if(goal){const points=[];while(prev.has(goal)){const [a,b]=goal.split(',').map(Number);points.push(new T.Vector3(a*step,0,b*step));goal=prev.get(goal)!}route=points.reverse();target=route.shift()??null}else notify('そこへは歩いて行けないようだ')}
 function canMove(x:number,z:number){return x>-22&&x<22&&z>-22&&z<22&&chapter.walkable(s,x,z)&&!blocks.some(b=>Math.abs(x-b.x)<b.w/2+.23&&Math.abs(z-b.z)<b.d/2+.23)}
 function updateActorShadow(sp:T.Sprite){const sh=sp.userData.shadow;sh.position.set(sp.position.x,height(sp.position.x,sp.position.z)+.025,sp.position.z)}
 function schedule(){raf=software?window.setTimeout(()=>frame(performance.now()),16):requestAnimationFrame(frame)}
 function visibility(){blur();if(document.hidden){cancelAnimationFrame(raf);clearTimeout(raf)}else{last=performance.now();lastFrameAt=0;frameSum=frameCount=0;statsAt=last;schedule()}}document.addEventListener('visibilitychange',visibility);
 function frame(now:number){if(dead||document.hidden)return;schedule();if(!software&&now-lastFrameAt<16)return;if(!software)lastFrameAt=now-((now-lastFrameAt)%(1000/60));const elapsed=now-last;let dt=Math.min(elapsed/1000,.045);last=now;clock+=dt;if(mode==='loading')return;s.time+=dt;timeUniform.value=clock;if((waterFrame++&1)===0)waterTimeUniform.value=clock;shake*=Math.exp(-dt*7.67);hitstop=Math.max(0,hitstop-dt);flash.intensity*=Math.exp(-dt*4.35);if(toast&&clock>toastUntil){toast='';uiDirty=true}
 frameSum+=elapsed;frameCount++;if(now-statsAt>1000){fps=Math.round(1000/(frameSum/Math.max(1,frameCount)));if(!software&&quality==='auto'&&!busy&&hitstop===0&&adaptive.sample(frameSum/Math.max(1,frameCount)))resize();frameSum=frameCount=0;statsAt=now;const stats=document.getElementById('renderStats');if(stats)stats.textContent=`${software?'互換描画（GPUを利用できません）':'WebGL'} · ${fps} fps · ${canvas.width} × ${canvas.height} · 描画グループ ${scene.userData.batches?.after??0}`}
 if(clock-lastLight>.2){lastLight=clock;const focus=mode==='title'?camLook:hero.position;localLights.sort((a,b)=>a.position.distanceToSquared(focus)-b.position.distanceToSquared(focus));lightPool.forEach((l,i)=>{const source=localLights[i];if(source){l.position.copy(source.position);l.color.copy(source.color);l.intensity=source.power}else l.intensity=0})}
 if(!software&&clock-lastShadow>.5){lastShadow=clock;if(!map().night){sun.position.x=-18+Math.sin(clock*.012)*10;renderer.shadowMap.needsUpdate=true}}
 if(audio&&!muted&&clock>nextNote){nextNote=clock+(mode==='battle'?.4:1.1);const notes=mode==='battle'?chapter.music.battle:map().night?chapter.music.night:chapter.music.field;tone(notes[Math.floor(clock*1.1)%notes.length],1.8,'sine',.016)}
 if(clock-lastAmbient>1/30){lastAmbient=clock;for(const f of flames)f.scale.y=1.05+Math.sin(clock*13+f.position.x)*.18;for(const g of grass)g.rotation.z=Math.sin(clock*2+g.position.x)*.12}
 for(let i=fx.length-1;i>=0;i--){const f=fx[i];f.userData.life-=dt;f.userData.age.value=1.3-f.userData.life;(f.material as T.PointsMaterial).opacity=Math.max(0,f.userData.life/1.3);if(f.userData.life<=0){world.remove(f);f.geometry.dispose();(f.material as T.Material).dispose();fx.splice(i,1)}}
 if(mode==='explore'&&!modal){let dx=0,dz=0;const sx=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0)+joy.x,sy=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0)+joy.y;if(sx||sy){target=null;route=[];dx=sx*.85+sy*.53;dz=-sx*.53+sy*.85}else if(target){dx=target.x-s.x;dz=target.z-s.z;if(Math.hypot(dx,dz)<.18){target=route.shift()??null;dx=dz=0}}const l=Math.hypot(dx,dz);if(l>.01){dx/=l;dz/=l;const nx=s.x+dx*dt*5,nz=s.z+dz*dt*5;let moved=false;if(canMove(nx,s.z)){s.x=nx;moved=true}if(canMove(s.x,nz)){s.z=nz;moved=true}if(!moved)target=null;hero.material.rotation=Math.sin(clock*15)*.035;hero.position.y=height(s.x,s.z)+Math.abs(Math.sin(clock*12))*.07;hero.material.map!.repeat.x=1;hero.material.map!.offset.x=0}else{hero.material.rotation=0;hero.position.y=height(s.x,s.z)+.06}hero.position.x=s.x;hero.position.z=s.z;let n:Obj|undefined,best=Infinity;for(const o of objects){const d=(o.x-s.x)**2+(o.z-s.z)**2;if(d<o.r*o.r&&d<best){best=d;n=o}}if(n!==near){near=n;uiDirty=true}}
 if(mode!=='battle'){companion.position.lerp(followPosition.set(s.x+1,height(s.x+1,s.z+1)+.06,s.z+1),dt*4);if(mode==='title'){camLook.set(-1,1,0);camPos.set(22+Math.sin(clock*.05)*3,24,31)}else{camLook.set(s.x,1,s.z-1);const mobile=innerWidth<600;camPos.set(s.x+(mobile?19:15),mobile?27:21,s.z+(mobile?30:24))}if(!map().night){const t=.5+.5*Math.sin(clock*.015);sun.color.setHSL(.105-t*.045,.52,.8);sun.intensity=3.8-t*1.3}}
 else{const h=hero.position,e=enemySprite!.position,mobile=innerWidth<600;const orbit=clock*(battle.boss?.24:.12);camLook.set((h.x+e.x)/2,1.5,(h.z+e.z)/2);const radius=mobile?(battle.boss?35:29):17;camPos.set(camLook.x+Math.sin(orbit)*3+6,anim===2?9:12,camLook.z+radius-(anim?3:0));if(battle.boss){enemySprite!.position.y=height(s.x,s.z)+Math.sin(clock*2)*.15;enemySprite!.material.color.set(battle.phase===2?'#e0bdff':'#d7fffa')}}
 camera.position.lerp(camPos,dt*(mode==='battle'?2.3:3));const look=lookPosition.copy(camLook);if(shake){camera.position.x+=(Math.random()-.5)*shake;camera.position.y+=(Math.random()-.5)*shake}camera.lookAt(look);updateActorShadow(hero);updateActorShadow(companion);if(uiDirty)renderUI();if(hitstop<=0)composer.render()}
 schedule();return()=>{dead=true;releaseJoystick?.();cancelAnimationFrame(raf);clearTimeout(raf);timers.forEach(clearTimeout);window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur);window.removeEventListener('resize',resize);document.removeEventListener('visibilitychange',visibility);canvas.removeEventListener('pointerdown',point);ui.removeEventListener('click',action);audio?.close();collectResources();disposeWorld();Object.values(mats).forEach(m=>m.dispose());spriteCache.forEach(t=>t.dispose());composer.dispose();renderer.dispose()}
}
