import * as T from 'three';
import {bindJoystick} from './input';
import {SoftwareRenderer} from './software';
import {dungeonWalls,sealedGate,shrines,gateOpen,dungeonWalkable} from './dungeon';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';
import {UnrealBloomPass} from 'three/addons/postprocessing/UnrealBloomPass.js';
import {ShaderPass} from 'three/addons/postprocessing/ShaderPass.js';
import {Reflector} from 'three/addons/objects/Reflector.js';

type Save={area:number,x:number,z:number,hp:number,mp:number,lv:number,xp:number,gold:number,potions:number,ethers:number,sword:boolean,armor:boolean,quest:number,chests:string[],wins:string[],seals:string[],springUsed:boolean,dungeonVersion:number,time:number};
type Obj={x:number,z:number,r:number,name:string,kind:string,id:string,mesh?:T.Object3D};
const fresh=():Save=>({area:0,x:0,z:8,hp:100,mp:30,lv:1,xp:0,gold:35,potions:4,ethers:2,sword:false,armor:false,quest:0,chests:[],wins:[],seals:[],springUsed:false,dungeonVersion:1,time:0});
const areas=[['水灯の町 リュネ','LYUNE · THE LANTERN VILLAGE','夕映えの水路'],['琥珀の丘','AMBER HIGHLANDS','風渡る旧街道'],['星眠りの遺跡','MOONFALL SANCTUM','森に眠る双灯の迷宮']];
export function startGame(){
 let canvas=document.getElementById('world') as HTMLCanvasElement;const ui=document.getElementById('ui')!,fade=document.getElementById('fade')!;
 let renderer:any,software=false;try{renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});}catch{software=true;const replacement=canvas.cloneNode() as HTMLCanvasElement;canvas.replaceWith(replacement);canvas=replacement;renderer=new SoftwareRenderer(canvas)}
 renderer.setPixelRatio(Math.min(devicePixelRatio,1.65));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.18;
 const scene=new T.Scene(),camera=new T.PerspectiveCamera(36,1,.1,180);scene.background=new T.Color('#758c98');scene.fog=new T.FogExp2('#8d9b9b',.021);
 const composer:any=software?{addPass:()=>{},setSize:()=>{},dispose:()=>{},render:()=>renderer.render(scene,camera)}:new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));const bloom=new UnrealBloomPass(new T.Vector2(800,600),.65,.5,.82);composer.addPass(bloom);
 const tilt=new ShaderPass({uniforms:{tDiffuse:{value:null},resolution:{value:new T.Vector2(800,600)},strength:{value:1.7}},vertexShader:'varying vec2 vUv; void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:`uniform sampler2D tDiffuse;uniform vec2 resolution;uniform float strength;varying vec2 vUv;void main(){float f=smoothstep(.13,.47,abs(vUv.y-.49));vec2 d=vec2(1.)/resolution*f*strength*2.;vec4 c=texture2D(tDiffuse,vUv)*.24;c+=texture2D(tDiffuse,vUv+d)*.12;c+=texture2D(tDiffuse,vUv-d)*.12;c+=texture2D(tDiffuse,vUv+vec2(d.x,-d.y))*.12;c+=texture2D(tDiffuse,vUv+vec2(-d.x,d.y))*.12;c+=texture2D(tDiffuse,vUv+vec2(0.,d.y*2.))*.07;c+=texture2D(tDiffuse,vUv-vec2(0.,d.y*2.))*.07;c+=texture2D(tDiffuse,vUv+vec2(d.x*2.,0.))*.07;c+=texture2D(tDiffuse,vUv-vec2(d.x*2.,0.))*.07;float vig=1.-.32*pow(length((vUv-.5)*1.4),1.5);gl_FragColor=vec4(c.rgb*vig,1.);}`});composer.addPass(tilt);
 const ambient=new T.HemisphereLight('#c3e1ef','#384538',2);scene.add(ambient);const sun=new T.DirectionalLight('#ffcf85',4);sun.position.set(-14,25,9);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-30,right:30,top:30,bottom:-30,near:1,far:90});sun.shadow.bias=-.0007;sun.shadow.normalBias=.035;scene.add(sun);const flash=new T.PointLight('#85dbff',0,35,1);flash.position.set(0,5,0);scene.add(flash);
 let world=new T.Group();scene.add(world);let hero:T.Sprite,companion:T.Sprite,enemySprite:T.Sprite|undefined;let objects:Obj[]=[],blocks:{x:number,z:number,w:number,d:number}[]=[],waters:T.Mesh[]=[],flames:T.Sprite[]=[],grass:T.Mesh[]=[],particles:T.Points;let mode='title',modal='',dialogues:string[]=[],speaker='',afterDialogue:(()=>void)|undefined;let releaseJoystick:(()=>void)|undefined;let s=fresh(),keys=new Set<string>(),joy={x:0,y:0},target:T.Vector3|null=null,route:T.Vector3[]=[],near:Obj|undefined,clock=0,last=performance.now(),raf=0,dead=false,toast='',toastUntil=0,shake=0,hitstop=0,battle:any=null,busy=false,battleLog='',fx:T.Points[]=[];let audio:AudioContext|undefined,muted=false,nextNote=0;let camLook=new T.Vector3(),camPos=new T.Vector3(),anim=0;const timers:ReturnType<typeof setTimeout>[]=[];const later=(f:()=>void,t:number)=>{timers.push(setTimeout(()=>{if(!dead)f()},t))};
 const maxHP=()=>100+(s.lv-1)*24,maxMP=()=>30+(s.lv-1)*8;
 const rand=(n:number)=>{const x=Math.sin(n*127.1+311.7)*43758.5453;return x-Math.floor(x)};
 const mat=(color:string,roughness=.9)=>new T.MeshStandardMaterial({color,roughness});
 const mats={stone:mat('#8b9186'),dark:mat('#505d58'),wall:mat('#ddcba6'),wood:mat('#665044'),roof:mat('#487573'),gold:mat('#b38a45'),ground:mat('#647b46'),path:mat('#b4a17a')};
 function box(x:number,y:number,z:number,w:number,h:number,d:number,m:T.Material,cast=true){const a=new T.Mesh(new T.BoxGeometry(w,h,d,software?Math.ceil(w/3):1,1,software?Math.ceil(d/3):1),m);a.position.set(x,y,z);a.castShadow=cast;a.receiveShadow=true;world.add(a);return a}
 function cyl(x:number,y:number,z:number,r:number,h:number,m:T.Material,n=8){const a=new T.Mesh(new T.CylinderGeometry(r,r*1.08,h,n),m);a.position.set(x,y,z);a.castShadow=true;a.receiveShadow=true;world.add(a);return a}
 function texture(kind:string){const c=document.createElement('canvas');c.width=48;c.height=64;const g=c.getContext('2d')!;const rect=(x:number,y:number,w:number,h:number,col:string)=>{g.fillStyle=col;g.fillRect(x,y,w,h)};
 if(kind==='slime'){for(let y=19;y<53;y++){const w=Math.floor(Math.sqrt(Math.max(0,1-((y-37)/19)**2))*20);rect(24-w,y,w*2,1,y<28?'#b3ece0':y<40?'#61c4b0':'#328b8d')}rect(12,26,9,5,'#dcffec');rect(15,37,4,6,'#173e48');rect(31,37,4,6,'#173e48');rect(22,47,8,2,'#244f56');}
 else if(kind==='wolf'){rect(6,29,35,18,'#4c6280');rect(7,24,19,20,'#768eaa');rect(8,15,6,14,'#91a3b4');rect(22,18,5,12,'#617491');rect(4,34,8,8,'#9aa8b7');rect(9,48,6,10,'#3d4e69');rect(31,46,6,12,'#3d4e69');rect(13,31,4,3,'#f2c16d');rect(38,22,5,19,'#627c98');}
 else if(kind==='boss'){for(let y=6;y<61;y++){const w=Math.floor(12+8*Math.sin(y*.11));rect(24-w,y,w*2,1,y<20?'#819daf':y<44?'#425d73':'#293a54')}rect(9,1,5,16,'#d1bd82');rect(34,1,5,16,'#d1bd82');rect(5,23,8,19,'#789495');rect(35,23,8,19,'#789495');rect(14,22,7,3,'#fff5a9');rect(28,22,7,3,'#fff5a9');rect(21,32,7,13,'#7dedec');rect(23,34,3,9,'#e1ffff');rect(7,45,8,14,'#334454');rect(33,45,8,14,'#334454');}
 else{const npc=kind!=='hero',blue=kind==='mage',coat=blue?'#d6d4dc':npc?'#89977a':'#355f83';rect(17,8,15,6,npc?'#aaa197':'#4a3535');rect(14,13,20,13,npc?'#cec1a1':'#533b36');rect(18,15,14,14,'#e9b58c');rect(29,18,3,3,'#26313b');rect(14,13,7,11,npc?'#a7a8a7':'#684335');rect(16,29,17,20,coat);rect(12,30,5,16,coat);rect(32,31,5,13,coat);rect(13,44,5,5,'#e9b58c');rect(33,42,4,6,'#e9b58c');rect(17,46,7,11,'#283947');rect(27,46,6,11,'#283947');rect(15,56,9,4,'#302d31');rect(27,55,9,4,'#302d31');rect(17,28,18,5,blue?'#6bb9b4':'#dfa552');rect(10,32,6,20,blue?'#9eafb9':'#bd6d49');rect(19,43,14,3,'#97754a');if(!npc){rect(36,25,3,30,'#c1d5d3');rect(33,45,9,3,'#c3a26d')}if(blue){rect(9,2,26,6,'#c5c5d9');rect(17,0,13,5,'#b2b5ce');rect(37,24,2,34,'#82775d');rect(34,21,8,7,'#96f7ed')}}
 const tx=new T.CanvasTexture(c);tx.magFilter=T.NearestFilter;tx.minFilter=T.NearestFilter;tx.colorSpace=T.SRGBColorSpace;return tx}
 const spriteCache=new Map<string,T.Texture>();function sprite(kind:string,x:number,z:number,scale=2.2){if(!spriteCache.has(kind))spriteCache.set(kind,texture(kind));const sp=new T.Sprite(new T.SpriteMaterial({map:spriteCache.get(kind),color:'#fff4df',alphaTest:.1,depthWrite:true}));sp.scale.set(scale*.75,scale,1);sp.center.set(.5,0);sp.position.set(x,height(x,z)+.06,z);world.add(sp);const sh=new T.Mesh(new T.CircleGeometry(scale*.24,24),new T.MeshBasicMaterial({color:'#071a20',transparent:true,opacity:.3,depthWrite:false}));sh.rotation.x=-Math.PI/2;sh.position.set(x,height(x,z)+.025,z);world.add(sh);sp.userData.shadow=sh;return sp}
 function height(x:number,z:number){if(s.area===1&&x>5)return Math.min(2.3,(x-5)*.2);if(s.area===2&&z< -7)return Math.min(1.5,(-z-7)*.22);return 0}
 function light(x:number,y:number,z:number,color='#ffd087',power=8){const l=new T.PointLight(color,power,7,2);l.position.set(x,y,z);world.add(l);return l}
 function torch(x:number,z:number){const y=height(x,z);cyl(x,y+.8,z,.09,1.6,mats.wood);const c=document.createElement('canvas');c.width=c.height=32;const g=c.getContext('2d')!,gr=g.createRadialGradient(16,16,0,16,16,16);gr.addColorStop(0,'#fff5c6');gr.addColorStop(.23,'#ffc65b');gr.addColorStop(.5,'#ee761aaa');gr.addColorStop(1,'#ff660000');g.fillStyle=gr;g.fillRect(0,0,32,32);const f=new T.Sprite(new T.SpriteMaterial({map:new T.CanvasTexture(c),blending:T.AdditiveBlending,depthWrite:false}));f.position.set(x,y+1.8,z);f.scale.set(.7,1.2,1);world.add(f);flames.push(f);light(x,y+2,z)}
 function tree(x:number,z:number,scale=1){const y=height(x,z);cyl(x,y+1.6*scale,z,.23*scale,3.2*scale,mats.wood);for(let i=0;i<3;i++){const m=mat(s.area===2?['#234b46','#2c6255','#427b61'][i]:['#466c49','#648347','#839455'][i]);const a=new T.Mesh(new T.ConeGeometry((2-i*.4)*scale,2.5*scale,7),m);a.position.set(x,y+(3+i*1.1)*scale,z);a.rotation.y=rand(x+z)*5;a.castShadow=true;a.receiveShadow=true;world.add(a)}blocks.push({x,z,w:.6*scale,d:.6*scale})}
 function exitMarker(x:number,z:number,label:string){const y=height(x,z);for(const side of [-1,1]){cyl(x+side*2,y+1.7,z,.07,3.4,mats.wood);const banner=box(x+side*2.3,y+2.65,z,.55,1.1,.05,new T.MeshStandardMaterial({color:'#c9a257',emissive:'#775125',emissiveIntensity:.3}));banner.rotation.z=side*.07;torch(x+side*2,z+1)}const c=document.createElement('canvas');c.width=512;c.height=100;const ctx=c.getContext('2d')!;ctx.fillStyle='#0d2631e8';ctx.fillRect(0,0,512,100);ctx.strokeStyle='#e6c47c';ctx.lineWidth=4;ctx.strokeRect(3,3,506,94);ctx.fillStyle='#ffe6a8';ctx.font='32px serif';ctx.textAlign='center';ctx.fillText(label,256,62);const tx=new T.CanvasTexture(c);const sign=new T.Sprite(new T.SpriteMaterial({map:tx,depthWrite:false}));sign.position.set(x,y+3.8,z);sign.scale.set(6.2,1.21,1);world.add(sign);const ring=new T.Mesh(new T.TorusGeometry(1,.045,8,48),new T.MeshStandardMaterial({color:'#ffe1a1',emissive:'#ffc45c',emissiveIntensity:1.8}));ring.rotation.x=-Math.PI/2;ring.position.set(x,y+.12,z);world.add(ring)}
 function nextGoal(){if(s.quest===0||s.quest===3)return undefined;if(s.area===0)return objects.find(o=>o.id==='field');if(s.area===1)return objects.find(o=>o.id==='forest');const shrine=shrines.find(a=>!s.seals.includes(a.id));if(shrine)return objects.find(o=>o.id===(s.wins.includes(shrine.guardian)?shrine.id:shrine.guardian));return objects.find(o=>o.id===(!s.springUsed?'spring':'boss'))}
 function house(x:number,z:number,w:number,d:number,roof='#467471'){box(x,1.5,z,w,3,d,mats.wall);box(x,.22,z,w+.25,.45,d+.25,mats.stone);for(const dx of [-w/2+.1,w/2-.1])box(x+dx,1.6,z+d/2+.03,.17,2.8,.15,mats.wood);box(x,2.7,z+d/2+.05,w,.16,.13,mats.wood);const rm=mat(roof);for(const side of [-1,1]){const r=box(x+side*w*.25,3.6,z,w*.65,.23,d+.8,rm);r.rotation.z=side*-.58;for(let j=0;j<5;j++){const b=box(x+side*(j+.5)*w/10,4.32-j*.18,z,.07,.08,d+.85,mats.dark);b.rotation.z=side*-.58}}box(x+.6,4,z-.5,.55,1.8,.65,mats.stone);box(x,1,z+d/2+.07,.85,2,.1,mats.wood);for(const dx of [-w*.3,w*.3]){box(x+dx,1.65,z+d/2+.09,.7,.9,.07,new T.MeshStandardMaterial({color:'#ffce81',emissive:'#ffac45',emissiveIntensity:2.2}));box(x+dx,1.65,z+d/2+.15,.06,1,.07,mats.wood);box(x+dx,1.65,z+d/2+.15,.8,.06,.07,mats.wood);light(x+dx,1.8,z+d/2+.5,'#ffd291',4)}blocks.push({x,z,w:w+.3,d:d+.3})}
 function addObj(kind:string,name:string,x:number,z:number,id=kind){const o:Obj={kind,name,x,z,r:2.3,id};objects.push(o);return o}
 function chest(x:number,z:number,id:string){const y=height(x,z),opened=s.chests.includes(id);const b=box(x,y+.35,z,.8,.6,.65,opened?mats.dark:mats.wood);box(x,y+.63,z,.87,.13,.69,mats.gold);box(x,y+.4,z+.34,.15,.25,.04,mats.gold);const o=addObj('chest',opened?'空の宝箱':'宝箱を開ける',x,z,id);o.mesh=b}
 function water(x:number,z:number,w:number,d:number,level=-.22){const ref=new Reflector(new T.PlaneGeometry(w,d),{textureWidth:512,textureHeight:512,color:0x648a91,clipBias:.003});ref.rotation.x=-Math.PI/2;ref.position.set(x,level,z);world.add(ref);const mesh=new T.Mesh(new T.PlaneGeometry(w,d,24,48),new T.MeshStandardMaterial({color:'#4e969c',transparent:true,opacity:.38,metalness:.7,roughness:.24}));mesh.rotation.x=-Math.PI/2;mesh.position.set(x,level+.06,z);world.add(mesh);waters.push(mesh)}
 function disposeWorld(){world.traverse(o=>{if(o instanceof T.Mesh||o instanceof T.Points){o.geometry.dispose();const ms=Array.isArray(o.material)?o.material:[o.material];ms.forEach(m=>{if(!Object.values(mats).includes(m))m.dispose()})}if(o instanceof Reflector)o.dispose()});scene.remove(world);world=new T.Group();scene.add(world);objects=[];blocks=[];waters=[];flames=[];grass=[];fx=[]}
 function build(){disposeWorld();const night=s.area===2;scene.background=new T.Color(night?'#253e4d':s.area===1?'#8fa7ac':'#9ba9a3');scene.fog=new T.FogExp2(night?'#395b64':s.area===1?'#9caeb0':'#a0aaa3',night?.025:.022);ambient.intensity=night?1.85:1.7;ambient.groundColor.set(night?'#63777e':'#384538');sun.color.set(night?'#8dcde5':'#ffcd88');sun.intensity=night?2.5:3.5;scene.userData.fillLift=night?1.16:1;
 const riverX=s.area===0?-6:s.area===1?-11:21,riverW=s.area===0?3.3:s.area===1?5:4;const leftEdge=riverX-riverW/2,rightEdge=riverX+riverW/2;box((-24+leftEdge)/2,-1.1,0,leftEdge+24,2,48,night?mat('#294942'):mats.ground);box((rightEdge+24)/2,-1.1,0,24-rightEdge,2,48,night?mat('#294942'):mats.ground);box(0,-2.8,0,49,2.1,49,mats.dark);
 if(s.area===0){water(-6,0,3.3,47);for(const x of [-8,-4])box(x,.05,0,.4,.4,47,mats.stone);for(const z of [5,-8]){box(-6,.1,z,5,.28,3,mats.wood);for(let j=0;j<10;j++)box(-8.3+j*.5,.27,z,.07,.04,3,mats.gold);for(const dz of [-1.45,1.45]){box(-6,.85,z+dz,4.8,.12,.13,mats.wood);for(const x of [-8,-6,-4])box(x,.5,z+dz,.13,1,.13,mats.wood)}}blocks.push({x:-6,z:-17,w:3.5,d:15},{x:-6,z:-1.5,w:3.5,d:9.8},{x:-6,z:15.5,w:3.5,d:17});
 box(1,.012,3,6,.04,30,mats.path);box(0,.015,4,26,.04,3,mats.path);house(-13,-2,5.5,4.7,'#405f72');house(7,-4,5.8,5,'#647d6e');house(13,6,4.5,4,'#806552');house(-13,11,5,4,'#426e74');house(6,-16,5.5,4,'#58746a');
 cyl(0,.25,-5,2.2,.5,mats.stone,16);cyl(0,.6,-5,1.6,.45,mats.dark,16);water(0,-5,2.4,2.4,.84);cyl(0,1.6,-5,.25,2.5,mats.stone);const gem=new T.Mesh(new T.OctahedronGeometry(.5),new T.MeshStandardMaterial({color:'#ffe1a1',emissive:'#ffb95e',emissiveIntensity:2}));gem.position.set(0,3,-5);world.add(gem);light(0,3,-5,'#ffcf89',12);blocks.push({x:0,z:-5,w:3.8,d:3.8});
 sprite('npc',1,1);addObj('elder','灯守のエダ',1,1);sprite('npc',7,0);addObj('shop','道具と装備の店',7,0);sprite('mage',-12,2);addObj('inn','宿屋「水鳥亭」',-12,2);chest(12,10,'town');addObj('exit','琥珀の丘へ',1,-20,'field');exitMarker(1,-20,'北門 → 琥珀の丘');box(1,.015,-16,3.2,.06,10,mats.path);torch(-3,6);torch(3,-10);torch(-9,5);torch(10,3);for(let i=0;i<22;i++){const x=rand(i+4)*43-21,z=rand(i+98)*43-21;if(Math.abs(x)>16||z>16)tree(x,z,.8+rand(i)*.35)}}
 else if(s.area===1){water(-11,0,5,47);blocks.push({x:-11,z:0,w:5,d:48});for(let i=0;i<20;i++){const x=6+i*.65;box(x,-.45+i*.065,0,.7,.7+i*.13,46,mats.ground)}for(let i=0;i<45;i++){const z=22-i;box(Math.sin(z*.13)*2,.035,z,3.3,.06,1.1,mats.path)}for(let i=0;i<38;i++){let x=rand(i+44)*42-21,z=rand(i+83)*44-22;if(Math.abs(x)>6&&Math.abs(x+11)>3)tree(x,z,.65+rand(i)*.7)}for(let i=0;i<12;i++){const x=10+rand(i)*10,z=rand(i+99)*30-15;box(x,height(x,z)+.5,z,1.5,1.4,1.6,mats.stone).rotation.y=i}chest(6,5,'field');sprite('mage',3,13);addObj('traveler','旅の薬師',3,13);const e=sprite('slime',0,5,2);if(!s.wins.includes('slime'))addObj('enemy','露玉プルム',0,5,'slime').mesh=e;else e.visible=false;const w=sprite('wolf',-1,-7,2.3);if(!s.wins.includes('wolf'))addObj('enemy','灰羽の獣',-1,-7,'wolf').mesh=w;else w.visible=false;addObj('exit','リュネの町へ',0,21,'town');addObj('exit','星眠りの遺跡へ',0,-21,'forest');exitMarker(0,-21,'星眠りの遺跡 →');torch(-2,-18);torch(2,-18)}
 else{
 water(21,0,4,47);blocks.push({x:21,z:0,w:4,d:48});
 const floor=mat('#526561'),wall=mat('#4e6463'),cap=mat('#81918a');
 box(0,-.02,5,33,.12,31,floor);for(let i=0;i<19;i++){const z=-7-i*.7;box(0,(i*.7)*.11-.13,z,32,.25,1,mats.stone)}
 for(const b of dungeonWalls){const y=height(b.x,b.z);box(b.x,y+.7,b.z,b.w,1.4,b.d,wall);box(b.x,y+1.46,b.z,b.w+.12,.12,b.d+.12,cap);blocks.push(b);const length=Math.max(b.w,b.d);for(let i=0;i<Math.floor(length/2.5);i++){const along=-length/2+(i+.5)*2.5;box(b.x+(b.w>b.d?along:0),y+.65,b.z+(b.d>b.w?along:0),b.w>b.d?.08:b.w+.03,1.2,b.d>b.w?.08:b.d+.03,mats.dark)}}
 for(let i=0;i<12;i++){box(0,.06,18-i*2,2.4,.09,1.4,mats.dark)}
 for(const x of [-10,10])for(let i=0;i<9;i++)box(x,.07,15-i*2,1.8,.08,1.3,mats.stone);
 for(let i=0;i<24;i++){const x=(i%2?-1:1)*(18.5+rand(i)*1.2),z=rand(i+77)*42-21;tree(x,z,.8+rand(i)*.4)}
 for(const x of [-3,3]){cyl(x,2.2,-8,.5,4.4,mats.stone);box(x,4.5,-8,1.4,.35,1.4,cap);torch(x,13)}box(0,4.5,-8,7,.45,1.2,cap);
 const open=gateOpen(s.seals,s.quest);if(!open){blocks.push(sealedGate);for(let i=-2;i<=2;i++)box(i,.4+1.65,-8,.18,3.3,.2,new T.MeshStandardMaterial({color:'#addaf1',emissive:'#539ddc',emissiveIntensity:1.2}));box(0,1.8,-8,5.5,3.4,.12,new T.MeshStandardMaterial({color:'#6b9fc6',emissive:'#3e82ad',emissiveIntensity:.4,transparent:true,opacity:.28}));light(0,3,-7,'#8dcaff',15)}
 addObj('gate',open?'開かれた双灯の扉':`双灯の扉（封印 ${s.seals.length}/2）`,0,-5.7,'gate');
 for(const shrine of shrines){const done=s.seals.includes(shrine.id);cyl(shrine.x,.35,shrine.z,1.45,.7,mats.stone,12);const ring=new T.Mesh(new T.TorusGeometry(1.15,.065,8,48),new T.MeshStandardMaterial({color:done?'#abffe1':shrine.color,emissive:done?'#6cffc2':shrine.color,emissiveIntensity:done?2:.7}));ring.rotation.x=-Math.PI/2;ring.position.set(shrine.x,.73,shrine.z);world.add(ring);const crystal=new T.Mesh(new T.OctahedronGeometry(.5),new T.MeshStandardMaterial({color:shrine.color,emissive:shrine.color,emissiveIntensity:done?2.5:.6}));crystal.position.set(shrine.x,1.65,shrine.z);world.add(crystal);light(shrine.x,2,shrine.z,shrine.color,done?14:5);addObj('seal',shrine.name+(done?'（解放済み）':''),shrine.x,shrine.z,shrine.id);if(!s.wins.includes(shrine.guardian)){const e=sprite('wolf',shrine.gx,shrine.gz,2.6);e.material.color.set(shrine.color);addObj('enemy',shrine.enemy,shrine.gx,shrine.gz,shrine.guardian).mesh=e}torch(shrine.x,6)}
 box(2,.8,16,1.3,1.5,.4,mats.stone);addObj('tablet','入口の石碑',2,16,'tablet');
 chest(-14,15,'forest');objects[objects.length-1].name=s.chests.includes('forest')?'空の宝箱':'西回廊の宝箱';chest(14,-5,'sanctum');objects[objects.length-1].name=s.chests.includes('sanctum')?'空の宝箱':'東の隠し宝箱';
 const spring=cyl(2,.65,-10.5,.8,1.3,new T.MeshStandardMaterial({color:'#9bffe0',emissive:'#53cfa9',emissiveIntensity:1.4}));addObj('spring','灯の泉',2,-10.5,'spring');light(2,1,-10.5,'#9bffe0',8);
 for(const x of [-4,4]){for(const z of [-13,-18]){cyl(x,height(x,z)+2,z,.5,4,mats.stone);box(x,height(x,z)+4,z,1.3,.4,1.3,mats.stone);torch(x,z+1)}}box(0,5.1,-18,9,.6,1.1,mats.stone);cyl(0,1.6,-16,3.6,.45,mats.stone,24);const altar=new T.Mesh(new T.TorusGeometry(2,.075,8,64),new T.MeshStandardMaterial({color:'#8df7e1',emissive:'#53dccc',emissiveIntensity:3}));altar.position.set(0,1.9,-16);altar.rotation.x=-Math.PI/2;world.add(altar);light(0,4,-16,'#60ffe0',22);
 const boss=sprite('boss',0,-16,5);if(s.quest<3&&open)addObj('boss','虚ろの灯守 ヴェルグ',0,-16,'boss').mesh=boss;else boss.visible=false;
 addObj('exit','琥珀の丘へ',0,21,'field');
 }
 // Tufts and wildflowers sit within the same lighting as the miniature architecture.
 const bladeMat=new T.MeshStandardMaterial({color:night?'#4c8770':'#a1b26b',side:T.DoubleSide});const bladeGeo=new T.PlaneGeometry(.1,.42);for(let i=0;i<650;i++){const x=rand(i+1000)*44-22,z=rand(i+2000)*44-22;if(s.area===2&&Math.abs(x)<16&&Math.abs(z)<20||Math.abs(x)<3||s.area===0&&Math.abs(x)<15&&z<15||Math.abs(x-(s.area===0?-6:s.area===1?-11:9))<3)continue;const a=new T.Mesh(bladeGeo,bladeMat);a.position.set(x,height(x,z)+.17,z);a.rotation.y=i;world.add(a);if(i%4===0)grass.push(a);if(i%8===0)box(x,height(x,z)+.35,z,.09,.09,.09,new T.MeshStandardMaterial({color:night?'#7fdfdd':'#ffe4ac',emissive:night?'#53a8a8':'#5a471c',emissiveIntensity:night?1:.1}),false)}
 const pos=new Float32Array(150*3);for(let i=0;i<150;i++){pos[i*3]=rand(i+58)*42-21;pos[i*3+1]=rand(i+922)*7+.4;pos[i*3+2]=rand(i+88)*42-21}const pg=new T.BufferGeometry();pg.setAttribute('position',new T.BufferAttribute(pos,3));particles=new T.Points(pg,new T.PointsMaterial({color:night?'#adfff0':'#ffe0a0',size:.065,transparent:true,opacity:.75,blending:T.AdditiveBlending,depthWrite:false}));world.add(particles);
 hero=sprite('hero',s.x,s.z,2.2);companion=sprite('mage',s.x+1,s.z+1,2.1);companion.visible=s.quest>0;camLook.set(s.x,1,s.z);camPos.set(s.x+15,21,s.z+24);camera.position.copy(camPos);camera.lookAt(camLook);renderUI()}
 function save(manual=false){try{localStorage.setItem('lumenfall-v1',JSON.stringify({...s,version:1}));if(manual)notify('冒険を記録しました')}catch{notify('保存できません。ブラウザの保存設定をご確認ください')}}
 function load(){try{const d=JSON.parse(localStorage.getItem('lumenfall-v1')||'null');if(!d||d.version!==1||![0,1,2].includes(d.area)||!Number.isFinite(d.hp)||!Number.isFinite(d.x)||!Number.isFinite(d.z)||!Array.isArray(d.wins)||!Array.isArray(d.chests))throw Error();s={...fresh(),...d};s.seals=Array.isArray(d.seals)?d.seals.filter((v:string)=>['west','east'].includes(v)):[];if(s.area===2&&(d.dungeonVersion!==1||!dungeonWalkable(s.x,s.z,s.seals,s.quest))){s.x=0;s.z=18}s.dungeonVersion=1;s.x=Math.max(-21,Math.min(21,s.x));s.z=Math.max(-21,Math.min(21,s.z));s.hp=Math.max(1,Math.min(maxHP(),s.hp));mode='explore';modal='';build();notify('記録した冒険を再開しました')}catch{notify('読み込める記録がありません')}}
 function notify(t:string){toast=t;toastUntil=clock+3;renderUI()}
 function talk(name:string,lines:string[],cb?:()=>void){speaker=name;dialogues=[...lines];afterDialogue=cb;modal='dialogue';target=null;renderUI()}
 function next(){if(modal!=='dialogue')return;dialogues.shift();if(!dialogues.length){modal='';const cb=afterDialogue;afterDialogue=undefined;cb?.()}renderUI()}
 function newGame(){s=fresh();mode='explore';modal='';build();talk('灯守のエダ',['水路の灯が、ひとつずつ消えている。森の「暁の種」が、眠ってしまったんだ。','リオ、灯を届けてくれるかい？ 星読みのミナが一緒に行くよ。北の道から琥珀の丘へお行き。','剣だけでは砕けない闇もある。ミナの星火と、癒しの光を頼るんだよ。'],()=>{s.quest=1;companion.visible=true;save();notify('ミナが同行した。北の森へ向かおう')})}
 function transition(area:number){s.area=area;s.x=0;s.z=area===0?-17:area===1?(s.z<0?18:-18):18;near=undefined;target=null;route=[];build();save();notify(areas[area][0]);if(area===2&&s.quest<3)talk('ミナ',['ここは星眠りの遺跡。奥の祭壇は、双灯の封印で閉ざされている。','左右の回廊を探索しよう。入口の石碑に、封印を解く手がかりがありそう。'])}
 function interact(o=near){if(!o||modal||mode!=='explore')return;target=null;route=[];tone(523,.08);if(o.kind==='elder'){talk('灯守のエダ',s.quest===3?['おかえり、リオ。水路に朝が戻ったね。あなたたちがつないだ灯を、私たちは守り続けるよ。']:['暁の種は、北の森の祭壇にある。丘の魔物で腕を磨いて、回復の準備を忘れずに。'])}
 if(o.kind==='tablet')talk('入口の石碑',['「西には、夜を照らす静かな円。東には、朝を告げる燃える円。」','「二つの番獣を鎮め、正しい紋章を祠に捧げよ。双灯がともるとき、祭壇への扉は開く。」']);
 if(o.kind==='seal'){const shrine=shrines.find(a=>a.id===o.id)!;if(s.seals.includes(o.id)){talk(shrine.name,['この祠の封印は解かれている。']);return}if(!s.wins.includes(shrine.guardian)){talk('ミナ',[shrine.enemy+'の気配が、祠を覆っている。先に回廊の番獣を鎮めよう。']);return}modal='seal-'+o.id;renderUI()}
 if(o.kind==='gate')talk('双灯の扉',gateOpen(s.seals,s.quest)?['二つの灯がともり、祭壇への道が開いている。奥の灯の泉で休んでから進もう。']:['扉は固く閉ざされている。左右の回廊にある二つの祠の封印を解除しよう。','解放した祠：'+s.seals.length+' / 2']);
 if(o.kind==='spring'){if(s.springUsed){talk('灯の泉',['泉の灯は、静かに眠っている。']);return}s.hp=maxHP();s.mp=maxMP();s.springUsed=true;save();talk('灯の泉',['あたたかな光がふたりを包んだ。HP・MPが全回復した！'])}
 if(o.kind==='shop'){modal='shop';renderUI()}if(o.kind==='inn'){modal='inn';renderUI()}if(o.kind==='traveler')talk('旅の薬師',['この先は星眠りの遺跡。左右の回廊で二つの封印を解かなければ、祭壇には進めない。','「身を守る」でしのげば、傷は小さくなるよ。星火に弱いという噂もある。']);
 if(o.kind==='chest'){if(s.chests.includes(o.id)){notify('宝箱は空っぽだ');return}s.chests.push(o.id);s.gold+=25;s.potions+=2;if(o.id==='forest')s.ethers+=2;o.name='空の宝箱';save();talk('宝箱',['25 G と 薬草 ×2 を手に入れた！'+(o.id==='forest'?' 星の雫 ×2 も入っていた。':'')])}
 if(o.kind==='exit'){if(s.quest===0){talk('ミナ',['出発する前に、町の灯守エダに話を聞こう。']);return}transition(o.id==='town'?0:o.id==='field'?1:2)}
 if(o.kind==='boss'&&!gateOpen(s.seals,s.quest)){notify('先に二つの封印を解除しよう');return}if(o.kind==='enemy'||o.kind==='boss')startBattle(o)}
 function tone(freq:number,duration=.2,type:OscillatorType='sine',vol=.045){if(muted||!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(vol,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+duration)}
 function activateAudio(){if(!audio){audio=new AudioContext()}if(audio.state==='suspended')audio.resume()}
 function burst(x:number,y:number,z:number,color:string,count=100){const p=new Float32Array(count*3),v=[];for(let i=0;i<count;i++){p[i*3]=x;p[i*3+1]=y;p[i*3+2]=z;v.push(new T.Vector3((Math.random()-.5)*10,Math.random()*7,(Math.random()-.5)*10))}const g=new T.BufferGeometry();g.setAttribute('position',new T.BufferAttribute(p,3));const f=new T.Points(g,new T.PointsMaterial({color,size:.12,blending:T.AdditiveBlending,transparent:true,depthWrite:false}));f.userData={v,life:1.3};world.add(f);fx.push(f)}
 function damageText(t:string,healing=false){const e=document.createElement('div');e.className='damage';e.textContent=t;if(healing){e.style.left='30%';e.style.color='#acffdc'}document.getElementById('floaters')!.append(e);later(()=>e.remove(),1100)}
 function impact(magic=false){shake=magic?.42:.2;hitstop=.09;flash.color.set(magic?'#8bf5ff':'#ffd1a0');flash.intensity=magic?65:25;fade.style.background=magic?'#b8fff6':'#ffe4b8';fade.style.opacity=magic?'.22':'.1';later(()=>fade.style.opacity='0',110);tone(magic?880:130,.3,magic?'sine':'triangle',.08)}
 function startBattle(o:Obj){const boss=o.kind==='boss';mode='battle';busy=true;near=undefined;battle={id:o.id,boss,name:o.name,hp:boss?245:o.id==='slime'?42:o.id.startsWith('sentinel')?78:60,max:boss?245:o.id==='slime'?42:o.id.startsWith('sentinel')?78:60,turn:0,charge:false,phase:1,origin:{x:s.x,z:s.z},obj:o};hero.position.set(s.x-2,height(s.x,s.z),s.z+1);companion.position.set(s.x-3,height(s.x,s.z),s.z+3);enemySprite=o.mesh as T.Sprite;enemySprite.position.set(s.x+3,height(s.x,s.z),s.z-2);battleLog=boss?'祭壇の灯が脈打つ。虚ろの灯守が目覚めた。':'魔物が行く手をふさいだ！';if(boss){bloom.strength=1.1;burst(enemySprite.position.x,3,enemySprite.position.z,'#79ffee',160);impact(true)}renderUI();later(()=>{busy=false;battleLog='リオたちは どうする？';renderUI()},1500)}
 function command(cmd:string){if(mode!=='battle'||busy)return;if(cmd==='fire'&&s.mp<6||cmd==='heal'&&s.mp<5||cmd==='potion'&&s.potions<=0||cmd==='ether'&&s.ethers<=0)return;busy=true;const e=enemySprite!;let dmg=0,guard=false;battle.turn++;if(cmd==='attack'){dmg=17+s.lv*4+(s.sword?9:0);battleLog='リオの攻撃！';anim=1;later(()=>{impact();burst(e.position.x,1.8,e.position.z,'#ffe2a0',50)},350)}if(cmd==='fire'){s.mp-=6;dmg=33+s.lv*6+(battle.boss?9:0);battleLog='ミナは 星火 を唱えた！';flash.color.set('#63cfff');flash.intensity=30;anim=2;burst(hero.position.x,2,hero.position.z,'#87eaff',75);later(()=>{impact(true);burst(e.position.x,2.5,e.position.z,'#80eaff',160)},650)}if(cmd==='heal'){s.mp-=5;const heal=Math.min(maxHP()-s.hp,58);s.hp+=heal;battleLog='ミナの 灯の癒し。HPが回復した！';burst(hero.position.x,1,hero.position.z,'#b1ffd4',65);damageText('+'+heal,true);tone(660,.7)}if(cmd==='potion'){s.potions--;const heal=Math.min(maxHP()-s.hp,65);s.hp+=heal;battleLog='薬草を使った。HPが回復した！';damageText('+'+heal,true)}if(cmd==='ether'){s.ethers--;s.mp=Math.min(maxMP(),s.mp+20);battleLog='星の雫を使った。MPが20回復した！';tone(740,.4)}if(cmd==='guard'){guard=true;battleLog='リオたちは 身を守っている。'}renderUI();later(()=>{if(dmg){battle.hp=Math.max(0,battle.hp-dmg);damageText(String(dmg));renderUI()}},cmd==='fire'?700:400);
 later(()=>{anim=0;if(battle.hp<=0){victory();return}if(battle.boss&&battle.hp<=battle.max*.5&&battle.phase===1){battle.phase=2;scene.fog=new T.FogExp2('#43304f',.037);sun.color.set('#ba91ec');bloom.strength=1.35;battleLog='灯守の核が露わになった。森が紫の炎に包まれる！';impact(true);burst(e.position.x,3,e.position.z,'#d48cff',180);renderUI();later(()=>enemyTurn(guard),1300)}else enemyTurn(guard)},1500)}
 function enemyTurn(guard:boolean){if(!battle)return;if(battle.boss&&!battle.charge&&battle.turn%3===1){battle.charge=true;battleLog='ヴェルグが光を集めている… 次の一撃に備えよう！';flash.color.set('#e5a3ff');flash.intensity=25;burst(enemySprite!.position.x,2,enemySprite!.position.z,'#c892ff',70);tone(160,.8,'triangle');busy=false;renderUI();return}const charged=battle.charge;let dmg=battle.boss?(charged?43:battle.phase===2?23:18):battle.id==='slime'?9:14;dmg=Math.max(1,dmg-(s.armor?5:0));if(guard)dmg=Math.ceil(dmg*.25);battle.charge=false;s.hp=Math.max(0,s.hp-dmg);battleLog=(charged?'ヴェルグの 月蝕の奔流！':battle.name+'の攻撃！')+' '+dmg+' ダメージ'+(guard?'（防御）':'');damageText('-'+dmg,true);impact(charged);burst(hero.position.x,1.5,hero.position.z,charged?'#c491ff':'#ffdba1',charged?130:40);renderUI();later(()=>{if(s.hp<=0){mode='explore';battle=null;modal='';s.hp=maxHP();s.mp=maxMP();s.area=0;s.x=-10;s.z=5;s.gold=Math.max(0,s.gold-10);build();talk('宿の主人',['大丈夫、ここは水鳥亭。旅人が運んできてくれたんだ。','治療代は10 G。装備を整えて、もう一度挑んでごらん。']);save()}else{busy=false;battleLog='リオたちは どうする？';renderUI()}},1000)}
 function victory(){const boss=battle.boss,id=battle.id;const xp=boss?100:id==='slime'?24:36,gold=boss?80:25;s.xp+=xp;s.gold+=gold;if(!s.wins.includes(id))s.wins.push(id);let leveled=false;while(s.xp>=s.lv*30){s.xp-=s.lv*30;s.lv++;leveled=true}s.hp=leveled?maxHP():s.hp;s.mp=leveled?maxMP():s.mp;battleLog='勝利！ '+xp+' EXP / '+gold+' G'+(leveled?'　レベルアップ！ HP・MP全回復':'');enemySprite!.visible=false;burst(enemySprite!.position.x,2,enemySprite!.position.z,'#ffe2a2',150);tone(523,.2);later(()=>tone(659,.25),200);later(()=>tone(784,.7),400);renderUI();later(()=>{mode='explore';battle=null;bloom.strength=.65;build();if(boss){s.quest=3;save();talk('ミナ',['見て。あの人は、灯を守ろうとして闇を抱え込んでいたんだね。','暁の種が、あたたかい。帰ろう、リオ。みんなの灯が待ってる。'],()=>{s.area=0;s.x=0;s.z=8;build();sun.color.set('#ffe8bc');sun.intensity=4;scene.fog=new T.FogExp2('#c5c6b0',.018);mode='ending';save();renderUI()})}else{save();notify(leveled?'レベル '+s.lv+' になった！':'道が開けた。先へ進もう')}},1900)}
 function party(){return `<div class="party"><small>Lv. ${s.lv}</small><b>リオ <span style="font-size:11px;color:#bbc9cb">& ミナ</span></b><div class="stat"><span>HP</span><div class="bar"><i style="width:${s.hp/maxHP()*100}%"></i></div><span>${s.hp}/${maxHP()}</span></div><div class="stat"><span>MP</span><div class="bar mp"><i style="width:${s.mp/maxMP()*100}%"></i></div><span>${s.mp}/${maxMP()}</span></div></div>`}
 function btn(id:string,t:string,disabled=false){return `<button data-action="${id}" ${disabled?'disabled':''}>${t}</button>`}
 function renderUI(){const goal=nextGoal();let h='<div class="vignette"></div>';if(mode==='title'){let has=false;try{has=!!localStorage.getItem('lumenfall-v1')}catch{}h+=`<div class="title"><div class="eyebrow">A TALE OF THE LAST LIGHT</div><h1>灯の継承者</h1><div class="subtitle">L U M E N F A L L</div><p>消えゆく灯。小さな約束。<br>夜明けをつなぐ、ふたりの旅。</p>${btn('new','はじめから　 →')}${has?btn('load','つづきから'):''}</div><div class="corner">A SHORT FANTASY · 約15分の冒険</div>`}
 else if(mode==='ending'){h+=`<div class="overlay"><div class="panel ending"><div class="eyebrow">THE LIGHT WILL LIVE ON</div><h1>そして、灯はつづく</h1><div class="sep"></div><p>朝の光が、水路を金色に染めた。<br>名もなき小さな勇気が、<br>今日も誰かの窓に灯をともす。</p><p>リオとミナの旅は、ここでひと休み。<br>けれど、世界にはまだ多くの夜がある。</p><div class="badge">THE END</div><p style="font-size:12px">到達レベル ${s.lv} · 討伐 ${s.wins.length} · 宝箱 ${s.chests.length}/4</p>${btn('after','灯の戻った町へ')}</div></div>`}
 else if(mode==='battle'){h+=`<div class="battle"><div class="battlehead"><div class="eyebrow">${battle.boss?'GUARDIAN OF THE HOLLOW LIGHT':'ENCOUNTER'}</div><h2>${battle.name}</h2><div class="enemybar"><i style="width:${battle.hp/battle.max*100}%"></i></div><p style="font:11px Arial;color:#ddd4c2">${battle.hp} / ${battle.max}${battle.charge?'　 ⚠ 次の攻撃に備えよう':''}</p></div><div class="bottom">${party()}</div><div class="battlelog">${battleLog}</div><div class="commands">${btn('attack','剣で攻撃<small>SWORD</small>',busy)}${btn('fire','星火<small>MP 6 · 光の攻撃</small>',busy||s.mp<6)}${btn('heal','灯の癒し<small>MP 5 · HP回復</small>',busy||s.mp<5)}${btn('guard','身を守る<small>被ダメージを軽減</small>',busy)}${btn('potion',`薬草 ×${s.potions}<small>HP +65</small>`,busy||!s.potions)}${btn('ether',`星の雫 ×${s.ethers}<small>MP +20</small>`,busy||!s.ethers)}</div></div>`}
 else {h+=`<div class="top"><div class="region"><small>${areas[s.area][1]}</small><h2>${areas[s.area][0]}</h2><p>${areas[s.area][2]} · ${s.area===2?'月夜':Math.sin(clock*.015)>.6?'夕暮れ':'午後'}</p></div><div class="tools"><button class="iconbtn" data-action="sound" aria-label="音の切り替え">${muted?'♪̸':'♪'}</button><button class="iconbtn" data-action="map" aria-label="周辺の案内">⌖</button><button class="iconbtn" data-action="menu" aria-label="冒険メニュー">☰</button></div></div><div class="quest"><small>${s.quest===3?'旅の記憶':'次の目的地'}</small><div class="journey"><span class="${s.area===0?'current':''}">町</span> › <span class="${s.area===1?'current':''}">草原</span> › <span class="${s.area===2?'current':''}">遺跡</span> › 祭壇</div>${s.quest===0?'灯守のエダに話を聞こう':s.quest===3?'町に灯が戻った。自由に散策しよう':s.area===0?'北の道から、琥珀の丘へ':s.area===1?'街道を北へ進み、星眠りの遺跡へ':(gateOpen(s.seals,s.quest)?'双灯の扉が開いた。奥の祭壇へ':'左右の回廊を探索し、祠の封印を解く（'+s.seals.length+'/2）')}${goal?`<button class="guide" data-action="guide">${Math.hypot(goal.x-s.x,goal.z-s.z)<goal.r?'ここから進む · ':'⌖ '}${s.area===0?'北門 → 琥珀の丘':s.area===1?'森の入口 → 星眠りの遺跡':goal.name}${Math.hypot(goal.x-s.x,goal.z-s.z)<goal.r?'':'まで案内'}</button>`:''}</div><div class="bottom">${party()}<div class="help">WASD / 矢印キー · 移動　 E / Space · 調べる<br>地面をクリック · 移動　 Esc · メニュー</div></div>${near&&!modal?`<button class="interact" data-action="interact"><em>E</em>${near.name}</button>`:''}<div class="joystick" id="joystick" aria-label="移動スティック"><i></i></div>`}
 if(modal==='dialogue')h+=`<div class="dialogue"><b>${speaker}</b><p>${dialogues[0]}</p>${btn('next',dialogues.length>1?'つづける　 ▸':'閉じる　 ▸')}<div style="clear:both"></div></div>`;
 if(modal==='menu')h+=`<div class="overlay"><div class="panel"><div class="eyebrow">TRAVEL JOURNAL</div><h2>冒険の記録</h2><p>リオとミナ　Lv. ${s.lv}　 /　${s.gold} G<br>経験値 ${s.xp} / ${s.lv*30}<br>武器：${s.sword?'暁鉄の剣（攻撃 +9）':'旅立ちの剣'}<br>防具：${s.armor?'織星の外套（被ダメージ −5）':'旅人の服'}</p>${btn('usepotion',`薬草を使う ×${s.potions}　 HP +65`,!s.potions||s.hp===maxHP())}${btn('useether',`星の雫を使う ×${s.ethers}　 MP +20`,!s.ethers||s.mp===maxMP())}${btn('save','冒険を記録する')}${btn('load','記録から再開する')}${btn('controls','操作方法')}${btn('close','旅に戻る')}</div></div>`;
 if(modal.startsWith('seal-')){const shrine=shrines.find(a=>a.id===modal.slice(5))!;h+=`<div class="overlay"><div class="panel"><div class="eyebrow">SEAL OF THE TWIN LIGHTS</div><h2>${shrine.name}</h2><p>番獣の気配は消えた。<br>台座に捧げる紋章を選ぼう。<br><br>石碑の言葉：<br>「西には、夜を照らす静かな円。<br>東には、朝を告げる燃える円。」</p>${btn('glyph-moon','月の紋章')}${btn('glyph-sun','太陽の紋章')}${btn('glyph-star','星の紋章')}${btn('close','あとで考える')}</div></div>`}
 if(modal==='map')h+=`<div class="overlay"><div class="panel"><div class="eyebrow">NEARBY</div><h2>周辺の案内</h2><p>目的地を選ぶと、歩いて向かいます。</p>${objects.filter(o=>(o.kind!=='chest'||!s.chests.includes(o.id))&&(o.kind!=='spring'||gateOpen(s.seals,s.quest))).map(o=>btn('walk-'+o.id,o.name)).join('')}${btn('close','戻る')}</div></div>`;
 if(modal==='shop')h+=`<div class="overlay"><div class="panel"><div class="eyebrow">LYUNE TRADING POST</div><h2>旅支度の店</h2><p>「小さな備えが、旅を助けるよ。」<br>所持金：${s.gold} G</p>${btn('buy-potion','薬草　15 G　／ HP +65',s.gold<15)}${btn('buy-ether','星の雫　20 G　／ MP +20',s.gold<20)}${btn('buy-sword',s.sword?'暁鉄の剣　装備中':'暁鉄の剣　40 G　／ 攻撃 +9',s.sword||s.gold<40)}${btn('buy-armor',s.armor?'織星の外套　装備中':'織星の外套　35 G　／ 被ダメージ −5',s.armor||s.gold<35)}${btn('close','店を出る')}</div></div>`;
 if(modal==='inn')h+=`<div class="overlay"><div class="panel"><div class="eyebrow">THE WATERBIRD INN</div><h2>水鳥亭</h2><p>「今夜は、窓の灯を消さずにおくよ。」<br>一泊 10 G。HP・MPをすべて回復します。<br>所持金：${s.gold} G</p>${btn('rest',s.gold>=10?'ひと休みする　10 G':'ひと休みする（今回は無料）')}${btn('close','宿を出る')}</div></div>`;
 if(modal==='controls')h+=`<div class="overlay"><div class="panel"><h2>旅の手引き</h2><p>移動：WASD / 矢印キー。地面のクリック・タップでも移動できます。スマホでは左下のスティックを使えます。<br><br>会話・宝箱・出入口：近づいて E / Space、または表示されたボタン。<br><br>戦闘はコマンド選択式。敵が力をためたら「身を守る」。HPが減ったら薬草や癒しの魔法を。<br><br>エリア移動・勝利・買い物時に自動保存。メニューから手動でも保存できます。記録はこのブラウザに保存されます。</p>${btn('close','戻る')}</div></div>`;
 if(toast&&clock<toastUntil)h+=`<div class="toast">${toast}</div>`;const oldJoy=ui.querySelector('#joystick');
 // Keep the captured node connected while nearby prompts and toasts change.
 if(oldJoy&&releaseJoystick&&mode==='explore'&&!modal){const template=document.createElement('template');template.innerHTML=h;template.content.querySelector('#joystick')?.remove();for(const child of [...ui.childNodes])if(child!==oldJoy)child.remove();ui.append(template.content)}
 else{releaseJoystick?.();releaseJoystick=undefined;ui.innerHTML=h;const joystick=ui.querySelector('#joystick') as HTMLElement|null;if(joystick&&mode==='explore'&&!modal)releaseJoystick=bindJoystick(joystick,(x,y)=>{joy={x,y};target=null;route=[]});else joy={x:0,y:0}}}

 function action(e:MouseEvent){const b=(e.target as HTMLElement).closest('[data-action]') as HTMLButtonElement;if(!b||b.disabled)return;activateAudio();const a=b.dataset.action!;if(mode==='battle'){command(a);return}tone(440,.04);if(a.startsWith('glyph-')&&modal.startsWith('seal-')){const shrine=shrines.find(v=>v.id===modal.slice(5))!;if(a.slice(6)!==shrine.answer){notify('紋章が淡く揺れた。石碑の言葉を思い出そう。');return}s.seals.push(shrine.id);modal='';build();save();burst(shrine.x,2,shrine.z,shrine.color,100);talk('ミナ',gateOpen(s.seals,s.quest)?['二つの灯がつながった！ 双灯の扉が開いたよ。','奥に回復の泉がある。準備を整えて、祭壇へ進もう。']:[shrine.name+'の封印が解けた。もう一方の回廊へ行こう。']);renderUI();return}if(a==='guide'){const goal=nextGoal();if(goal){if(Math.hypot(goal.x-s.x,goal.z-s.z)<goal.r)interact(goal);else{navigate(goal.x,goal.z);notify('目的地まで歩いて案内します')}}}if(a==='new')newGame();if(a==='load')load();if(a==='next')next();if(a==='interact')interact();if(a==='menu'){modal=modal?'':'menu';target=null}if(a==='close')modal='';if(a==='controls')modal='controls';if(a==='map')modal='map';if(a.startsWith('walk-')){const o=objects.find(o=>o.id===a.slice(5));modal='';if(o)navigate(o.x,o.z)}if(a==='sound')muted=!muted;if(a==='save')save(true);if(a==='after'){mode='explore';modal='';save()}if(a==='usepotion'&&s.potions){s.potions--;s.hp=Math.min(maxHP(),s.hp+65);save()}if(a==='useether'&&s.ethers){s.ethers--;s.mp=Math.min(maxMP(),s.mp+20);save()}if(a.startsWith('buy-')){const item=a.slice(4),cost=item==='potion'?15:item==='ether'?20:item==='sword'?40:35;if(s.gold>=cost){s.gold-=cost;if(item==='potion')s.potions++;if(item==='ether')s.ethers++;if(item==='sword')s.sword=true;if(item==='armor')s.armor=true;save();notify(item==='sword'||item==='armor'?'購入して装備した':'購入した')}}if(a==='rest'){s.gold=Math.max(0,s.gold-10);s.hp=maxHP();s.mp=maxMP();modal='';save();talk('宿の主人',['ゆっくり休めたかい？ HP・MPが全回復したよ。いってらっしゃい。'])}renderUI()}
 ui.addEventListener('click',action);
 const down=(e:KeyboardEvent)=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' ','Tab'].includes(e.key)&&e.key!=='Tab')e.preventDefault();keys.add(e.key.toLowerCase());if(e.repeat)return;activateAudio();if(e.key==='Escape'&&mode==='explore'){if(modal==='dialogue')next();else{modal=modal?'':'menu';renderUI()}}if(['e','E',' ','Enter'].includes(e.key)){if(modal==='dialogue')next();else if(mode==='explore'&&!modal)interact()}};const up=(e:KeyboardEvent)=>keys.delete(e.key.toLowerCase());const blur=()=>{keys.clear();joy={x:0,y:0};target=null;route=[]};window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);
 const ray=new T.Raycaster(),plane=new T.Plane(new T.Vector3(0,1,0),0);const point=(e:PointerEvent)=>{if(mode!=='explore'||modal)return;const v=new T.Vector2(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1);ray.setFromCamera(v,camera);const p=new T.Vector3();if(ray.ray.intersectPlane(plane,p)){navigate(T.MathUtils.clamp(p.x,-21,21),T.MathUtils.clamp(p.z,-21,21))}};canvas.addEventListener('pointerdown',point);
 function resize(){renderer.setSize(innerWidth,innerHeight);composer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();tilt.uniforms.resolution.value.set(innerWidth*renderer.getPixelRatio(),innerHeight*renderer.getPixelRatio())}window.addEventListener('resize',resize);resize();build();document.getElementById('loading')?.remove();
 function navigate(x:number,z:number){const step=.75;const start=[Math.round(s.x/step),Math.round(s.z/step)];const queue=[start],seen=new Set([start.join(',')]),prev=new Map<string,string>();let goal='';for(let n=0;n<queue.length&&n<5000;n++){const [a,b]=queue[n];if(Math.hypot(a*step-x,b*step-z)<1.2){goal=[a,b].join(',');break}for(const [da,db] of [[0,1],[0,-1],[1,0],[-1,0]]){const aa=a+da,bb=b+db,k=[aa,bb].join(',');if(!seen.has(k)&&canMove(aa*step,bb*step)){seen.add(k);prev.set(k,[a,b].join(','));queue.push([aa,bb])}}}if(goal){const points=[];while(prev.has(goal)){const [a,b]=goal.split(',').map(Number);points.push(new T.Vector3(a*step,0,b*step));goal=prev.get(goal)!}route=points.reverse();target=route.shift()??null}else notify('そこへは歩いて行けないようだ')}
 function canMove(x:number,z:number){return x>-22&&x<22&&z>-22&&z<22&&(s.area!==2||dungeonWalkable(x,z,s.seals,s.quest))&&!blocks.some(b=>Math.abs(x-b.x)<b.w/2+.23&&Math.abs(z-b.z)<b.d/2+.23)}
 function frame(now:number){if(dead)return;raf=software?window.setTimeout(()=>frame(performance.now()),33):requestAnimationFrame(frame);let dt=Math.min((now-last)/1000,.045);last=now;clock+=dt;s.time+=dt;shake*=.88;hitstop=Math.max(0,hitstop-dt);flash.intensity*=.93;if(toast&&clock>toastUntil){toast='';renderUI()}
 if(audio&&!muted&&clock>nextNote){nextNote=clock+(mode==='battle'?.4:1.1);const notes=mode==='battle'?[146.83,220,293.66,349.23,440]:s.area===2?[196,293.66,392,440,587.33]:[220,329.63,440,493.88,659.25];tone(notes[Math.floor(clock*1.1)%notes.length],1.8,'sine',.016)}
 const pp=particles.geometry.attributes.position;for(let i=0;i<pp.count;i++){pp.setY(i,pp.getY(i)+dt*.13);pp.setX(i,pp.getX(i)+Math.sin(clock*.3+i)*dt*.04);if(pp.getY(i)>8)pp.setY(i,.3)}pp.needsUpdate=true;for(const f of flames){f.scale.y=1.05+Math.sin(clock*13+f.position.x)*.18;f.position.x+=Math.sin(clock*10+f.position.z)*.0009}for(const g of grass)g.rotation.z=Math.sin(clock*2+g.position.x)*.12;for(const w of waters){const p=w.geometry.attributes.position;for(let i=0;i<p.count;i++)p.setZ(i,Math.sin(p.getX(i)*3+clock*1.6+p.getY(i))*.025);p.needsUpdate=true;w.geometry.computeVertexNormals()}
 for(const f of [...fx]){f.userData.life-=dt;const p=f.geometry.attributes.position;for(let i=0;i<p.count;i++){const v=f.userData.v[i];p.setXYZ(i,p.getX(i)+v.x*dt,p.getY(i)+v.y*dt,p.getZ(i)+v.z*dt);v.y-=dt*5}p.needsUpdate=true;(f.material as T.PointsMaterial).opacity=Math.max(0,f.userData.life/1.3);if(f.userData.life<=0){world.remove(f);f.geometry.dispose();(f.material as T.Material).dispose();fx.splice(fx.indexOf(f),1)}}
 if(mode==='explore'&&!modal){let dx=0,dz=0;const sx=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0)+joy.x,sy=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0)+joy.y;if(sx||sy){target=null;route=[];dx=sx*.85+sy*.53;dz=-sx*.53+sy*.85}else if(target){dx=target.x-s.x;dz=target.z-s.z;if(Math.hypot(dx,dz)<.18){target=route.shift()??null;dx=dz=0}}const l=Math.hypot(dx,dz);if(l>.01){dx/=l;dz/=l;const nx=s.x+dx*dt*5,nz=s.z+dz*dt*5;let moved=false;if(canMove(nx,s.z)){s.x=nx;moved=true}if(canMove(s.x,nz)){s.z=nz;moved=true}if(!moved)target=null;hero.material.rotation=Math.sin(clock*15)*.035;hero.position.y=height(s.x,s.z)+Math.abs(Math.sin(clock*12))*.07;hero.material.map!.repeat.x=1;hero.material.map!.offset.x=0}else{hero.material.rotation=0;hero.position.y=height(s.x,s.z)+.06}hero.position.x=s.x;hero.position.z=s.z;const n=objects.filter(o=>Math.hypot(o.x-s.x,o.z-s.z)<o.r).sort((a,b)=>Math.hypot(a.x-s.x,a.z-s.z)-Math.hypot(b.x-s.x,b.z-s.z))[0];if(n!==near){near=n;renderUI()}}
 if(mode!=='battle'){companion.position.lerp(new T.Vector3(s.x+1,height(s.x+1,s.z+1)+.06,s.z+1),dt*4);if(mode==='title'){camLook.set(-1,1,0);camPos.set(22+Math.sin(clock*.05)*3,24,31)}else{camLook.set(s.x,1,s.z-1);const mobile=innerWidth<600;camPos.set(s.x+(mobile?19:15),mobile?27:21,s.z+(mobile?30:24))}if(s.area!==2){const t=.5+.5*Math.sin(clock*.015);sun.color.setHSL(.105-t*.045,.52,.8);sun.intensity=3.8-t*1.3;sun.position.x=-18+Math.sin(clock*.012)*10}}
 else{const h=hero.position,e=enemySprite!.position,mobile=innerWidth<600;const orbit=clock*(battle.boss?.24:.12);camLook.set((h.x+e.x)/2,1.5,(h.z+e.z)/2);const radius=mobile?(battle.boss?35:29):17;camPos.set(camLook.x+Math.sin(orbit)*3+6,anim===2?9:12,camLook.z+radius-(anim?3:0));if(battle.boss){enemySprite!.position.y=height(s.x,s.z)+Math.sin(clock*2)*.15;enemySprite!.material.color.set(battle.phase===2?'#e0bdff':'#d7fffa')}}
 camera.position.lerp(camPos,dt*(mode==='battle'?2.3:3));const look=new T.Vector3();look.copy(camLook);if(shake){camera.position.x+=(Math.random()-.5)*shake;camera.position.y+=(Math.random()-.5)*shake}camera.lookAt(look);for(const sp of [hero,companion]){const sh=sp.userData.shadow;sh.position.set(sp.position.x,height(sp.position.x,sp.position.z)+.025,sp.position.z)}if(hitstop<=0)composer.render()}
 raf=software?window.setTimeout(()=>frame(performance.now()),33):requestAnimationFrame(frame);return()=>{dead=true;releaseJoystick?.();cancelAnimationFrame(raf);clearTimeout(raf);timers.forEach(clearTimeout);window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur);window.removeEventListener('resize',resize);canvas.removeEventListener('pointerdown',point);ui.removeEventListener('click',action);audio?.close();disposeWorld();spriteCache.forEach(t=>t.dispose());composer.dispose();renderer.dispose()}
}
