import * as T from 'three';
// Compatibility renderer for browsers without a GPU context. Uses the same 3D scene and camera.
export class SoftwareRenderer {
 shadowMap={enabled:false,type:0};toneMapping=0;toneMappingExposure=1;ratio=1;ctx:CanvasRenderingContext2D;
 constructor(public canvas:HTMLCanvasElement){this.ctx=canvas.getContext('2d')!}
 setPixelRatio(_:number){this.ratio=1}getPixelRatio(){return 1}setSize(w:number,h:number){this.canvas.width=Math.floor(w*.65);this.canvas.height=Math.floor(h*.65)}dispose(){}
 render(scene:T.Scene,camera:T.Camera){const c=this.ctx,w=this.canvas.width,h=this.canvas.height;if(!c)return;scene.updateMatrixWorld();camera.updateMatrixWorld();const vp=new T.Matrix4().multiplyMatrices(camera.projectionMatrix,camera.matrixWorldInverse),v=new T.Vector3();const faces:any[]=[];c.fillStyle='#71919b';c.fillRect(0,0,w,h);const sun=new T.Vector3(-.5,1,.3).normalize();const fog=scene.fog?.color??new T.Color('#8ca1a6');
 scene.traverse(o=>{if(!o.visible||!o.parent?.visible)return;if(o instanceof T.Sprite){const p=o.position.clone().applyMatrix4(vp);if(p.z>1)return;const tex=o.material.map?.image;if(!tex)return;const p2=o.position.clone().add(new T.Vector3(0,o.scale.y,0)).applyMatrix4(vp);const sh=Math.abs(p2.y-p.y)*h/2*1.15;faces.push({z:p.z,sprite:tex,x:(p.x+1)*w/2,y:(1-p.y)*h/2,sh,sw:sh*o.scale.x/o.scale.y});return}if(!(o instanceof T.Mesh)||o instanceof T.Points)return;const g=o.geometry,attr=g.attributes.position;if(!attr)return;const material=Array.isArray(o.material)?o.material[0]:o.material;if(material.opacity===0)return;const transform=new T.Matrix4().multiplyMatrices(vp,o.matrixWorld);const verts=[];for(let i=0;i<attr.count;i++){v.fromBufferAttribute(attr,i).applyMatrix4(transform);verts.push([v.x*w/2+w/2,-v.y*h/2+h/2,v.z])}const index=g.index;const total=index?index.count:attr.count;const color=(material as any).color??new T.Color('#5e9599');const normal=new T.Vector3();for(let i=0;i<total;i+=3){const ia=index?index.getX(i):i,ib=index?index.getX(i+1):i+1,ic=index?index.getX(i+2):i+2;const a=verts[ia],b=verts[ib],d=verts[ic];if(a[2]>1||b[2]>1||d[2]>1||a[2]<-1)continue;if(Math.max(a[0],b[0],d[0])<0||Math.min(a[0],b[0],d[0])>w||Math.max(a[1],b[1],d[1])<0||Math.min(a[1],b[1],d[1])>h)continue;if((b[0]-a[0])*(d[1]-a[1])-(b[1]-a[1])*(d[0]-a[0])>0&&material.side!==T.DoubleSide)continue;const n=g.attributes.normal;if(n)normal.fromBufferAttribute(n,ia).transformDirection(o.matrixWorld);else normal.set(0,1,0);const col=color.clone().multiplyScalar((.63+Math.max(0,normal.dot(sun))*.55)*(scene.userData.fillLift??1));const em=(material as any).emissive;if(em)col.add(em.clone().multiplyScalar(Math.min((material as any).emissiveIntensity??0,.4)));const z=(a[2]+b[2]+d[2])/3;col.lerp(fog,Math.max(0,(z-.996)*90));faces.push({z,a,b,d,color:'#'+col.getHexString(),opacity:material.transparent?material.opacity:1})}});
 const frame=c.createImageData(w,h),pixels=frame.data,depth=new Float32Array(w*h);depth.fill(2);for(let k=0;k<w*h;k++){pixels[k*4]=77;pixels[k*4+1]=103;pixels[k*4+2]=118;pixels[k*4+3]=255}
 for(const f of faces){if(f.sprite)continue;const [a,b,d]=[f.a,f.b,f.d],den=(b[1]-d[1])*(a[0]-d[0])+(d[0]-b[0])*(a[1]-d[1]);if(Math.abs(den)<.01)continue;const minX=Math.max(0,Math.floor(Math.min(a[0],b[0],d[0]))),maxX=Math.min(w-1,Math.ceil(Math.max(a[0],b[0],d[0]))),minY=Math.max(0,Math.floor(Math.min(a[1],b[1],d[1]))),maxY=Math.min(h-1,Math.ceil(Math.max(a[1],b[1],d[1])));const rgb=parseInt(f.color.slice(1),16),r=rgb>>16,g=rgb>>8&255,blue=rgb&255;for(let y=minY;y<=maxY;y++)for(let x=minX;x<=maxX;x++){const u=((b[1]-d[1])*(x-d[0])+(d[0]-b[0])*(y-d[1]))/den,vv=((d[1]-a[1])*(x-d[0])+(a[0]-d[0])*(y-d[1]))/den,t=1-u-vv;if(u<-.001||vv<-.001||t<-.001)continue;const z=u*a[2]+vv*b[2]+t*d[2],idx=y*w+x;if(z>=depth[idx])continue;depth[idx]=z;const k=idx*4;pixels[k]=r;pixels[k+1]=g;pixels[k+2]=blue}}
 c.putImageData(frame,0,0);faces.filter(f=>f.sprite).sort((a,b)=>b.z-a.z).forEach(f=>{c.imageSmoothingEnabled=false;c.drawImage(f.sprite,f.x-f.sw/2,f.y-f.sh,f.sw,f.sh)});c.globalAlpha=1;const grad=c.createLinearGradient(0,0,0,h);grad.addColorStop(0,'#07132355');grad.addColorStop(.35,'#07132300');grad.addColorStop(.7,'#07132300');grad.addColorStop(1,'#07132366');c.fillStyle=grad;c.fillRect(0,0,w,h)
 }
}
