import type {ChapterContext,WorldObject} from '../chapters/types.ts';
import {progress} from '../systems/progression.ts';
import {gear} from '../systems/gear.ts';
import {cases,caseById} from './catalog.ts';
import {migrateInvestigations,startCase,scan,ready} from './state.ts';
import {claim} from './rewards.ts';
export function open(c:ChapterContext){const n=migrateInvestigations(c.state);if(!n.introduced){n.introduced=true;c.save();c.talk('ラウとミナ',['ラウ「環海の流れを戻してから、別の土地でも妙な反応が出ている。灯は離れていても、どこかでつながっているらしい」','ミナ「じゃあ、環海だけ直して終わりじゃないってこと？」','ラウ「そういうことだ。三つの痕跡を調べれば、流れを抱えた個体を見つけられる。無理はするなよ」'],()=>{c.modal='investigations';c.renderUI()})}else{c.modal='investigations';c.renderUI()}}
export async function beginCase(c:ChapterContext,id:number){const old=structuredClone(c.state.investigations),p=progress(c.state.campaign),defeated=[...p.defeatedEnemies],bosses=[...p.bosses];startCase(c.state,id);const e=caseById(id);p.defeatedEnemies=p.defeatedEnemies.filter(x=>x!==e.enemy);p.bosses=p.bosses.filter(x=>x!==e.enemy);c.modal='';try{await c.transition(id);c.state.hp=c.maxHP();c.state.mp=c.maxMP();c.save();c.talk('ミナ',[`${e.title}。三つの痕跡を、案内の灯をたどって調べよう。`,e.hint])}catch(error){c.state.investigations=old;p.defeatedEnemies=defeated;p.bosses=bosses;c.build();c.notify('調査を開始できませんでした。記録は保持されています。')}}
export function goal(c:ChapterContext){const r=c.state.investigations?.run;if(!r||r.resolved)return c.objects.find(o=>o.id==='investigation-list');const next=[0,1,2].find(i=>!r.clues.includes(i));return c.objects.find(o=>o.id===(next===undefined?caseById(r.caseId).enemy:'trace-'+next))}
export function interact(c:ChapterContext,o:WorldObject){if(o.id==='investigation-list'){open(c);return}if(o.kind==='trace'){const i=Number(o.id.slice(6));if(scan(c.state,i)){c.save();c.talk('ミナ',[caseById(c.state.area).clues[i]]);c.build()}else open(c);return}if(o.kind==='boss'){if(!ready(c.state)){c.talk('ミナ',['先に三つの痕跡を調べよう。異変の流れを確かめてからなら、戦える。']);return}c.startBattle(o)}}
export function action(c:ChapterContext,a:string){if(a==='investigations'){open(c);return true}if(a.startsWith('investigate:')){void beginCase(c,Number(a.split(':')[1]));return true}if(a==='investigation-home'){void c.switchChapter('chapter-4').catch(()=>c.notify('環海を読み込めませんでした'));return true}return false}
export function victory(c:ChapterContext,id:string){const entry=cases.find(e=>e.enemy===id);if(!entry)return;const r=claim(c.state,entry.id);if(!r)return;c.save();c.build();c.talk('灯路異変 解消',[`${entry.title}の流れが、静かに戻っていく。`,`${r.first?'初回調査完了':'再調査完了'}：${r.xp}XP ／ ${r.gold}G。${r.leveled?'レベル '+c.state.lv+' に上がった！ HP・MP全回復。':''}`,...(r.item?[gear[r.item].name+'を手に入れた。冒険メニューの武器・防具で装備できる。']:[]),...(r.complete?['四つの灯路がつながった。「灯路の剣」を手に入れた。','ミナ「全部が、ひとつの流れなんだね。次の旅でも、この灯を忘れないでいよう」']:[])],()=>{c.modal='investigations';c.renderUI()})}
