import test from 'node:test';import assert from 'node:assert/strict';import * as T from 'three';
import {fresh} from '../app/systems/state.ts';import {progress,recordVictory,createProgress} from '../app/systems/progression.ts';
import {encode,decode,writeSave} from '../app/systems/save.ts';import {prepareChapterSwitch} from '../app/systems/chapter-manager.ts';
import {initialLoad,prepareLoad,installSafely} from '../app/systems/loading.ts';import {travel} from '../app/debug/debug-actions.ts';
import {debugStorage} from '../app/debug/gate.ts';import {batchStatic} from '../app/performance.ts';
import {migrateTrials,maxHealth,attackBonus,incoming,regenerate,reward,equip} from '../app/trials/state.ts';
import {awardGear,weaponBonus,armorBonus} from '../app/systems/gear.ts';
import chapter from '../app/chapters/chapter-4/chapter-config.ts';import {placements,treasures} from '../app/chapters/chapter-4/object-config.ts';
import {flags,canEnter} from '../app/chapters/chapter-4/state.ts';import {createFight,hit,retaliation,forecast,switchLamp,active,canSwitch,recovery} from '../app/chapters/chapter-4/combat.ts';
const memory=()=>{const m=new Map();return {getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,v)}};
function legacy(){const s=fresh();s.lv=13;s.hp=355;s.mp=112;s.gold=421;s.xp=87;s.potions=8;s.ethers=7;s.sword=s.armor=true;for(const id of ['chapter-1','chapter-2','chapter-3']){const p=s.campaign.chapters[id]=createProgress();p.completed=true;s.campaign.completedChapters.push(id)}s.campaign.currentChapter='chapter-3';s.campaign.unlockedChapters=['chapter-1','chapter-2','chapter-3'];return s}
function state(){const s=decode(JSON.stringify(encode(legacy())));return prepareChapterSwitch(s,'chapter-4',chapter.start)}
export function context(){const s=state();chapter.initialize(s);const c={state:s,progress:progress(s.campaign),world:new T.Group(),scene:new T.Scene(),ambient:new T.HemisphereLight(),sun:new T.DirectionalLight(),objects:[],blocks:[],mobile:true,animationTime:{value:0},modal:'',mode:'explore',talk:(_n,l,cb)=>{c.lines=l;c.after=cb},save:()=>{c.saved=JSON.stringify(encode(s))},notify:t=>c.notice=t,renderUI:()=>{},build:()=>{},burst:()=>{},maxHP:()=>maxHealth(s),maxMP:()=>30+(s.lv-1)*8,finish:()=>c.finished=true,transition:async n=>{s.area=n;s.x=0;s.z=16},startBattle:o=>c.enemy=o.id,rand:n=>Math.abs(Math.sin(n*13)%1),mat:(color,roughness=.9)=>new T.MeshStandardMaterial({color,roughness}),light:()=>{},exitMarker:()=>{},height:(x,z)=>chapter.height(s,x,z),addObj:(kind,name,x,z,id)=>{const o={kind,name,x,z,id,r:2.3};c.objects.push(o);return o},btn:(id,label,disabled)=>`<button data-action="${id}" ${disabled?'disabled':''}>${label}</button>`};c.box=(x,y,z,w,h,d,m)=>{const mesh=new T.Mesh(new T.BoxGeometry(w,h,d),m);mesh.position.set(x,y,z);c.world.add(mesh);return mesh};c.cyl=(x,y,z,r,h,m,n=8)=>{const mesh=new T.Mesh(new T.CylinderGeometry(r,r,h,n),m);mesh.position.set(x,y,z);c.world.add(mesh);return mesh};c.sprite=(kind,x,z)=>{const sp=new T.Sprite();sp.position.set(x,c.height(x,z),z);c.world.add(sp);return sp};c.chest=(x,z,id)=>c.addObj('chest','宝箱',x,z,id);return c}
function reachable(c,start,target){const step=.75,q=[[Math.round(start.x/step),Math.round(start.z/step)]],seen=new Set([q[0].join(',')]);for(let i=0;i<q.length&&i<5000;i++){const [a,b]=q[i];if(Math.hypot(a*step-target.x,b*step-target.z)<1.2)return true;for(const [dx,dz]of [[1,0],[-1,0],[0,1],[0,-1]]){const x=a+dx,z=b+dz,k=x+','+z;if(!seen.has(k)&&chapter.walkable(c.state,x*step,z*step)&&!c.blocks.some(r=>Math.abs(x*step-r.x)<r.w/2+.23&&Math.abs(z*step-r.z)<r.d/2+.23)){seen.add(k);q.push([x,z])}}}return false}
const interact=(c,id)=>{const o=placements[c.state.area].find(o=>o.id===id);assert.ok(o,id);chapter.interact(c,o)};
async function drain(c){for(let i=0;i<30;i++){const cb=c.after;c.after=null;if(cb)cb();await new Promise(r=>setImmediate(r));if(!c.after)break}}
test('C3 old clear unlocks C4 additively; no trial clear required; formal fields reconcile',()=>{const s=legacy();migrateTrials(s);for(let i=1;i<=5;i++)reward(s,i,20,100);equip(s,0,'afterglow');equip(s,1,'eternal');const original=structuredClone(s),d=decode(JSON.stringify(encode(s)));assert.ok(d.campaign.unlockedChapters.includes('chapter-4'));assert.deepEqual(d.trials,original.trials);for(const k of ['hp','mp','lv','xp','gold','potions','ethers','sword','armor'])assert.equal(d[k],s[k]);assert.deepEqual(d.campaign.chapters,s.campaign.chapters);assert.ok(!d.campaign.chapters['chapter-4']);const empty=decode(JSON.stringify(encode(legacy())));assert.equal(empty.trials.cleared.length,0);assert.equal(prepareChapterSwitch(empty,'chapter-4',chapter.start).campaign.currentChapter,'chapter-4');const formal=legacy();formal.campaign.chapters['chapter-3'].completed=false;assert.equal(decode(JSON.stringify(encode(formal))).campaign.chapters['chapter-3'].completed,true)});
test('C3 incomplete and boss-only cannot unlock C4',()=>{const s=legacy();s.campaign.completedChapters=s.campaign.completedChapters.filter(x=>x!=='chapter-3');const p=s.campaign.chapters['chapter-3'];p.completed=false;p.bosses=['aurel'];s.campaign.unlockedChapters.push('chapter-4');assert.throws(()=>prepareChapterSwitch(s,'chapter-4',chapter.start));assert.ok(!decode(JSON.stringify(encode(s))).campaign.unlockedChapters.includes('chapter-4'))});
for(const map of chapter.maps)test('C4 '+map.name+': load, spawn, every interaction reachable and bounded scenery',async()=>{const c=context();c.state.area=map.id;await (await map.load()).build(c);assert.ok(chapter.walkable(c.state,map.spawn.x,map.spawn.z));for(const o of c.objects)assert.ok(reachable(c,map.spawn,o),map.name+': '+o.id);assert.ok(c.world.children.length<240,c.world.children.length);assert.equal(c.world.children.filter(o=>o.isReflector).length,0);c.state.x=map.spawn.x;c.state.z=map.spawn.z;const d=decode(JSON.stringify(encode(c.state)));assert.equal(d.x,c.state.x);assert.equal(d.z,c.state.z);batchStatic(c.world);c.world.traverse(o=>{o.geometry?.dispose();o.material?.dispose?.()})});
test('C4 full chapter event route both islands, boss victory, ending and reload',async()=>{const c=context(),s=c.state;chapter.begin(c);assert.equal(c.modal,'chapter4-title');chapter.action(c,'ring-start');await drain(c);s.area=1;interact(c,'rau');assert.equal(canEnter(s,2),true);for(const [area,ids,lamp]of [[3,['shell','ray'],'east'],[2,['biter','jelly'],'west']]){s.area=area;interact(c,lamp);assert.ok(!flags(s)[lamp]);for(const id of ids)recordVictory(s.campaign,id,false);interact(c,lamp)}assert.equal(canEnter(s,4),true);s.area=4;recordVictory(s.campaign,'seawarden',true);chapter.onBossVictory(c,'seawarden');assert.equal(canEnter(s,5),true);s.area=5;interact(c,'cut');assert.equal(canEnter(s,6),true);s.area=6;interact(c,'van');await drain(c);assert.equal(canEnter(s,7),true);s.area=7;interact(c,'ignas');await drain(c);assert.equal(c.enemy,'ignas');recordVictory(s.campaign,'ignas',true);chapter.onBossVictory(c,'ignas');await drain(c);assert.equal(c.finished,true);assert.equal(c.progress.completed,true);assert.equal(flags(s).network,true);assert.equal(c.progress.quests['ring-current'],'complete');assert.equal(s.area,1);assert.ok(decode(c.saved).campaign.completedChapters.includes('chapter-4'));assert.match(chapter.endingUI(c),/CHAPTER 4 COMPLETE/)});
test('all six treasures and both subquests grant once, survive save and do not gate main',()=>{const c=context();for(const id of Object.keys(treasures)){chapter.interact(c,{kind:'chest',id});const before=JSON.stringify(encode(c.state));chapter.interact(c,{kind:'chest',id});assert.equal(JSON.stringify(encode(c.state)),before)}c.state.area=1;interact(c,'sena');interact(c,'ordo');for(const [area,id]of [[2,'mark-west'],[3,'mark-east'],[4,'mark-ring'],[5,'tablet']]){c.state.area=area;interact(c,id)}c.state.area=1;interact(c,'sena');interact(c,'ordo');const before=encode(c.state);interact(c,'sena');interact(c,'ordo');assert.deepEqual(encode(c.state),before);assert.equal(decode(JSON.stringify(before)).campaign.chapters['chapter-4'].quests['stone-record'],'complete');assert.ok(c.state.gear.owned.includes('silent-cloth'))});
test('three lamps stop for bounded turns with cooldown and cannot repeat; phase two increases interval',()=>{const f=createFight();assert.equal(switchLamp(f,'cycle',1),true);assert.equal(active(f,'cycle',3),false);assert.equal(active(f,'cycle',4),true);assert.equal(canSwitch(f,'cycle',4),false);assert.equal(canSwitch(f,'attack',2),false);assert.equal(canSwitch(f,'attack',3),true);f.phase=2;switchLamp(f,'attack',3);assert.equal(canSwitch(f,'defense',5),false);assert.equal(canSwitch(f,'defense',6),true);assert.match(forecast('ignas',5),/防御/);assert.match(forecast('seawarden',4),/白い灯/)});
function fight(id,access=false,level=14){const s=state();s.lv=level;s.hp=maxHealth(s);s.mp=30+(level-1)*8;s.potions=8;s.ethers=7;s.trials.slots=access?['afterglow','eternal']:[null,null];const f=createFight();let hp=chapter.enemies[id].hp,turn=0,phase2=false,switched=false;while(hp>0&&s.hp>0&&turn++<150){let cmd='fire';if((id==='ignas'&&turn%5===0)||(id==='seawarden'&&turn%4===0))cmd='guard';else if(s.hp<130&&s.potions)cmd='potion';else if(s.hp<100&&s.mp>=5)cmd='heal';else if(id==='ignas'&&turn%5===4&&canSwitch(f,'cycle',turn))cmd='route:cycle';else if(id==='ignas'&&canSwitch(f,'defense',turn))cmd='route:defense';else if(s.mp<6)cmd=s.ethers?'ether':'attack';if(cmd.startsWith('route:')){switchLamp(f,cmd.slice(6),turn);switched=true}if(cmd==='fire')s.mp-=6;if(cmd==='ether'){s.ethers--;s.mp=Math.min(30+(level-1)*8,s.mp+20)}if(cmd==='potion'){s.potions--;s.hp=Math.min(maxHealth(s),s.hp+65)}if(cmd==='heal'){s.mp-=5;s.hp=Math.min(maxHealth(s),s.hp+58)}const base=cmd==='attack'?attackBonus(s,17+level*4+weaponBonus(s)):cmd==='fire'?attackBonus(s,33+level*6):0;hp-=hit(f,id,turn,cmd,base);if(hp<=0)break;if(hp<=chapter.enemies[id].hp*.5){f.phase=2;phase2=true}if(id==='ignas')hp=Math.min(chapter.enemies[id].hp,hp+recovery(f,turn));s.hp=Math.max(0,s.hp-incoming(s,retaliation(f,id,turn),cmd==='guard',()=>1));regenerate(s)}return {hp,player:s.hp,turn,phase2,switched}}
for(const id of Object.keys(chapter.enemies))test(id+' balanced without accessories and repeatable after defeat',()=>{for(let i=0;i<2;i++){const r=fight(id);assert.ok(r.hp<=0,JSON.stringify({id,...r}));if(id==='ignas'){assert.ok(r.phase2);assert.ok(r.switched)}}});
test('accessory stats, regen and two slots remain effective; optional C4 gear does not replace them',()=>{const s=state();migrateTrials(s);for(let i=1;i<=5;i++)reward(s,i,20,100);equip(s,0,'afterglow');equip(s,1,'eternal');assert.equal(attackBonus(s,100),108);s.hp=1;regenerate(s);assert.equal(s.hp,1+Math.floor(maxHealth(s)*.03));const slots=[...s.trials.slots];awardGear(s,'ring-sword');awardGear(s,'silent-cloth');assert.equal(weaponBonus(s),11);assert.equal(armorBonus(s),5);assert.deepEqual(s.trials.slots,slots);assert.deepEqual(decode(JSON.stringify(encode(s))).gear,s.gear);assert.ok(fight('ignas',true).hp<=0)});
test('cleared debug travel to every map preserves story fields and normal storage',async()=>{const store=memory();writeSave(store,legacy());const original=store.getItem('lumenfall-save');for(const id of ['chapter-1','chapter-2','chapter-3','chapter-4']){const c=await travel(fresh(),id,undefined,'Cleared');const {loadChapter}=await import('../app/chapters/registry.ts');for(const map of (await loadChapter(id)).maps){const n=await travel(c,id,map.id),old=progress(c.campaign),p=progress(n.campaign);assert.equal(n.area,map.id);assert.equal(p.completed,true);assert.deepEqual(p.flags,old.flags);assert.deepEqual(p.quests,old.quests);writeSave(debugStorage(store),n)}}assert.equal(store.getItem('lumenfall-save'),original)});
test('startup import/missing chapter/map failures and corrupt JSON never write fresh over saves',async()=>{const storage=memory();writeSave(storage,legacy());const before=storage.getItem('lumenfall-save');await assert.rejects(()=>initialLoad(storage,async()=>{throw Error('missing chunk')}));await assert.rejects(()=>initialLoad(storage,async()=>({initialize(){},normalize(){},maps:[{id:0,load:async()=>{throw Error('map chunk')}}]})));const s=legacy();s.campaign.currentChapter='missing';s.campaign.chapters.missing=createProgress();await assert.rejects(()=>prepareLoad(s));assert.equal(storage.getItem('lumenfall-save'),before);storage.setItem('lumenfall-save','broken');await assert.rejects(()=>initialLoad(storage));assert.equal(storage.getItem('lumenfall-save'),'broken')});
test('failed installation rolls back state and leaves persisted bytes untouched',()=>{const storage=memory(),old=legacy();writeSave(storage,old);const before=storage.getItem('lumenfall-save');let current=old,world='old';assert.throws(()=>installSafely(()=>{current=fresh();world='partial';throw Error('build failure')},()=>{current=old;world='old'}));assert.equal(current,old);assert.equal(world,'old');assert.equal(storage.getItem('lumenfall-save'),before)});
test('batching does not discard texture/alphaTest or custom shader material differences',()=>{for(const make of [()=>new T.MeshStandardMaterial({map:new T.Texture()}),()=>new T.MeshStandardMaterial({alphaTest:Math.random()+.1}),()=>{const m=new T.MeshStandardMaterial();m.onBeforeCompile=()=>{};return m}]){const group=new T.Group();group.add(new T.Mesh(new T.BoxGeometry(),make()),new T.Mesh(new T.BoxGeometry(),make()));batchStatic(group);assert.equal(group.children.length,2)}});
