import test from 'node:test';import assert from 'node:assert/strict';
import {fresh} from '../app/systems/state.ts';
import {progress} from '../app/systems/progression.ts';
import {encode,decode,SAVE_VERSION,writeSave} from '../app/systems/save.ts';
import {initialLoad} from '../app/systems/loading.ts';
import {prepareChapterSwitch} from '../app/systems/chapter-manager.ts';
import {loadChapter} from '../app/chapters/registry.ts';
import {travel,presets} from '../app/debug/debug-actions.ts';
import {debugStorage} from '../app/debug/gate.ts';
import {cases,FIRST_XP,REPEAT_XP} from '../app/investigations/catalog.ts';
import {investigationUnlocked,migrateInvestigations,startCase,scan,ready} from '../app/investigations/state.ts';
import {claim} from '../app/investigations/rewards.ts';
import {open} from '../app/investigations/events.ts';
import * as combat from '../app/investigations/combat.ts';
import {gear,equipGear,weaponBonus,armorBonus} from '../app/systems/gear.ts';
import {maxHealth,incoming} from '../app/trials/state.ts';
import {createGearFight,outgoingGear,incomingGear,drainMP,endGearBattle} from '../app/systems/gear-effects.ts';
function oldSave(lv=14){const s=fresh();s.lv=lv;s.hp=maxHealth(s);s.mp=30+(lv-1)*8;s.gold=500;s.sword=s.armor=true;for(const id of ['chapter-1','chapter-2','chapter-3','chapter-4']){const p=progress(s.campaign,id);p.completed=true;p.flags.kept='yes';p.quests.story='complete';p.bosses=['preserved'];p.chests=['kept'];s.campaign.completedChapters.push(id)}s.trials.owned=['warden','eternal'];s.trials.slots=['warden','eternal'];s.trials.cleared=[1,2,3,4,5];return s}
function clear(s,id){startCase(s,id);for(let i=0;i<3;i++)scan(s,i);return claim(s,id)}
test('investigations require formal Chapter 4 completion, not trials or injected unlock flag',async()=>{const s=fresh();s.trials.cleared=[1,2,3,4,5];migrateInvestigations(s).unlocked=true;s.campaign.unlockedChapters.push('investigations');assert.equal(investigationUnlocked(s),false);assert.throws(()=>startCase(s,0));assert.throws(()=>prepareChapterSwitch(s,'investigations',{area:0,x:0,z:17}));assert.throws(()=>(presets.investigations.apply(s,'Anomaly 1')));const pack=await loadChapter('investigations');assert.throws(()=>pack.initialize(s));});
test('old C4 save with no investigation data unlocks additively without resetting player/story/trials',()=>{const s=oldSave(),before=structuredClone(s);const n=decode(JSON.stringify(encode(s)));assert.equal(n.investigations.unlocked,true);assert.deepEqual(n.investigations.cleared,[]);assert.deepEqual(n.campaign.chapters,before.campaign.chapters);assert.deepEqual(n.trials.slots,before.trials.slots);assert.deepEqual(n.trials.cleared,before.trials.cleared);for(const k of ['lv','xp','gold','hp','mp','potions','ethers','sword','armor'])assert.equal(n[k],before[k]);assert.equal(SAVE_VERSION,2)});
test('unlock introduction is one-time and survives reload',()=>{let s=oldSave(),talks=0;const c={get state(){return s},save(){},talk(_n,_l,after){talks++;after()},renderUI(){},modal:''};open(c);s=decode(JSON.stringify(encode(s)));open(c);assert.equal(talks,1);assert.equal(c.modal,'investigations')});
for(const entry of cases){
 test(entry.title+': clues, initial reward, repeat and idempotent payout',()=>{const s=oldSave();migrateInvestigations(s);startCase(s,entry.id);assert.equal(claim(s,entry.id),null);scan(s,0);scan(s,0);assert.equal(s.investigations.run.clues.length,1);scan(s,1);scan(s,2);assert.equal(ready(s),true);let r=claim(s,entry.id);assert.equal(r.xp,FIRST_XP);assert.equal(r.gold,entry.gold);assert.equal(r.item,entry.item);assert.equal(s.gear.weapon,undefined);const saved=JSON.stringify(encode(s));assert.equal(claim(s,entry.id),null);assert.equal(JSON.stringify(encode(s)),saved);r=clear(s,entry.id);assert.equal(r.xp,REPEAT_XP);assert.equal(r.gold,entry.repeatGold);assert.equal(r.item,null);assert.equal(s.gear.owned.filter(x=>x===entry.item).length,1);assert.equal(s.investigations.xpRewarded.length,1)});
 test(entry.title+': debug boss shortcut and scene load leave main records untouched',async()=>{const source=oldSave();const before=structuredClone(source.campaign.chapters);const n=await travel(source,'investigations',undefined,'Anomaly '+(entry.id+1));assert.equal(n.area,entry.id);assert.equal(ready(n),true);for(const id of ['chapter-1','chapter-2','chapter-3','chapter-4']){const a=structuredClone(n.campaign.chapters[id]),b=structuredClone(before[id]);delete a.position;delete b.position;assert.deepEqual(a,b)};const pack=await loadChapter('investigations');const m=await pack.maps[entry.id].load();assert.equal(typeof m.build,'function');assert.ok(pack.walkable(n,0,17));const loaded=decode(JSON.stringify(encode(n)));assert.deepEqual(loaded.investigations,n.investigations)});
}
for(const lv of [14,15])test('four first clears from Lv'+lv+' stay within 0.8–1.2 levels, preserve main progress',()=>{const s=oldSave(lv),before=structuredClone(s.campaign.chapters);let xp=0;for(const e of cases)xp+=clear(s,e.id).xp;assert.equal(xp,480);assert.ok(xp/(lv*30)>=.8&&xp/(lv*30)<=1.2);assert.equal(s.lv,lv+1);assert.equal(s.xp,lv===14?60:30);assert.ok(s.gear.owned.includes('lamproad-sword'));assert.deepEqual(s.campaign.chapters,before);for(const c of cases){const r=clear(s,c.id);assert.equal(r.complete,false)}assert.equal(s.gear.owned.filter(x=>x==='lamproad-sword').length,1)});
test('DEBUG save persists investigation but leaves normal save bytes unchanged; failed load preserves save',async()=>{const s=oldSave(),data=new Map(),store={getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)};writeSave(store,s);const normal=data.get('lumenfall-save');const n=await travel(s,'investigations',undefined,'Anomaly 4');clear(n,3);writeSave(debugStorage(store),n);assert.equal(data.get('lumenfall-save'),normal);await assert.rejects(initialLoad(debugStorage(store),async()=>{throw Error('missing chunk')}));assert.equal(data.get('lumenfall-save'),normal);assert.ok(data.has('lumenfall-debug-save'))});
test('wind guard, execute and once-per-battle resonance are bounded and reset',()=>{const s=oldSave();s.gear={owned:['afterwind-sword','white-lamp-blade','lamproad-sword','ringkeeper-robes'],weapon:'afterwind-sword'};let f=createGearFight(),b={hp:30,max:100,boss:true,turn:1,command:'attack'};outgoingGear(s,f,b,100,()=>0);assert.equal(incomingGear(s,f,b,100),90);assert.equal(incomingGear(s,f,b,100),100);equipGear(s,'white-lamp-blade');assert.equal(outgoingGear(s,f,b,100),106);assert.equal(outgoingGear(s,f,{...b,boss:false},100),112);equipGear(s,'lamproad-sword');f=createGearFight();assert.equal(outgoingGear(s,f,b,100),100);for(let turn=5;turn<=10;turn++)assert.equal(outgoingGear(s,f,{...b,turn},100),turn<7?110:100);assert.equal(f.resonated,true);assert.equal(createGearFight().resonated,false);equipGear(s,'ringkeeper-robes');assert.equal(incomingGear(s,createGearFight(),b,100),92);assert.equal(incomingGear(s,createGearFight(),{...b,turn:4},100),100);assert.equal(armorBonus(s),7)});
test('tidelight MP resistance and victory recovery never exceed max or revive',()=>{const s=oldSave();s.gear={owned:['tidelight-cloak'],armor:'tidelight-cloak'};s.mp=10;assert.equal(drainMP(s,6),3);assert.equal(s.mp,7);endGearBattle(s);assert.equal(s.mp,10);s.mp=999;endGearBattle(s);assert.equal(s.mp,134);s.hp=0;s.mp=0;endGearBattle(s);assert.equal(s.mp,0)});
test('wind can evade swords but light strips guard; threats remain visible',()=>{const s=oldSave(),c={state:s,battle:{hp:900,max:960}};combat.start();combat.onCommand(c,'afterwind',1,'attack');assert.equal(combat.damage(c,'afterwind',1,'attack',100,()=>0),0);assert.equal(combat.damage(c,'afterwind',1,'fire',100,()=>0),100);assert.match(combat.status(c,'afterwind',3),/今、防御/);assert.equal(combat.enemyAttack(c,'afterwind',4,'guard',36),80)});
test('echo MP siphon buffs next attack, frost charges and ring switching stays turn-based',()=>{const s=oldSave(),c={state:s,battle:{id:'echo-jelly',hp:900,max:1000,turn:0}};combat.start();const mp=s.mp;combat.enemyAttack(c,'echo-jelly',1,'attack',38);assert.equal(s.mp,mp-6);assert.equal(combat.enemyAttack(c,'echo-jelly',2,'guard',38),50);combat.start();c.battle.hp=400;combat.enemyAttack(c,'reverse-frost',1,'attack',36);assert.match(combat.status(c,'reverse-frost',1),/今、防御/);assert.ok(combat.enemyAttack(c,'reverse-frost',2,'guard',24)>75);combat.start();c.battle.id='ring-remnant';combat.onCommand(c,'ring-remnant',1,'route:cycle');const hp=c.battle.hp;combat.enemyAttack(c,'ring-remnant',1,'route:cycle',38);assert.equal(c.battle.hp,hp);assert.equal(combat.commands(c).find(x=>x.id==='route:cycle').disabled,true);combat.onCommand(c,'ring-remnant',2,'route:defense');assert.equal(combat.damage(c,'ring-remnant',3,'attack',100),100)});
for(const lv of [14,15])test('all four fights can be beaten at Lv'+lv+' with standard gear and no trial accessories',()=>{
 const s=oldSave(lv);s.trials.slots=[null,null];s.potions=10;s.ethers=8;for(const e of cases){combat.start();s.hp=maxHealth(s);s.mp=30+(s.lv-1)*8;const c={state:s,battle:{id:e.enemy,hp:e.hp,max:e.hp,turn:0}},g=createGearFight();let turns=0;while(c.battle.hp>0&&turns<80&&s.hp>0){const next=++turns,hint=combat.status(c,e.enemy,next-1);let cmd=hint.includes('今、防御')?'guard':s.hp<140?'heal':s.mp>=6?'fire':'attack';if(cmd==='heal'&&s.mp<5)cmd='potion';if(e.id===3&&next===1)cmd='route:defense';combat.onCommand(c,e.enemy,next,cmd);let hit=0;if(cmd==='attack')hit=17+s.lv*4+weaponBonus(s);if(cmd==='fire'){s.mp-=6;hit=33+s.lv*6}if(cmd==='heal'){s.mp-=5;s.hp=Math.min(maxHealth(s),s.hp+58)}if(cmd==='potion'){assert.ok(s.potions>0,e.name+' HP '+s.hp+' enemy '+c.battle.hp+' turn '+turns);s.potions--;s.hp=Math.min(maxHealth(s),s.hp+65)}hit=combat.damage(c,e.enemy,next,cmd,hit,()=>1);c.battle.hp-=hit;if(c.battle.hp<=0)break;const raw=combat.enemyAttack(c,e.enemy,next,cmd,e.attack);s.hp-=incomingGear(s,g,{boss:true,turn:next},incoming(s,raw,cmd==='guard',()=>1));}assert.ok(s.hp>0&&c.battle.hp<=0,e.name+' cannot finish');assert.ok(turns>=6&&turns<40);clear(s,e.id)}
});
test('new gear mitigation works through trial turn rules without modifying lamp or no-heal rules',async()=>{const {createRun,resolveTurn,allowed}=await import('../app/trials/rules.ts');const s=oldSave();s.trials.slots=[null,null];s.gear={owned:['ringkeeper-robes'],armor:'ringkeeper-robes'};const r=createRun(5),baseline=createRun(5),other=structuredClone(s);resolveTurn(baseline,other,'guard',0,()=>1);resolveTurn(r,s,'guard',0,()=>1,n=>incomingGear(s,createGearFight(),{boss:true,turn:r.turn},n));assert.equal(r.lamp,baseline.lamp);assert.ok(s.hp>=other.hp);assert.equal(allowed(createRun(4),'heal'),false)});
