import type {GameState} from '../../systems/state.ts';
import {progress} from '../../systems/progression.ts';
export const flags=(s:GameState)=>progress(s.campaign,'chapter-2').flags;
export const won=(s:GameState,id:string)=>progress(s.campaign,'chapter-2').defeatedEnemies.includes(id);
export const clues=['clue-bell','clue-boat','clue-star'] as const;
export const order=['bell','boat','star'] as const;
export const allClues=(s:GameState)=>clues.every(id=>flags(s)[id]);
export const bridgeOpen=(s:GameState)=>Number(flags(s).beacons??0)===3;
export const naveOpen=(s:GameState)=>!!flags(s)['nave-west']&&!!flags(s)['nave-east'];
export const choirReady=(s:GameState)=>['vigil-west','vigil-east','vigil-heart'].every(id=>flags(s)[id]);
