import type {ChapterContext} from '../types.ts';
import {maps} from './map-config.ts';
import {goal} from './events.ts';
import {flags,bridgeOpen,naveOpen,won} from './state.ts';
export function hud(c:ChapterContext){const m=maps[c.state.area],g=goal(c),f=flags(c.state);const near=g&&Math.hypot(g.x-c.state.x,g.z-c.state.z)<g.r;const text=c.progress.completed?'帰った人たちの灯を見届けよう':c.state.area===0?'港の三人から証言を集め、イサへ':c.state.area===1?'航路灯：鐘 → 舟 → 星（'+Number(f.beacons??0)+'/3）':c.state.area===2?'左右の祈り灯をつなぎ、沈鐘の衛士へ':'三つの帰り灯を点け、聖歌の主へ';return `<div class="top"><div class="region"><small>${m.eyebrow}</small><h2>${m.name}</h2><p>${m.description} · 夜</p></div><div class="tools"><button class="iconbtn" data-action="sound" aria-label="音の切り替え">${c.muted?'♪̸':'♪'}</button><button class="iconbtn" data-action="map" aria-label="周辺の案内">⌖</button><button class="iconbtn" data-action="menu" aria-label="冒険メニュー">☰</button></div></div><div class="quest"><small>CHAPTER 2 · 帰り灯の海</small><div class="journey">港 › 桟橋 › 礼拝堂 › 聖歌廊</div><span class="quest-copy">${text}</span>${g?`<button class="guide" data-action="guide">${near?'進む · ':'⌖ '}${g.name}</button>`:''}<button class="guide chapter-notebook" data-action="harbor-notes">航路の手帳</button></div>`}
export function modalUI(c:ChapterContext){const b=c.btn,s=c.state,f=flags(s);let h='';if(c.modal.startsWith('beacon:')){const id=c.modal.slice(7),name=c.objects.find(o=>o.id===id)?.name;h=`<h2>${name}</h2><p>濡れた台座に火を分ける。<br>航路の作法：<b>鐘 → 舟 → 星</b><br>現在 ${Number(f.beacons??0)} / 3 点灯</p>${b('ignite-beacon','この灯に火を分ける')}${b('close','戻る')}`}
 if(c.modal==='shop')h=`<h2>港の旅支度</h2><p>所持金 ${s.gold} G。海へ出る前に備えを。</p>${b('buy-potion','薬草 15 G ／ HP +65',s.gold<15)}${b('buy-ether','星の雫 20 G ／ MP +20',s.gold<20)}${b('buy-sword',s.sword?'暁鉄の剣 装備中':'暁鉄の剣 40 G ／ 攻撃 +9',s.sword||s.gold<40)}${b('buy-armor',s.armor?'織星の外套 装備中':'織星の外套 35 G ／ 被ダメージ −5',s.armor||s.gold<35)}${b('close','店を出る')}`;
 if(c.modal==='inn')h=`<h2>宿屋「帰り灯」</h2><p>「帰る人のために、灯を残しているの」<br>HP・MP全回復。所持金 ${s.gold} G。</p>${b('rest',s.gold>=10?'ひと休みする 10 G':'ひと休みする（今回は無料）')}${b('close','宿を出る')}`;
 if(c.modal==='home-confirm')h=`<h2>リュネへの街道</h2><p>港の進行を記録してChapter 1へ戻ります。メニューのチャプター記録から、いつでも港の続きを再開できます。</p>${b('return-chapter-1','リュネへ戻る')}${b('close','港に残る')}`;
 if(c.modal==='harbor-notes')h=`<h2>航路の手帳</h2><p>聞き込み：鐘番 ${f['clue-bell']?'✓':'—'} ／ 船大工 ${f['clue-boat']?'✓':'—'} ／ 星図師 ${f['clue-star']?'✓':'—'}<br>灯の順番：<b>鐘 → 舟 → 星</b><br>礼拝堂：左右の祈り灯で階段を開く。<br>深部：三つの帰り灯を点ける。</p><p>潮殻：星火が弱点。<br>クラゲ：三行動ごとの濃霧は星火で。<br>蛾：星火で反撃を弱める。<br>ネレイス：三行動ごとに消灯。星火で灯し直すか、防御。</p><p>弟の捜索：${c.progress.quests['lost-brother']??'未受注'}<br>工具箱：${c.progress.quests['lost-tools']??'未受注'}</p>${b('close','手帳を閉じる')}`;
 return h?'<div class="overlay"><div class="panel">'+h+'</div></div>':''}
export function endingUI(c:ChapterContext){return `<div class="overlay"><div class="panel ending"><div class="eyebrow">A LIGHT TO COME HOME TO</div><h1>帰り灯の海</h1><div class="sep"></div><p>窓に灯が戻り、港に名前が戻った。<br>分け合った小さな火は、<br>霧の向こうでも消えなかった。</p><p>黒い星硝子が示すのは、白嶺の観測塔。<br>雪の奥で、第三の灯が待っている。</p><div class="badge">CHAPTER 2 CLEAR</div><p>到達レベル ${c.state.lv} · 宝箱 ${c.progress.chests.length}/4</p>${c.btn('after','人々の戻った港へ')}</div></div>`}
export function visible(c:ChapterContext,o:import('../types.ts').WorldObject){if(c.state.area===1&&o.id==='chapel')return bridgeOpen(c.state);if(c.state.area===2&&o.id==='bellwarden')return naveOpen(c.state);if(c.state.area===2&&o.id==='choir')return won(c.state,'bellwarden');return true}
