import {foeColors} from './presentation.ts';
import type {GameState} from '../systems/state.ts';
import {accessories,migrateTrials} from './state.ts';
import {trialNames,descriptions,hidden,forecast} from './rules.ts';
import type {TrialRun} from './rules.ts';
type Button=(id:string,t:string,disabled?:boolean)=>string;
export function trialMenu(s:GameState,btn:Button){const t=migrateTrials(s);return `<div class="overlay"><div class="panel trial-panel"><div class="eyebrow">灯守の遺した記憶</div><h2>灯の試練 <small>ともしびのしれん</small></h2><p>すべてターン制。挑戦時はHP・MP全快、薬草4・星の雫3を貸与。終了・撤退時に本編のHP・MP・所持品へ戻ります。途中記録からの再開は祭壇から再挑戦です。</p>${trialNames.map((n,i)=>`<section><h3>第${i+1}の試練「${n}」${t.cleared.includes(i+1)?' · CLEAR':''}</h3><p>${descriptions[i]}</p><p>初回報酬：${accessories[i].name} · ${accessories[i].effect}</p>${t.best[i+1]?`<p>ベスト ${t.best[i+1].turns}ターン · 残HP ${t.best[i+1].hp}</p>`:''}${btn('trial-start:'+(i+1),t.cleared.includes(i+1)?'もう一度挑む':'挑戦する',!t.unlockedTrials.includes(i+1))}</section>`).join('')}${btn('equipment','アクセサリーを整える')}${btn('trial-return','霧港へ帰る')}${btn('close','祭壇へ戻る')}</div></div>`}
export function equipmentMenu(s:GameState,btn:Button){const t=migrateTrials(s);return `<div class="overlay"><div class="panel"><h2>アクセサリー</h2><p>装備は2枠。同じ品は同時に2個装備できません。試練でも本編でも効果を発揮します。</p>${[0,1].map(slot=>`<section><h3>アクセサリー${slot+1}：${accessories.find(a=>a.id===t.slots[slot])?.name??'なし'}</h3>${btn('equip:'+slot+':none','外す',!t.slots[slot])}${accessories.filter(a=>t.owned.includes(a.id)).map(a=>btn('equip:'+slot+':'+a.id,a.name+' — '+a.effect,t.slots.includes(a.id))).join('')}</section>`).join('')}<p>防御力+8%は防具適用後の被ダメージを1/1.08にします。リジェネは戦闘の行動選択開始時のみ。無癒では発動しません。</p>${btn('close','戻る')}</div></div>`}
export function trialStatus(r:TrialRun,btn:Button,busy:boolean){const live=r.foes.reduce((n,f)=>n+(f.hp>0?1:0),0);return `<div class="trial-status"><b>第${r.id}の試練「${trialNames[r.id-1]}」 · ${r.turn} ${r.id===2?'/ 15 ':''}ターン</b><p>${r.id===1||r.id===4?'Wave '+r.wave+' / 3 · ':''}${r.id===1||r.id===5?'灯 '+r.lamp+' / 100 · ':''}${r.id===5?'第'+r.phase+'形態 · 欠片 '+r.shards:''}${r.id===4?'回復禁止':''} · 敵 ${live}体</p>${r.id===1||r.id===5?`<div class=trial-lamp role=meter aria-label=灯 aria-valuemin=0 aria-valuemax=100 aria-valuenow=${r.lamp}><i style="width:${r.lamp}%"></i></div>`:''}<p>${live?forecast(r):r.id===2&&r.result==='active'?'敵はいない。防御・回復で次の増援を待とう。':'敵を倒した！'}</p><div class="trial-targets trial-roster">${r.foes.map((f,i)=>f.hp>0?btn('trial-target:'+i,`<span style="color:${foeColors[i%6]}">${r.target===i?'◎ 選択中':'○ 敵'+(i+1)} · ${f.name}</span><small>${hidden(r)?'HP ？？？':f.hp+' / '+f.max}</small>`,busy):'').join('')}</div>${hidden(r)?'<p>弱点・予告：？？？</p>':''}</div>`}
