import type {GameState} from '../systems/state.ts';
import type {Chapter,WorldObject} from '../chapters/types.ts';
import {progress,recordVictory} from '../systems/progression.ts';
import {chapters,presets,travel,playerAction,editProgress,exportSave,importSave,resetChapter,resetAll,mark,reconcile} from './debug-actions.ts';
import {DEBUG_SAVE} from './gate.ts';
export type Host={state:()=>GameState;chapter:()=>Chapter;objects:()=>WorldObject[];replace:(s:GameState)=>Promise<void>;refresh:()=>void;save:()=>void;reload:()=>Promise<void>;stop:()=>void;safe:()=>boolean;canMove:(x:number,z:number)=>boolean;teleport:(x:number,z:number)=>void;win:()=>void;defeatBoss:(id:string)=>void;god:(v:boolean)=>void;stats:()=>unknown};
export function mountDebug(h:Host){
 const root=document.createElement('details');root.id='lumenfall-debug';root.open=false;const title=document.createElement('summary');title.textContent='DEBUG';root.append(title);const body=document.createElement('div');root.append(body);const status=document.createElement('p');status.textContent='専用セーブ / 通常データは変更しません';body.append(status);let pending=false,disposed=false;
 const el=(tag:string,text='',parent:HTMLElement=body)=>{const e=document.createElement(tag);e.textContent=text;parent.append(e);return e};
 const section=(name:string)=>{const d=el('details') as HTMLDetailsElement;el('summary',name,d);return d};
 const run=async(f:()=>unknown)=>{if(pending)return;pending=true;try{await f();status.textContent='OK · DEBUG専用セーブ';update()}catch(e){status.textContent=e instanceof Error?e.message:String(e)}finally{pending=false}};
 const button=(name:string,f:()=>unknown,parent:HTMLElement)=>{const b=el('button',name,parent) as HTMLButtonElement;b.type='button';b.addEventListener('click',()=>void run(f));return b};
 const input=(label:string,parent:HTMLElement,type='text')=>{const l=el('label',label,parent);const i=el('input','',l) as HTMLInputElement;i.type=type;return i};
 const select=(label:string,parent:HTMLElement)=>{const l=el('label',label,parent);return el('select','',l) as HTMLSelectElement};
 const options=(s:HTMLSelectElement,values:{id:string;title:string}[])=>{s.replaceChildren();for(const v of values){const o=document.createElement('option');o.value=v.id;o.textContent=v.title;s.append(o)}};
 const safe=()=>{if(!h.safe())throw Error('戦闘・会話・演出を終了してから操作してください');h.stop()};
 const replace=async(s:GameState)=>{safe();await h.replace(mark(s));h.save()};
 const world=section('World'),info=el('pre','',world),chapterSelect=select('Chapter',world);options(chapterSelect,chapters());
 button('Go',async()=>{safe();await replace(await travel(h.state(),chapterSelect.value))},world);
 const mapSelect=select('Map',world);button('Teleport',async()=>{safe();await replace(await travel(h.state(),h.chapter().id,Number(mapSelect.value)))},world);
 const x=input('X',world,'number'),z=input('Z',world,'number');x.step=z.step='0.1';button('Teleport to coordinates',()=>{safe();if(!x.value||!z.value)throw Error('X/Zを入力してください');h.teleport(Number(x.value),Number(z.value));mark(h.state());h.save()},world);
 const player=section('Player');for(const [name,key]of [['HP全回復','hp'],['MP全回復','mp'],['HP/MP全回復','both'],['Gold +100','gold:100'],['Gold +1000','gold:1000'],['薬草 +1','potions:1'],['薬草 +10','potions:10'],['星の雫 +1','ethers:1'],['星の雫 +10','ethers:10'],['Level +1','lv:1'],['XP +100','xp:100']])button(name,()=>{safe();playerAction(h.state(),key);h.refresh();h.save()},player);
 const god=input('God Mode（HPのみ。灯の敗北条件は有効）',player,'checkbox');god.addEventListener('change',()=>{h.god(god.checked);mark(h.state())});
 const story=section('Progress'),presetSelect=select('Shortcut',story);button('Apply preset',async()=>{safe();if(!confirm('このChapterの進行をデバッグ用に変更しますか？'))return;await replace(await travel(h.state(),h.chapter().id,undefined,presetSelect.value))},story);
 el('p','flags / quests / defeatedEnemies（wins）/ bosses / chests / completed を編集。Chapter 1: storyStage=quest、seal:west/east=seals。',story);
 const progressJSON=el('textarea','',story) as HTMLTextAreaElement;progressJSON.setAttribute('aria-label','Chapter progress JSON');button('Read progress',()=>{progressJSON.value=JSON.stringify(progress(h.state().campaign),null,2)},story);button('Apply progress JSON',async()=>{safe();await replace(editProgress(h.state(),progressJSON.value))},story);
 const flagKey=input('Flag key',story),flagValue=input('Value (JSON: true / 1 / "text")',story);button('Set flag',async()=>{safe();const p=structuredClone(progress(h.state().campaign));const k=flagKey.value.trim();if(!k||['__proto__','constructor','prototype'].includes(k))throw Error('Invalid key');p.flags[k]=JSON.parse(flagValue.value);await replace(editProgress(h.state(),JSON.stringify(p)))},story);
 const battle=section('Battle'),enemySelect=select('Enemy（現在マップ）',battle);let enemies:WorldObject[]=[];
 button('Refresh enemies',()=>readEnemies(),battle);
 button('Bossへテレポート',()=>{safe();const boss=enemies.find(o=>o.id===enemySelect.value&&h.chapter().enemies[o.id]?.boss)??enemies.find(o=>h.chapter().enemies[o.id]?.boss);if(!boss)throw Error('このマップにボスはいません。Before Bossプリセットを使用してください');for(let r=2.8;r<=6;r+=.5)for(let i=0;i<24;i++){const a=i*Math.PI/12,px=boss.x+Math.sin(a)*r,pz=boss.z+Math.cos(a)*r;if(h.canMove(px,pz)){h.teleport(px,pz);mark(h.state());h.save();return}}throw Error('安全な着地点がありません')},battle);
 button('撃破済みにする（ボスは戦闘から）',async()=>{safe();const id=enemySelect.value;if(!h.chapter().enemies[id])throw Error('敵を選択してください');if(h.chapter().enemies[id].boss)throw Error('ボスは戦闘開始 → Instant Winで通常の勝利イベントを実行してください');const n=structuredClone(h.state());recordVictory(n.campaign,id,false);await replace(n)},battle);
 button('撃破状態を解除',async()=>{safe();const id=enemySelect.value;if(!h.chapter().enemies[id])throw Error('敵を選択してください');const n=structuredClone(h.state()),p=progress(n.campaign);p.defeatedEnemies=p.defeatedEnemies.filter(x=>x!==id);p.bosses=p.bosses.filter(x=>x!==id);if(h.chapter().enemies[id].boss){p.completed=false;reconcile(n)}await replace(n)},battle);
 button('Boss撃破済みにする（勝利イベント実行）',()=>{safe();h.defeatBoss(enemySelect.value)},battle);button('Instant Win',()=>h.win(),battle);el('p','戦闘コマンド待ち中のみ。本編の勝利・報酬・ボスイベントを実行。試練の即クリアは対象外。',battle);
 const save=section('Save'),json=el('textarea','',save) as HTMLTextAreaElement;json.setAttribute('aria-label','Save JSON');button('Read Save JSON',()=>{json.value=exportSave(h.state())},save);button('Copy Save JSON',async()=>{json.value=exportSave(h.state());await navigator.clipboard.writeText(json.value)},save);button('Export Save JSON',()=>{const url=URL.createObjectURL(new Blob([exportSave(h.state())],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='lumenfall-debug-save.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)},save);
 button('Import Save JSON',async()=>{safe();await replace(importSave(json.value))},save);button('Save now',()=>{safe();mark(h.state());h.save()},save);button('Reload save',async()=>{safe();await h.reload()},save);
 button('Reset current Chapter progress',async()=>{safe();if(confirm('現在Chapterの進行をリセットしますか？（DEBUG専用）')){const n=resetChapter(h.state());await replace(await travel(n,n.campaign.currentChapter))}},save);
 button('Reset all save data (DEBUG only)',async()=>{safe();if(confirm('DEBUG専用セーブをすべてリセットしますか？')&&confirm('通常セーブと設定は残します。DEBUGデータをリセットしますか？')){await replace(resetAll());localStorage.removeItem(DEBUG_SAVE);h.save()}},save);
 button('Disable DEBUG',()=>{const u=new URL(location.href);u.searchParams.set('debug','0');location.href=u.href},save);
 let signature='';async function readEnemies(){const id=h.chapter().id,area=h.state().area;let rows=[...h.objects().filter(o=>!!h.chapter().enemies[o.id])];const loaders:Record<string,()=>Promise<any>>={'chapter-1':()=>import('../chapters/chapter-1/object-config.ts'),'chapter-2':()=>import('../chapters/chapter-2/object-config.ts'),'chapter-3':()=>import('../chapters/chapter-3/object-config.ts')};if(loaders[id]){const data=await loaders[id]();if(disposed||h.chapter().id!==id||h.state().area!==area)return;for(const o of data.placements[area]??[])if(h.chapter().enemies[o.id]&&!rows.some(r=>r.id===o.id))rows.push({...o,r:2.3});}if(id==='chapter-1'&&area===2){for(const id of Object.keys(h.chapter().enemies))if(!rows.some(o=>o.id===id)&&['boss','sentinel','sentinel-east'].includes(id))rows.push({id,name:id,kind:'enemy',x:id==='sentinel'?-14:id==='sentinel-east'?14:0,z:id==='boss'?-16:4,r:2.3})}enemies=rows;options(enemySelect,rows.map(o=>({id:o.id,title:o.name+(progress(h.state().campaign).defeatedEnemies.includes(o.id)?' [撃破済]':'')})))}
 function update(){if(disposed)return;const s=h.state(),c=h.chapter(),sig=c.id+':'+s.area;if(sig!==signature){signature=sig;chapterSelect.value=c.id;options(mapSelect,c.maps.map(m=>({id:String(m.id),title:m.id+' · '+m.name})));mapSelect.value=String(s.area);options(presetSelect,(presets[c.id]?.names??[]).map(n=>({id:n,title:n})));void readEnemies().catch(e=>status.textContent=String(e));progressJSON.value=JSON.stringify(progress(s.campaign),null,2)}if(root.open)info.textContent=JSON.stringify({chapter:c.id,title:c.title,area:s.area,map:c.maps.find(m=>m.id===s.area)?.name,x:+s.x.toFixed(2),z:+s.z.toFixed(2),hp:s.hp,mp:s.mp,level:s.lv,xp:s.xp,gold:s.gold,potions:s.potions,ethers:s.ethers,walkable:h.canMove(s.x,s.z),interactionRadius:h.objects().map(o=>({id:o.id,r:o.r})),render:h.stats()},null,2)}
 for(const event of ['keydown','keyup','pointerdown','pointerup','click'])root.addEventListener(event,e=>e.stopPropagation());root.addEventListener('focusin',()=>h.stop());document.body.append(root);update();const timer=setInterval(update,500);return()=>{disposed=true;clearInterval(timer);root.remove()};
}
